### ISSUE TITLE
diff_iso_usage.py produces unexpected results with 0.0 counts

### ISSUE THREAD

**Issue by WalterMuskovic** [BrooksLabUCSC/flair#101]
Hi @belgravia 
Thank you for producing and maintaining this excellent tool. I just came across this issue when using _diff_iso_usage.py_:

```
cat test_data.tsv
ids     x       y
isoformA_gene1  10.0    5.0
isoformB_gene2  0.0     1.0
isoformC_gene3  8.0     6.0
isoformD_gene4  0.0     0.0

python diff_iso_usage.py test_data.tsv x y diff_isos_test.txt
cat diff_isos_test.txt
gene1   isoformA        NA      10.0    5.0     0       0
gene2   isoformA        NA      10.0    5.0     0       0
gene3   isoformC        NA      8.0     6.0     0       0
gene4   isoformC        NA      8.0     6.0     0       0
```
The output isoform names and the counts don't match with the input. Any help would be greatly appreciated!

**Comment by belgravia** [comment]
Thanks for catching this bug. It shouldn't matter for real data, but I am happy this is fixed. 

For isoforms where there is a 0.0 count, flair ignores these (see #91). I will continue to have the script ignore these isoforms and not test them. I have now fixed the bug such that the ignored isoforms that have 0 counts will still have their counts variable properly updated and reflective of the correct counts. 

This is the output I get now for your test file, with the updated diff_iso_usage.py script:

> gene1   isoformA        NA      10.0    5.0     0       0
gene2   isoformB        NA      0.0     1.0     0       0
gene3   isoformC        NA      8.0     6.0     0       0
gene4   isoformD        NA      0.0     0.0     0       0

-Alison
