### ISSUE TITLE
plot_isoform_usage.py: TclError

### ISSUE THREAD

**Issue by bsaintjo** [BrooksLabUCSC/flair#103]
Some people are running into issues with a Tcl/TkError running plot_isoform_usage.py. The common fix is to add something like:
```python3
import matplotlib
matplotlib.use("Agg")
```
to the top so that it works properly.

**Comment by belgravia** [comment]
Thanks! I have added those lines of code to the plot_isoform_usage.py script with the recent commit. In the future, you are welcome to open a pull request for something like this. 
-Alison

**Comment by yoon5812** [comment]
Hello Alison,

I've got the same error although those two lines were in your script.

When I moved those two lines to the very beginning of the script, it worked perfectly.
The script must start with these two lines.

Yoon

**Comment by belgravia** [comment]
Ok, I have updated this with the latest commit. Thanks!!
-Alison
