### ISSUE TITLE
novel transcripts located in UTR and reads mapped to wrong places 

### ISSUE THREAD

**Issue by robinycfang** [BrooksLabUCSC/flair#104]
Hello,

I ran into a few issues when I tried to use FLAIR to identify some novel transcripts from ONT data. I realized that when I visualize the results in igv, some "novel" transcripts located in the 5' or 3' UTR of annotated genes are actually labelled as "novel" transcript and gene (e.g., the first picture below, the last novel transcript is located in the 3' UTR of gene HSD17B6), but I think cases like this are mostly likely false positives? These novel transcripts just look weird to me.

The second thing is that for example, I blast this novel transcript sequence (the second picture), and found hits on an annotated transcripts on a different chromosome, so it seems like this chunk of "novel" transcript should be a spliced mature mRNA from another gene. But I guess this is the problem of minimap2, as it has something to do with how the aligner assigns reads. ps. I only used primary alignments for FLAIR analysis as I wanted to have a higher accuracy.

My command lines are here:
`python flair.py correct -c chr_length.txt -q sample.bed -o out_file_base_name -g Homo_sapiens.GRCh38.dna.primary_assembly.fa -f gencode.v32.annotation_nochr_MT.gtf -j junction_filtered.bed -t threads`
`python flair.py collapse -r prim1.fastq,prim2.fastq,prim3.fastq -q flair_all_corrected_master.psl -g Homo_sapiens.GRCh38.dna.primary_assembly.fa -f gencode.v32.annotation_nochr.gtf --stringent -t threads`

![pic3](https://user-images.githubusercontent.com/17020046/76418835-4cc1a180-63da-11ea-8447-71345beda92d.png)

![pic1](https://user-images.githubusercontent.com/17020046/76396567-651ec580-63b4-11ea-989b-098392001325.png)

**Comment by belgravia** [comment]
So the first way flair-collapse (specifically, the identify_gene_iso.py script) renames flair isoforms using the annotation is by matching the isoforms based on splice junctions. The _gene name_ is identified If the flair isoform shares some splice junctions as an annotated gene. The _isoform name_ is identified if the flair isoform shares the exact same splice junction chain as the annotated isoform. The second way applies to single exon genes only, in which the single-exon flair isoform must span at least 80% of the annotated single-exon gene. I currently don't do any comparisons between single-exon isoforms and multi-exon isoforms in the renaming step. 

By default, flair align only uses primary alignments (`secondary==no` in the minimap command). You could also try enforcing a mapping quality score cutoff for the alignments to try and reduce the number of ambiguous fragments prior to running the correct module and the rest of the pipeline.

-Alison

**Comment by robinycfang** [comment]
Hi Alison,

Thanks for your reply. 

First case: so my understanding is that a single-exon isoform mapped to an annotated multiple-exon gene (like this case) will only be annotated with a novel gene name? However, if a single-exon isoform is mapped 80% to an annotated single-exon gene (like a gene only coding for a lncRNA) will be annotated with a known gene name. Is that correct? Also, I used --stringent to remove reads that cover <80% of the transcripts and less than 25bp of the first and last exons, so theoretically the isoform in this case should be filtered out, but I assume the --stringent step only applies to annotated genes?  

For the two kinds of transcripts that I asked about, do you think they exist or just false positives? Might be novel ncRNAs? Do you have any previous experience seeing stuff like this?

**Comment by belgravia** [comment]
To your first two questions, yes, your understanding is correct. 

To the third question, the --stringent filter applies to all genes, not just those that are annotated. When flair is "grouping" together similar reads in the collapse step to determine the isoforms, flair will by default allow for truncated (but uniquely assigned) reads to be counted. The groups of reads that have 3+ more reads are kept. With the --stringent filter on, there must be 3+ reads in the isoform group that are considered full-length for the isoform to be kept. Hope that helps.

To the last questions, yes I've seen these in my data before. I am not sure what the best way to treat them is because they are short and, as you noticed, often map to multiple locations. I'm not sure if any of them are real, or if there is a way for us to tell if they are real or not. 
-Alison
