### ISSUE TITLE
flair collapse output doesn't contain any info from the gtf

### ISSUE THREAD

**Issue by wolfgangrumpf** [BrooksLabUCSC/flair#106]
I ran flair collapse with this command:

```
python flair.py collapse --threads $cores -g GRCh38.99.fa \
     -r ccs.fastq -q flair_all_corrected.bed \
     --gtf GRCh38.99.gtf
```
     
My output contains no gene or novelty information - is this expected?

```
2	FLAIR	exon	24083627	24085636	.	-	60	gene_id "2:24083000"; transcript_id "m64034_200216_143134/99092981/ccs"; exon_number "0";
2	FLAIR	transcript	24096796	24101283	.	+	.	gene_id "2:24096000"; transcript_id "m64034_200216_143134/176816480/ccs";
2	FLAIR	exon	24096796	24101283	.	+	60	gene_id "2:24096000"; transcript_id "m64034_200216_143134/176816480/ccs"; exon_number "0";
2	FLAIR	transcript	24098974	24101559	.	-	.	gene_id "2:24098000"; transcript_id "m64034_200216_143134/72092227/ccs";
2	FLAIR	exon	24098974	24101559	.	-	60	gene_id "2:24098000"; transcript_id "m64034_200216_143134/72092227/ccs"; exon_number "0";
2	FLAIR	transcript	24262357	24266786	.	+	.	gene_id "2:24262000"; transcript_id "m64034_200216_143134/127991996/ccs";
2	FLAIR	exon	24262357	24266786	.	+	60	gene_id "2:24262000"; transcript_id "m64034_200216_143134/127991996/ccs"; exon_number "0";
2	FLAIR	transcript	24306810	24311495	.	+	.	gene_id "2:24306000"; transcript_id "m64034_200216_143134/113706433/ccs";
2	FLAIR	exon	24306810	24311495	.	+	60	gene_id "2:24306000"; transcript_id "m64034_200216_143134/113706433/ccs"; exon_number "0";
2	FLAIR	transcript	24507436	24511661	.	-	.	gene_id "2:24507000"; transcript_id "m64034_200216_143134/21890648/ccs";
```

**Comment by belgravia** [comment]
Yes, if you provide a gtf that is formatted in a way that is compatible with flair (i.e. it needs to contain a transcript_id and gene_id field) then you should have meaningful gene_id and transcript_Id fields in the flair collapse gtf output. And no, the novelty information is not an expected output if by novelty you mean categories like 'novel isoform with annotated splice junctions' or 'novel isoform containing unannotated splice junctions'. I have a custom script to do this, and the tool SQANTI does this as well.

If there's an issue with how flair collapse is finding the gene names, would you mind sending me a link to where you downloaded your gtf just so I can take a look?
-Alison

**Comment by wolfgangrumpf** [comment]
I downloaded build 99 from Ensembl (ftp://ftp.ensembl.org/pub/release-99/gtf/homo_sapiens/Homo_sapiens.GRCh38.99.gtf.gz).  I was hoping to find Novel not in Catalog (like Sqanti) - I'm actually hoping to use flair to confirm cupcake/SQANTI2 data.

**Comment by belgravia** [comment]
The gtf looks fine to me. Are the gene names and isoform names also misformatted in the output isoforms bed file? They're supposed to be formatted like "ENST00000456328_ENSG00000223972". 

I would expect for the flair isoforms that do not match existing genes/isoforms to have names formatted like the ones in the gtf you initially put here. Unknown genes are formatted `chromosome:coordinate` and unknown isoforms keep the original read name format. But if they are all formatted incorrectly, then I would suspect that there's probably something wrong with the input files or with flair.
-Alison

**Comment by wolfgangrumpf** [comment]
There are no gene names at all in the output bed files!
```

[rwr002@qmaster01 flair]$ head flair_all_corrected.bed
1	14401	20705	m64034_200216_143134/28117327/ccs;0	1	-	14401	20705	217,95,2	4	2364,198,510,2791,	0,2456,2831,3513,
1	14403	19166	m64034_200216_143134/7342371/ccs;0	3	-	14403	19166	217,95,2	4	1544,159,198,1934,	0,2203,2454,2829,
1	14403	20669	m64034_200216_143134/105646222/ccs;16	9	-	14403	20669	217,95,2	6	1544,159,198,510,147,2402,	0,2203,2454,2829,3511,3864,
1	14403	21483	m64034_200216_143134/142148003/ccs;16	16	-	14403	21483	217,95,2	3	2362,885,3569,	0,2454,3511,
1	14403	18755	m64034_200216_143134/170983864/ccs;16	1	-	14403	18755	217,95,2	5	1544,159,198,510,841,	0,2203,2454,2829,3511,
1	14615	23493	m64034_200216_143134/59115836/ccs;16	4	-	14615	23493	217,95,2	6	1332,159,198,510,147,5226,	0,1991,2242,2617,3299,3652,
1	16441	22450	m64034_200216_143134/116196539/ccs;0	11	-	16441	22450	217,95,2	6	324,198,136,137,147,4183,	0,416,791,1164,1473,1826,
1	16441	18890	m64034_200216_143134/19334967/ccs;0	15	-	16441	18890	217,95,2	4	324,198,510,976,	0,416,791,1473,
1	16441	22450	m64034_200216_143134/137691229/ccs;16	6	-	16441	22450	217,95,2	6	324,198,136,137,147,4183,	0,416,791,1164,1473,1826,
1	16867	24882	m64034_200216_143134/128780190/ccs;0	1	-	16867	24882	217,95,2	6	188,136,137,147,99,145,	0,365,738,1047,1400,7870,
[rwr002@qmaster01 flair]$ head flair.collapse.isoforms.bed
2	218148	223908	m64034_200216_143134/170590876/ccs_2:218000	60	+	218148	223908	2	1	5760,	0,
2	234875	242459	m64034_200216_143134/32442401/ccs_2:234000	60	+	234875	242459	1	1	7584,	0,
2	258394	264139	m64034_200216_143134/23332782/ccs_2:258000	60	+	258394	264139	2	1	5745,	0,
2	264946	272014	m64034_200216_143134/100860339/ccs_2:264000	60	-	264946	272014	3	1	7068,	0,
2	663876	668976	m64034_200216_143134/156633068/ccs_2:663000	60	-	663876	668976	2	1	5100,	0,
2	669599	674062	m64034_200216_143134/139985071/ccs_2:669000	60	+	669599	674062	1	1	4463,	0,
2	1633166	1638280	m64034_200216_143134/157025634/ccs_2:1633000	60	-	1633166	1638280	1	1	5114,	0,
2	1646889	1651314	m64034_200216_143134/142148546/ccs_2:1646000	60	-	1646889	1651314	2	1	4425,	0,
2	1681309	1688662	m64034_200216_143134/135660744/ccs_2:1681000	60	-	1681309	1688662	1	1	7353,	0,
2	1690826	1693388	m64034_200216_143134/141165421/ccs_2:1690000	60	-	1690826	1693388	1	1	2562,	0,
```

**Comment by wolfgangrumpf** [comment]
Here's the script I'm using:
```

# Set Number of cores to use
cores=47

# Flair Align
python flair.py align --threads $cores -g GRCh38.99.fa -r ccs.fastq


# Flair Correct
python flair.py correct --threads $cores -q flair.aligned.bed -g GRCh38.99.fa \
     --gtf GRCh38.99.gtf --print_check


# Flair Collapse - FAILS  failed to write the results, might need PSL of aligned/corrected reads???
# DO NOT use --generate_map, it causes this step to fail
python flair.py collapse --threads $cores -g GRCh38.99.fa \
     -r ccs.fastq -q flair_all_corrected.bed \
     --gtf GRCh38.99.gtf
```

**Comment by wolfgangrumpf** [comment]
As you can see my inputs are the genome in fasta format and a fastq of our sequencing output.

**Comment by belgravia** [comment]
The script you wrote looks right. 

I looked at the few isoforms that you posted of the collapse .bed, and those don't match any isoforms in the gtf you are using and so this looks like standard flair behavior. If you can find an example of a spliced isoform that should get renamed and isn't getting renamed, that would be helpful for me. 

In response to the issues you noted in the comments of your script: it looks like you are having issues with --generate map, and flair-collapse isn't writing any results? I think I found the issue there, see if you still have issues when you run `--generate_map` in the latest commit. Also, collapse should work fine with bed files. If you can send me what error messages/notes flair is printing, that would be helpful in debugging where the problematic steps are.

-Alison
