### ISSUE TITLE
shebang headers of the python scripts

### ISSUE THREAD

**Issue by lucacozzuto** [BrooksLabUCSC/flair#109]
Dear developers,
I'm wondering we can have the shebang headers for the python scripts.

Something like:
#!/usr/bin/env python3

I see that correctSplice.py and junctions_from_sam.py: have hardcoded this: #!/usr/bin/python

Thanks
Luca

**Comment by belgravia** [comment]
Hi Luca,

I have added shebang headers now! Thanks for your patience.

-Alison
