### ISSUE TITLE
Error at flair collapse

### ISSUE THREAD

**Issue by martynakgajos** [BrooksLabUCSC/flair#11]
I get a following messages running flair 

Collapsing isoforms
Make sure all files (query, GTF) have valid paths and can be opened
Filtering isoforms
usage: script.py collapsed.psl (default/comprehensive/ginormous) filtered.psl [tolerance]
mv: cannot stat ‘$base.corrected_all_corrected.firstpass.filtered.psl’: No such file or directory
Renaming isoforms
usage: script.py psl gtf isos_matched.psl 

What might be my problem here?
My code:
````
python` $flair align -r $fnano -g $genome -m $minimap -o $base -sam $samtools
python $scriptdir"bam2Bed12.py" -i $base".sam" > $base".bed12"
python $scriptdir"junctions_from_sam.py" -s $frna -n shortreads
python $flair correct -f $annotation -c $chrSize -q $base".bed12" -j shortreads_junctions.bed -o $base".corrected"
python $flair collapse -r $fnano -q $base".corrected_all_corrected.psl" -g $genome -m 
$minimap -o $base -f $annotation -sam $samtools
````

**Comment by csoulette** [comment]
Hi martynakgajos,

I can't see any noticeable errors in the way you've written out your commands, but it looks like FLAIR was expecting a file to exists that may not have actually been created. Can you confirm if there are any intermediate files that were created in your run? Namely, there should be two BED formatted files containing your reads that have had their splice sites corrected. One should contained a label "corrected" and the other should be labeled "inconsistent." Can you check for these and whether or not the files contain any read information?

-CMS

**Comment by martynakgajos** [comment]
Following files exist: 
$base".corrected_all_corrected.psl"
$base".corrected_all_corrected.bed"
$base".corrected._all_inconsistent.bed", and they look good.
However, there is no file: $base".corrected._all_inconsistent.psl" - should it be created? No error message was created by previous commands.

Additional files created in the process:
$base.sam
$base.unsorted.bam
shortreads_junctions.bed
$base.bed12

**Comment by belgravia** [comment]
There isn't a psl made for the *_all_inconsistent.bed file. You're right in passing the corrected.psl to from flair-correct to flair-collapse. However it looks like flair-collapse is erroring at the very first step and can't open the corrected.psl that you're giving it, I'm guessing because of a bad path. 

Just to make sure - is the file made from the correction step `$base".corrected_all_corrected.psl"` or `$base.corrected._all_corrected.psl"`?
