### ISSUE TITLE
flair correct - empty output files 

### ISSUE THREAD

**Issue by dl870** [BrooksLabUCSC/flair#110]
Hi,

I ran flair.py correct with flair align bed output files using a -f argument and I get the correct output files, but empty. When running it shows the following - 

Step 1/5: Splitting junctions from GTF by chromosome: 100%|█| 13069/13069 [00:00<00:00, 
Step 3/5: Preparing annotated junctions to use for correction: 100%|█| 97/97 [00:00<00:0
Step 4/5: Preparing reads for correction: 1014it [00:00, 560271.93it/s]76/97 [00:00<00:0
Step 5/5: Correcting Splice Sites: 0it [00:00, ?it/s] ?it/s]
Step 5/5: Correcting Splice Sites: 0it [00:00, ?it/s]

- and no errors.

**Comment by belgravia** [comment]
Can you send me a link to where you downloaded your annotation file and your genome sequence file? It might have something to do with those. The _all_corrected.bed file being empty means that none of the aligned reads have splice junctions can be fuzzily matched to any splice sites present in the annotation. 
-Alison

**Comment by dl870** [comment]
https://parasite.wormbase.org/ftp.html - I am looking at Strongyloides ratti (pg6).

**Comment by belgravia** [comment]
Are both the *_inconsistent.bed and *_corrected.bed files empty? 

Thanks for sending that link. I looked at the gtf and genome fasta for pg6 and they seem fine.

-Alison

**Comment by mvheetve** [comment]
Hi,

same issue. Used same fasta as for alignment (Homo Sapiens), been using fasta and gtf succesfully for months with other tools and pipelines. Both output files are empty. 

Mattias

**Comment by belgravia** [comment]
I'm not sure what this issue is. It may be helpful for me if you could send me a couple of the lines from your aligned reads bed (or psl) file so I could try running flair-correct. Thanks for your patience!
-Alison

**Comment by mvheetve** [comment]
Hi Alison,

for me personally the issue was resolved by using a genomic fasta (.fna) in stead of regular one (.fa). No idea, why, maybe the file just got corrupted. 

Regards
Mattias

**Comment by belgravia** [comment]
Ok, that's good to hear. As long as the genome sequence is formatted like

>header
sequence
sequence
>header

and there are no weird line endings, then it should work for FLAIR. 
-Alison
