### ISSUE TITLE
Flair diffExp's runDE stderr 'rpy2.rinterface.RRuntimeError: Error in results(dds, name = name)'

### ISSUE THREAD

**Issue by chalybes** [BrooksLabUCSC/flair#112]
Hello everyone, 

I have yet another rpy2.rinterface.RRuntimeError, I made sure to have rpy2 v2.9 and I have run all preceding steps successfully, but when I reach the point of running diffExp I get this exception: 

```
rpy2.rinterface.RRuntimeError: Error in results(dds, name = name) :
the argument 'name' should be a character vector of length 1
```

I can't seem to troubleshoot out why I'm getting these errors, _drimseq2_results.tsv, filtered_gene_counts_ds2.tsv, filtered_iso_counts_drim.tsv, filtered_iso_counts_ds2.tsv, formula_matrix.tsv all get produced but runDE.py outputs that dge_stderror.

**Comment by belgravia** [comment]
The error looks like a DESeq2 error and it looks like the DESeq2 output files were not produced (differential isoform expression & differential gene expression). 

It might be caused by an issue with how you are naming your samples/conditions/batches in your manifest file provided to flair-quantify. Would you mind sending the first line of your counts_matrix.tsv?

-Alison

**Comment by chalybes** [comment]
Thanks for the quick response! Here is the first line from the counts_matrix.tsv: 

`ids     A10BC09_Lamp5Lsp1.Cells_batch1  A10b_Lamp5Lsp1.Cells_batch1 ...`

**Comment by chalybes** [comment]
I'm paranoid that maybe I may not have run a step or steps correctly in the pipeline. Here is a screenshot of what the head of counts_matrix.tsv looks like: 

![image](https://user-images.githubusercontent.com/10459147/81324541-f96f7680-904b-11ea-8331-f285d97ed04c.png)

First couple of lines for the collapsed.isoform.psl: 

![image](https://user-images.githubusercontent.com/10459147/81324692-2f145f80-904c-11ea-8a2d-ddd13fd8e950.png)

Stack trace of the DESeq2 error: 

![image](https://user-images.githubusercontent.com/10459147/81325494-4a339f00-904d-11ea-9f96-e3ef2a8c5087.png)


I was able to call plot_isoform_usage.py, but I'm hoping I can use diffExp to see clearer results.

**Comment by belgravia** [comment]
Your files look fine. Could you send me the command you're using to run quantify?

Also, this only applies if you have more than 2 conditions, but you will want to subset the count columns of your counts_matrix.tsv such that it only contains the columns corresponding to samples for the 2 groups that you are comparing.

-Alison

**Comment by chalybes** [comment]
Aha, it works now! I changed `counts_matrix.tsv` to specifically contain 2 groups and now diffExp runs. Thank you!
