### ISSUE TITLE
collapse psl_to_gtf.py IndexError: list index out of range

### ISSUE THREAD

**Issue by mvheetve** [BrooksLabUCSC/flair#114]
Hi,

`python flair.py collapse -f GRCh37.p13_genomic.gtf -g GRCh37.p13_genomic.fna -q flair_all_corrected.bed -r sample.fastq`

gave this output:
`Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Filtering isoforms
Renaming isoforms
Aligning reads to first-pass isoform reference
[M::mm_idx_gen::0.079*0.95] collected minimizers
[M::mm_idx_gen::0.099*1.44] sorted minimizers
[M::main::0.100*1.43] loaded/built the index for 393 target sequence(s)
[M::mm_mapopt_update::0.100*1.43] mid_occ = 312
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 393
[M::mm_idx_stat::0.101*1.42] distinct minimizers: 13975 (70.21% are singletons); average occurrences: 19.948; average spacing: 5.368
[M::worker_pipeline::2917.820*2.13] mapped 100793 sequences
[M::worker_pipeline::5086.950*2.45] mapped 103138 sequences
[M::worker_pipeline::9191.592*1.94] mapped 96586 sequences
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -t 4 -N 4 flair.collapse.firstpass.fa Desktop/EBV_qualtrimmed_filtered.fastq
[M::main] Real time: 9191.641 sec; CPU: 17869.178 sec; Peak RSS: 0.823 GB
Filtering isoforms by read coverage
Traceback (most recent call last):
  File "/Users/mvheetve/biotools/flair/bin/psl_to_gtf.py", line 51, in <module>
    print('\t'.join([chrom, 'FLAIR', 'transcript', line[15], line[16], '.', strand, '.', \
IndexError: list index out of range
Removing intermediate files/done`

please advise why list index is out of range. 
head gtf:
`#gtf-version 2.2
#!genome-build GRCh37.p13
#!genome-build-accession NCBI_Assembly:GCF_000001405.25
#!annotation-date 09/06/2019
#!annotation-source NCBI Homo sapiens Updated Annotation Release 105.20190906
NC_000001.10	BestRefSeq	gene	11874	14409	.	+	.	gene_id "DDX11L1"; db_xref "GeneID:100287102"; db_xref "HGNC:HGNC:37102"; description "DEAD/H-box helicase 11 like 1"; gbkey "Gene"; gene "DDX11L1"; gene_biotype "transcribed_pseudogene"; pseudo "true"; `

head bed:
`NC_000011.9	809974	810307	c7777a40-494d-415c-a1b8-1491de460cfd_1_1_3	60	+	809974	810307	255,0,0	2	65,74,	0,259,`

regards
Mattias

**Comment by belgravia** [comment]
Thanks for all the information. It looks like flair-collapse makes it all the way to the end and then errors on the script that converts the final isoform bed or psl to a gtf file. 

The line of code that it errors on (psl_to_gtf.py 51: `print('\t'.join([chrom, 'FLAIR', 'transcript', line[15], line[16], '.', strand, '.',`) must be from an older version of flair. I should have fixed this bug last [Novemberish](https://github.com/BrooksLabUCSC/flair/commit/e447fb249fe46633081df7e9c16a876b456d9ca4#diff-ca37cb855fe77a7193c16e82ecfdf1ce) it seems.

Do you think you can update to the newest release/commit of flair and try rerunning collapse? 
-Alison

**Comment by mvheetve** [comment]
Hi Alison,

yeah I've been using flair for a while now and I was still on v1.4. I updated and started collapse again. I'll let you know what the output says. 

Mattias

**Comment by mvheetve** [comment]
updating to v1.5 did the trick, sorry for the inconvenience.

Mattias
