### ISSUE TITLE
collapse output gtf has >3 frame exon rows

### ISSUE THREAD

**Issue by abs-yy** [BrooksLabUCSC/flair#117]
Hi, 
When I run collapse, the resulting gtf file has exon rows that have frames with values up to 60. Doesn't GTF frames normally have up to 2?

chr_4   FLAIR   transcript      26155   26400   .       -       .       gene_id "chr_4:26000"; transcript_id "cf127bef-68a2-4f16-bb3c-6
0c809448cad";
chr_4   FLAIR   exon    26155   26400   .       -       52      gene_id "chr_4:26000"; transcript_id "cf127bef-68a2-4f16-bb3c-60c809448
cad"; exon_number "0";
chr_4   FLAIR   transcript      26285   26521   .       -       .       gene_id "chr_4:26000"; transcript_id "d067c8f3-4ad5-48d6-93b0-e
2cc16f2d190";
chr_4   FLAIR   exon    26285   26521   .       -       60      gene_id "chr_4:26000"; transcript_id "d067c8f3-4ad5-48d6-93b0-e2cc16f2d
190"; exon_number "0";
chr_4   FLAIR   transcript      27181   28316   .       -       .       gene_id "chr_4:27000"; transcript_id "8774fc36-357e-4d25-921e-8
70b5633840a";
chr_4   FLAIR   exon    27181   28316   .       -       10      gene_id "chr_4:27000"; transcript_id "8774fc36-357e-4d25-921e-870b56338
40a"; exon_number "0";
chr_4   FLAIR   transcript      28528   28842   .       -       .       gene_id "chr_4:28000"; transcript_id "f1fb6f8f-dd45-44ae-9f09-3
95e5bfb11e5";
chr_4   FLAIR   exon    28528   28842   .       -       1       gene_id "chr_4:28000"; transcript_id "f1fb6f8f-dd45-44ae-9f09-395e5bfb1
1e5"; exon_number "0";

Thanks in advance.

**Comment by belgravia** [comment]
Thanks for catching this! Those numbers are the scores, which I put in the wrong column. They should be in the 6th column before the strand, but I accidentally put them in the 8th column, which is frame. That being said, I meant for that field to be a `.` just like it is for the transcript lines. In the next commit, the gtf conversion script will reflect the fixes I've made (the frame will be `.` for both transcript and exon lines.
-Alison

**Comment by abs-yy** [comment]
I'll replace the fields with a custom script for now.
Thanks for checking this out!
