### ISSUE TITLE
What ist the --trust-ends feature?

### ISSUE THREAD

**Issue by caspargross** [BrooksLabUCSC/flair#120]
Hi, 
can you explain the `--trust-ends` option for the collapse module?
Does it increase processing speed? Does it have any drawbacks? 
I use ONT cDNA reads preprocessed with pychopper. These should be long reads with minimal fragmentation, right? Or are you talking about Hifi-Reads with low Indel frequency?
Thanks,
Caspar

**Comment by belgravia** [comment]
Hi Caspar,

The --trust-ends feature is made for data where the 5' and 3' ends are assumed to be properly sequenced through.  I created this option for R2C2 ONT cDNA sequencing, which captures both ends well. Your cDNA reads processed with pychopper should fit this description.

It's used for breaking ties at the TSS/TES level. Say you have two candidate firstpass isoforms that have the same transcript model, except one isoform has a longer first exon. Default case - for a read where there is a relatively high chance that the ends are truncated (PCR, degradation, voltage spikes in the flow cell...), if the read supports the splice junction chain shared by these 2 isoforms but isn't long enough to uniquely support the isoform with the longer first exon, then that read is not counted. Trust_ends case - Flair will compare the distances from the read end to the candidate ends and also take the number of bases of the read that are not aligned at the ends (i.e. softclipped) into account. The read will be assigned to the isoform that the read is best able to reach the ends of with minimal softclipping. 

Let me know if you have questions. I'll incorporate this information into the README and in the collapse/quantify argument descriptions.

-Alison

**Comment by caspargross** [comment]
Thanks Allison, that answered my questions. I will use this option on my dataset, hopefully I will find time to benchmark this agains default options using untrimmed data and share the results with you.

Best, Caspar
