### ISSUE TITLE
Questions about "samJuncs.py"

### ISSUE THREAD

**Issue by Kyung-TaeLee** [BrooksLabUCSC/flair#121]
Hi, I am currently looking at the source code, "samJuncs.py" and have questions on the certain code block in the function, "inferMM2JuncStrand".

Here is the code block
"
```
if not juncDir:
            left, right = read.cigar[0], read.cigar[-1]
            s1, s2 = read.seq[:50], read.seq[-50:]
            #pa = str()
            if ("T"*10 in s1 and left[0] == 4 and left[1] >= 10) and ("A"*10 in s2 and right[0] == 4 and right[1] >= 10):
                # probably internal priming
                juncDir = "ambig"
            elif ("T"*10 in s1 and left[0] == 4 and left[1] >= 10):
                # maps to positive strand but has a rev comp polyA
                juncDir = "-" if orientation == 16 else "+"
                #print("anti")
                #pa = "ppa"
            elif ("A"*10 in s2 and right[0] == 4 and right[1] >= 10):
                # maps to positive strand but has a sense polyA
                juncDir = "+" if orientation == 16 else "-"
                #print("sense")
                #pa = "ppa"
            else:
                # no polyA or polyT. Fragment?
                juncDir = "ambig"
                #pa = "nan"
```
"

When there is no "ts" tag from the bam file outputted from minimap2, this functions tries to infer the actual strand of the transcript from which read was generated. 

When there are over 10 "T"s and more than 10 soft-clipped base at the leftmost position of the read sequence and Flag value is 16 (read sequenced being reverse-complemented), transcript strand is assumed as "-" strand and vice versa.

When you think about how Nanopore library prep is done for cDNA sequencing (shown below)
![Nanopore cDNA PCR1](https://user-images.githubusercontent.com/67738841/86349542-45c9e200-bc9c-11ea-92e8-dc704f5b937d.PNG)
![Nanopore cDNA PCR2](https://user-images.githubusercontent.com/67738841/86349555-4a8e9600-bc9c-11ea-9fd1-7f22fd0a2811.PNG)

the read with polyT at the leftmost position is first-strand cDNA molecule which is reverse-complementary to the actual RNA molecules (therefore, "ts" flag for this read should be "ts:A:-"). In this case, I think the transcript strand should be "+", not "-". 

It would be great if you can clarify this. Thank you and have a great day!

**Comment by Jeltje** [comment]
Hi gcorre, 

I'd like to help.
Please create a [new ticket](https://github.com/BrooksLabUCSC/flair/issues/new/choose) for this problem, since it is unrelated to issue 121.

Also please give the exact command you used, as well as the output of `flair --version`

**Comment by Jeltje** [comment]
[Flair is now conda installable.](https://flair.readthedocs.io/en/latest/index.html)

**Comment by Jeltje** [comment]
Re: the original question: @Kyung-TaeLee I agree this is confusing. Plus and minus here indicate the orientation of the nanopore read, not the gene (isoform) that it came from.
