### ISSUE TITLE
Error in plot_isoform_usage.py

### ISSUE THREAD

**Issue by GeertvanGeest** [BrooksLabUCSC/flair#122]
Hi there,

I was playing around with flair with data from [this](https://www.nature.com/articles/s41380-019-0583-1) paper, and all seemed to work well untill I used plot_isoform_usage:

```
python3 ./flair/bin/plot_isoform_usage.py \
CACNA1C_productivity.bed \
counts_matrix.tsv \
ENSG00000151067
```

It gave me the following error:

```
Traceback (most recent call last):
  File "./flair/bin/plot_isoform_usage.py", line 257, in <module>

    isoforms, lower, upper, strand, names = parse_psl(psl,keepiso=keepiso)
  File "./flair/bin/plot_isoform_usage.py", line 66, in parse_psl
    return info, lowbound, upbound, strand, usednames
UnboundLocalError: local variable 'strand' referenced before assignment
```

Am I missing something here?

Thanks in advance.

**Comment by belgravia** [comment]
Hi,

Sorry that error isn't a descriptive error, I'll add better error handling for that. Can you double check that your gene name is found in the bed file when you `grep` for it? 

-Alison

**Comment by GeertvanGeest** [comment]
Thanks for the reply.
The gene name in there, actually in every line in the bed file (which might be the issue?). 

Here's the first 8 columns and 5 lines of the bed file:
```
12      2053537 2691293 ERR3577080.1232_PRO_ENSG00000151067     60      +       2053562 2691199
12      2053537 2691293 ERR3577080.2070_PRO_ENSG00000151067     60      +       2053562 2691199
12      2053537 2691293 ENST00000399641_PRO_ENSG00000151067     60      +       2053562 2691199
12      2053537 2691293 ERR3577080.631_PRO_ENSG00000151067      60      +       2053562 2691199
12      2053537 2691293 ERR3577080.1725_PRO_ENSG00000151067     60      +       2053562 2691199
```
And the first 10 lines of counts_matrix.tsv:
```
ids     p5238_cingulate_cortex_batch1   p5346_dorsolateral_prefrontal_batch1
ENST00000327702_ENSG00000151067 2.0     8.0
ENST00000335762_ENSG00000151067 17.0    19.0
ENST00000399597_ENSG00000151067 18.0    19.0
ENST00000399601_ENSG00000151067 69.0    22.0
ENST00000399603_ENSG00000151067 5.0     9.0
ENST00000399634_ENSG00000151067 3.0     2.0
ENST00000399637_ENSG00000151067 3.0     7.0
ENST00000399638_ENSG00000151067 4.0     60.0
ENST00000399641_ENSG00000151067 2168.0  1365.0
```

**Comment by ozgegizlenci** [comment]
Hello,

I get the same error when I use the outputs from predictProductivity function to visualize the productivity of the isoforms with the plot_isoforms_usage.py function. Were you able to solve that?

**Comment by samir-watson** [comment]
Hi
Im getting the same error as well.

**Comment by GeertvanGeest** [comment]
I've rerun the analysis with the latest version of FLAIR, and didn't run into issues. Will therefore close this issue.

**Comment by ozgegizlenci** [comment]
I am using the latest version of FLAIR and still receiving the same error.
