### ISSUE TITLE
Flair needs samtools 1.6 to work

### ISSUE THREAD

**Issue by xyloforce** [BrooksLabUCSC/flair#124]
Hello,

I've been working on Flair v1.5 installed via conda in a empty env and I stumbled upon a issue with flair collapse : error message is "samtools view: failed to add PG line to the header" and it ends up with empty files flair.collapse.isoforms.bed/.fa

I fixed it by asking conda to downgrade samtools 1.7 (automatically installed in the env) to 1.6, but I think that needs to be mentionned ?

Attached is the output for flair collapse.
[slurm-1396734.txt](https://github.com/BrooksLabUCSC/flair/files/4980845/slurm-1396734.txt)

**Comment by belgravia** [comment]
I just tried running collapse with samtools v1.7 on my testing data and it worked. It is strange the switching to 1.6 fixed the error for you, and that it had an error with writing the PG line. There's also so many errors about the duplicated read sequence. I wasn't able to find anything particularly helpful from googling that error. I'd suspect that those errors may be from the data being passed in and not the version of samtools or minimap2. 

It will be hard for me to debug this without being able to recreate your error. You are welcome to send me enough of your data such that I can recreate your error. We can also just wait to see if anyone else runs into this issue.

-Alison

**Comment by xyloforce** [comment]
You'll find at this URL : http://tools.genouest.org/data/tderrien/cnrs_umr6290/flair-test-files.tar.gz
- a subset of the fastq files, created via seqtk : `seqtk sample -s 10 data.fastq 1000 > subset.fastq`
- a sam file created via minimap : `minimap2 -t 6 -ax splice --MD --junc-bed Ensembl_converted.bed ref_genome.fa subset.fastq > subset.sam`
- a bam file created via samtools : `samtools view -@ 6 -b subset.sam | samtools sort -o subset.bam`
- a bed file converted using the bamToBed script : `bamToBed -bed12 -i subset.bam > subset_converted.bed12`
- the output of `flair.py correct -q subset_converted.bed12 -g ref_genome.fa -f ref_anot.gtf`

The command who fails is `flair.py collapse -g ref_genome.fa -r subset.fastq -q flair_all_corrected.bed`, it produces an empty output.
The ref annot is the Ensembl dog annotation and the ref genome is the build CanFam3.

**Comment by Jeltje** [comment]
I would like to have a look at this issue, but I don't have access to that link (I get `403 Forbidden`).

**Comment by Jeltje** [comment]
We have released Flair v1.6.0
Please reopen this ticket if you still have trouble.
