### ISSUE TITLE
runDS error

### ISSUE THREAD

**Issue by BeatrizdeToledo** [BrooksLabUCSC/flair#126]
Good afternoon,
I just used Diffslpice and in the stderr file i got this warning:

Traceback (most recent call last):
  File "/group/calegari_beatrizepi/DESALTTIRDTRY/Flair/flair-master/bin/runDS.py", line 32, in <module>
    from rpy2.rinterface import RRuntimeWarning
ImportError: cannot import name RRuntimeWarning

I converted my gtf file *output of sqanti* into bed file and used the count.file output of the rsem as the input. This was my command

python flair.py diffSplice -i PP_DP_N_tama_sqanti_classification.filtered_lite.bed -q PP_DP_matrix_rename.counts.txt --test -t 20 

This was the head of one of the tsv events

head flair.diffsplice.alt3.events.quant.tsv
feature_id    coordinate        PPL393_conditionA_batch1        PPL355_conditionA_batch2        PPL222_conditionA_batch3        DPL394_conditionB_batch1        DPL356_conditionB_batch2        DPL223_conditionB_batch3  isoform_ids
inclusion_GL456233.1:39024      GL456233.1:39024-32584_GL456233.1:39024-32546   92.03   87.66   57.36000000000001       78.19   60.22   61.95   PB.20168.4,PB.20168.7,PB.20168.8,PB.20168.11,PB.20168.12,PB.20168.14,PB.20168.15,PB.20168.17,PB.20168.19,PB.20168.20,PB.20168.21
exclusion_GL456233.1:39024      GL456233.1:39024-32584_GL456233.1:39024-32546   0.0     2.63    0.0     0.0     0.0     5.02    PB.20168.5,PB.20168.13,PB.20168.18
inclusion_GL456216.1:31471      GL456216.1:31471-34085_GL456216.1:31471-34137   220.73000000000002      122.16999999999999      128.06  88.11   158.48000000000002      134.63  PB.20175.3,PB.20175.11,PB.20175.15

**Comment by belgravia** [comment]
I think the events quant file looks like it is formatted correctly. So your rsem counts and squanti bed seem to not be the issue for now. 

> ImportError: cannot import name RRuntimeWarning

Just making sure, did flair-diffsplice output a tsv file with the DRIMSeq2 results? If DRIMSeq was run successfully, then you can ignore warnings that have to do with rpy2 version differences... I'm not sure what causes the ImportError however; I tried to google the error verbatim and got nothing. 

-Alison

**Comment by Jeltje** [comment]
Please reopen this ticket if you still have trouble using the latest version of Flair (v1.6.0 as I write this).
