### ISSUE TITLE
`pip install flair` does install non-specfic flair (A very simple framework for state-of-the-art NLP)

### ISSUE THREAD

**Issue by akk01** [BrooksLabUCSC/flair#132]
i did following:
`$conda create -n flair python=3.6.5`
`$source activate flair`

But it installed wrong flair:
https://pypi.org/project/flair/

**Comment by callumparr** [comment]
You can try `conda install -c bioconda flair`

**Comment by Jeltje** [comment]
Flair is now available as `pip install flair-brookslab`
