### ISSUE TITLE
"flair.py correct" error occured

### ISSUE THREAD

**Issue by swZhang1** [BrooksLabUCSC/flair#133]
Hello, 
        when i run the "correct" command ,error occured as below:
```
index file /home/wwkong/Arabidopsis-genome/ensembl.plants/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa.fai not found, generating...
WARNING. chromosome (chrX) was not found in the FASTA file. Skipping.
Step 1/5: Splitting junctions from GTF by chromosome: 100%|██████████████████████████████████████████████████| 54013/54013 [00:00<00:00, 118577.50it/s]
Step 3/5: Preparing annotated junctions to use for correction: 100%|█████████████████████████████████████████████████████| 7/7 [00:00<00:00, 17.63it/s]
Step 4/5: Preparing reads for correction: 1207102it [00:02, 583114.35it/s]███████████████████████████████████████████████| 7/7 [00:00<00:00, 20.07it/s]
Step 5/5: Correcting Splice Sites: 100%|█████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 61.51it/s]
Traceback (most recent call last):   0%|                                                                                         | 0/7 [00:00<?, ?it/s]
  File "/home/wwkong/miniconda3/flair/bin/ssCorrect.py", line 425, in <module>
    main()
  File "/home/wwkong/miniconda3/flair/bin/ssCorrect.py", line 407, in main
    with open(os.path.join(tempDir, "%s_inconsistent.bed" % chrom),'rb') as fd:
IOError: [Errno 2] No such file or directory: '/home/wwkong/miniconda3/flair/tmp_5e865ca3-94e2-4a87-93eb-d9ad320d7ff1/Pt_inconsistent.bed'
Correction command did not exit with success status
```
The commandline record is :
```
python flair.py correct -q /home/wwkong/NAD_tag_3G/SRR8660547.bed -g /home/wwkong/Arabidopsis-genome/ensembl.plants/Arabidopsis_thaliana.TAIR10.dna.toplevel.fa -f /home/wwkong/Arabidopsis-genome/ensembl.plants/Arabidopsis_thaliana.TAIR10.47.gtf --print_check
```
what should i do to deal with it?

Looking forward to your reply.
Regards,
Zhang
20200914

**Comment by ClemV-O** [comment]
Hello, 
I got the same problem of you and will be please to see how you manage to fix it. 

my command line :  
`python /home/apps/flair/flair.py correct -q SequinMixA_rescuedFullLen_mm2spliceNoseck14.sam.bed12 -g /home/refs/sequins/chrIS.fa  -t 20 -o flair_correct -f /home/apps/Anaquin/data/transcriptome/rnasequin_annotation_2.4.gtf`

the output : 

`index file /home/refs/sequins/chrIS.fa.fai not found, generating...
could not open index file /home/refs/sequins/chrIS.fa.fai for writing!
Step 1/5: Splitting junctions from GTF by chromosome: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████| 160/160 [00:00<00:00, 83489.50it/s]
Step 3/5: Preparing annotated junctions to use for correction: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 296.44it/s]
Step 4/5: Preparing reads for correction: 6943286it [00:12, 561951.70it/s]                                                                                                           | 0/1 [00:00<?, ?it/s]
Step 5/5: Correcting Splice Sites: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 23.48it/s]
Traceback (most recent call last):   0%|                                                                                                                                             | 0/1 [00:00<?, ?it/s]
File "/home/apps/flair/bin/ssCorrect.py", line 425, in <module>
main()
File "/home/apps/flair/bin/ssCorrect.py", line 407, in main
with open(os.path.join(tempDir, "%s_inconsistent.bed" % chrom),'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/scratch/melanie/clement/Guppy_v6.0.1/output_flair/provide_align_test0/tmp_b931e39b-b350-412b-a663-1fab43708625/chrIS_inconsistent.bed'
Correction command did not exit with success status`
