### ISSUE TITLE
correct error - ssCorrect.py

### ISSUE THREAD

**Issue by halfrt** [BrooksLabUCSC/flair#134]
Hello -

I'm trying to analyze some RNA nanopore data using flair - the align process goes well, but the correct process does not complete the 'preparing reads for correction step', but skips forward and generates the following error:  
File "/home/.conda/envs/salmon/bin/bin/ssCorrect.py", line 425, in <module>    
main()
File "/home/.conda/envs/salmon/bin/bin/ssCorrect.py", line 407, in main
with open(os.path.join(tempDir, "%s_inconsistent.bed" % chrom),'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/home/.conda/envs/salmon/bin/tmp_c3e3515a-6be1-4888-820f-e6db47030281/1_inconsistent.bed'

My input script contains the .bed file from the align process, the gtf and fa genome.

Any suggestions?  Using Centos 8.
Thanks for any help!

**Comment by mvheetve** [comment]
Hi,

have you looked in `/home/.conda/envs/salmon/bin/tmp_c3e3515a-6be1-4888-820f-e6db47030281/ ` and the bed files it contains? Would help if you shared some more information. I suspect the problem lies with the fact that flair can't find the temporary _inconsistent.bed file(s) to make the final all_inconsistent.bed file. Maybe they aren't there for some reason, maybe they are named differently, maybe the earth is flat after all...

Regards
Mattias

**Comment by halfrt** [comment]
Thanks for the reply - I'm pretty new to this stuff, so I'm not sure what type of information would help solve this problem.  When I search the folder mentioned in the thread, it doesn't contain any temporary_inconsistent.bed files.  It does have the 'chrX_known_juncs.bed'  'chrX_temp_reads.bed' files for all the chromosomes.  I'm not finding any option to direct where fliar writes and reads the inconsistent.bed files - I would think it would be the same directory it uses for the other files?

**Comment by mvheetve** [comment]
Hi again,

could you show the full command you've used and maybe the first few lines of your genome sequence and annotation file + first few lines of the bed file from the align step?

**Comment by halfrt** [comment]
See below:

Command:
python flair.py correct -t 20 -q /home/flairdata/org_control.bed -f /home/flair/gencode.v35.annotation.gtf -g /home/flair/GCA_000001405.15_GRCh38_no_alt_analysis_set.fna -o /home/flairdata/human/correct/org_control

Annotation file: gencode.v35.annotation.gtf
##description: evidence-based annotation of the human genome (GRCh38), version 35 (Ensembl 101)
##provider: GENCODE
##contact: gencode-help@ebi.ac.uk
##format: gtf
##date: 2020-06-03
chr1    HAVANA  gene    11869   14409   .       +       .       gene_id "ENSG00000223972.5"; gene_type "transcribed_unproc$
chr1    HAVANA  transcript      11869   14409   .       +       .       gene_id "ENSG00000223972.5"; transcript_id "ENST00$

Genome file: GCA_000001405.15_GRCh38_no_alt_analysis_set.fna
>chr1  AC:CM000663.2  gi:568336023  LN:248956422  rl:Chromosome  M5:6aef897c3d6ff0c78aff06ac189178dd  AS:GRCh38
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN

Bed file: org_control.bed
chr1    14356   14696   2972de20-d299-4a77-ab94-00e470b5bf79;0  6       +       14356   14696   99,99,99      $
chr1    14399   24894   45ee276a-0af6-4848-be90-6380a95734ba;0  1       -       14399   24894   217,95,2      $

**Comment by mvheetve** [comment]
No, most likely not all steps have been executed. 

Also, have you checked out issue #26? I think this will help you out. Try to check out previous issues before posting a new one. Often you'll find people have had similar issues.

Mattias
