### ISSUE TITLE
new release regarding issue #116

### ISSUE THREAD

**Issue by mvheetve** [BrooksLabUCSC/flair#135]
Hi,

would it be possible to tag a new release including the fix mentioned in #116?

Regards
Mattias

Hi,

Please update to the newest commit and try running predictProductivity again. I have now accounted for gene names formatted `NC_*`. Thanks for your patience.

@ashokpatowary I would rerun with the original file, not the one where you replaced underscores with slashes.

-Alison

_Originally posted by @belgravia in https://github.com/BrooksLabUCSC/flair/issues/116#issuecomment-636217459_

**Comment by Jeltje** [comment]
You are correct, that code was available in the master branch but not as a release.
We have just released Flair v1.6.0
