### ISSUE TITLE
short read correction

### ISSUE THREAD

**Issue by charreca** [BrooksLabUCSC/flair#136]
Hi Flair community!
I would like to know if short read correction is based on junctions identified in short reads or donor sites/acceptor sites taken into consideration separetly whatever the junction  in which they are involved in.  When I take a look at output files it seems that the second way of correction is applied. If so, is there an option in the correction step to only considered the junction without spliting donor and acceptor sites identified in short read data?
Best 
Caroline

**Comment by belgravia** [comment]
Hi Caroline,

Yes, the current way the correction works is the latter -- a junction can be corrected to short-read supported donor/acceptor sites that aren't supported by a single junction read. 

I will be working on adding the functionality you're suggesting to the correct module. I will update this post when I have done this. Thanks for your patience.

-Alison

**Comment by charreca** [comment]
Hi Alison, 

Is it possible to know when this functionality will be available? We would like to try this way of correction before submitting our work. However if it is going to take a lot of time, we will use the first version of correction.
I hope I am not putting any pressure on you. It is just for information :)

Best, 

Caroline

**Comment by Jeltje** [comment]
Is this still a relevant request? Alison is no longer an active developer on the project and this is not a trivial addition to the code.
