### ISSUE TITLE
isoforms quantification

### ISSUE THREAD

**Issue by Matthijnssenslab** [BrooksLabUCSC/flair#137]
Dear, I have both the short-reads and long reads for the same sample, could I map the short-reads to the isoform fasta file produced by flair collapse to quantify the isoforms or use short-reads with the flair quantify module? Thanks

**Comment by belgravia** [comment]
Hi,

I wouldn't use the flair quantify module to quantify short reads. Instead, you could use your favorite short-read quantification method, say kallisto or salmon, with the long-read isoform fasta file from flair-collapse.

-Alison
