### ISSUE TITLE
Flair-collapse no output

### ISSUE THREAD

**Issue by sunqiangzai** [BrooksLabUCSC/flair#139]
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
[M::mm_idx_gen::67.455*1.83] collected minimizers
[M::mm_idx_gen::71.657*3.21] sorted minimizers
[M::main::71.982*3.20] loaded/built the index for 1462646 target sequence(s)
[M::mm_mapopt_update::74.229*3.14] mid_occ = 735
[M::mm_idx_stat] kmer size: 15; skip: 10; is_hpc: 0; #seq: 1462646
[M::mm_idx_stat::75.288*3.11] distinct minimizers: 58984185 (36.99% are singletons); average occurrences: 9.070; average spacing: 5.377
[M::worker_pipeline::235.733*20.34] mapped 452367 sequences
[M::worker_pipeline::330.544*25.93] mapped 455193 sequences
[M::worker_pipeline::430.363*29.16] mapped 460779 sequences
[M::worker_pipeline::533.260*31.24] mapped 452690 sequences
[M::worker_pipeline::633.011*32.60] mapped 448494 sequences
[M::worker_pipeline::741.954*33.26] mapped 447114 sequences
[M::worker_pipeline::853.773*33.53] mapped 447965 sequences
[M::worker_pipeline::952.467*34.20] mapped 449048 sequences
....
[M::main] Version: 2.17-r941
[M::main] CMD: minimap2 -a -t 40 -N 4 tissue.flair.collapsed.firstpass.fa all_merged.fq.gz
[M::main] Real time: 104884.968 sec; CPU: 3986130.078 sec; Peak RSS: 28.019 GB
Filtering isoforms
Renaming isoforms
Aligning reads to first-pass isoform reference

![
![Snipaste_2020-11-12_15-58-11](https://user-images.githubusercontent.com/22913048/98911647-e60ffd00-24ff-11eb-8d3e-c4ddd21c2411.png)

Only first-pass files are produced

**Comment by sunqiangzai** [comment]
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Renaming isoforms
Aligning reads to first-pass isoform reference
Failed at counting step for isoform read support

**Comment by halfrt** [comment]
This may be related to my issue #140 as well.  Do you have a large tmp folder containing a &&&.firstpass.sam file in your root/tmp directory?  I'm finding that this is related to the size of the initial fastq file I run through this step.  My root directory runs out of space for the tmp files and terminates.  None of my smaller fastq files cause this issue.  Is your root at 100%?

**Comment by zoucheng123** [comment]
> 
> 
> Annotated ends extracted from GTF
> Read data extracted
> Single-exon genes grouped, collapsing
> Renaming isoforms
> Aligning reads to first-pass isoform reference
> Failed at counting step for isoform read support

I encounter this issue (only first-pass files) too, have you fixed it now? Thanks!

**Comment by Jeltje** [comment]
Thanks everyone, 

This issue happened when one of flair's submodules exited with an error that wasn't captured by the main program.
Flair v1.6.0 has much better error messaging.
Please try your runs with the latest version and reopen this ticket (or create a new one) if you encounter more problems.
