### ISSUE TITLE
Output from diff_iso_usage

### ISSUE THREAD

**Issue by FitzsimmonsCM** [BrooksLabUCSC/flair#14]
Hello, 

I had a question about the output from the diff_iso_usage.py script. I don't quite understand the information contained in the alternative isoforms columns, as well as the last few columns at the end, and was wondering if you could explain it a bit more. 

Thanks!

[Nanopore1_diffEx.txt.zip](https://github.com/BrooksLabUCSC/flair/files/3052108/Nanopore1_diffEx.txt.zip)

**Comment by belgravia** [comment]
I will describe an example, hope it helps to clarify, let me know how else to help. It also looks like you added 4 extra columns at the end so I will ignore those.

Each isoform is tested to see if it is differentially expressed between your two samples. According to diff_iso output you sent, the `ENSG00000167658.15` gene has three isoforms. To test if the `56b506c1-1829-4036-af73-a725d1ab2d73` isoform is differentially used, a Fisher's test is done comparing the expression of that isoform in your two samples relative to the expression of all the other isoforms for `ENSG00000167658.15` (all other isoforms = alternative isoforms). FLAIR quantified 710 counts of `56b506c1-1829-4036-af73-a725d1ab2d73` in sample 1 and 1,523 counts in sample 2 (numbers are from the `*isoform_count` columns). FLAIR also quantified 634 for all other isoforms for that gene in sample 1 and 542 in sample 2 (numbers are from the `*alternative_isoforms_for_gene_count` column). So `56b506c1-1829-4036-af73-a725d1ab2d73` appears to be used much more in sample 1 relative to sample 2. 

-Alison

**Comment by FitzsimmonsCM** [comment]
Hi Alison, 
Your example helps. I was getting thrown off by the "alternative isoforms" column, but now I understand the math is comparing isoform = A and isoform != A between the samples. Thanks for clarifying! 
-Christina

**Comment by Akanksha2511** [comment]
Hi, sorry but I am having trouble understanding the conclusion you draw above. Shouldn't it be "so 56b506c1-1829-4036-af73-a725d1ab2d73 appears to be used much more in **sample 2** relative to **sample 1**."

**Comment by FitzsimmonsCM** [comment]
In the example above, the transcript is 52% of sample 1 and 74% of sample 2. The paragraph from Alison leads to the same conclusion, but gets flipped around at the end. So I think it was just a typo.

**Comment by Akanksha2511** [comment]
Yeah, sorry I got confused there. Thanks for your quick reply.
