### ISSUE TITLE
File or directory missing during initial step

### ISSUE THREAD

**Issue by callumparr** [BrooksLabUCSC/flair#145]
If I add the `--nvrna `flag I get an error:

```
python flair.py align -g Mus_musculus.GRCm38.dna.primary_assembly.fa -r test.fastq --nvrna --psl -t 12
[ERROR] failed to open file '12': No such file or directory
```

If I omit this `--nvrna ` flag, `align` runs ok.

I am unsure what is missing as all files exist and I event moved into the flair directory just in case this caused issue. I had my fastq files with U to T substitution so also converted it back in case there is some detection of uracils as a sanity check for DRS data. This did not work either. 

Unsure what to try next. 

I've doubled checked I have all python modules installed with `pip install` and I added `minimap2` to my `PATH`

**Comment by MustafaElshani** [comment]
Hi @callumparr 

I came across the same problem, I suspicions that `--nvrna ` arg as not being inserted in the correct place of `mm2_command` hence messing with minimap2 command so in flair.py I changes line 48 from `mm2_command[4:4] = ['-uf', '-k14']`  to `mm2_command[5:5] = ['-uf', '-k14']`

This worked well with the nvrna arg, hope this helps

**Comment by callumparr** [comment]
Is weird as I was using docker image because I was struggling to get an install working and that docker only has 1.4 release but then I just tried downloading the v1.5 source and it worked in the end regardless of the order.
