### ISSUE TITLE
Combined samples and then map or map samples separately?

### ISSUE THREAD

**Issue by callumparr** [BrooksLabUCSC/flair#146]
Is it expected to combine all the pass FASTQ files from all samples you have and then map with `flair.py align` or to map separately then combined the .psl files before the next step, `flair.py correct` ? 

I could not see a way to feed in multiple FASTQ for minimap2 that would also output separate SAM files for each sample. 

After I annotate splice sites I would like to use this for differential expression analysis so would need to go back to original samples and conditions again.

**Comment by Jeltje** [comment]
You should run them separately and combine them at the Flair quantify step.

Flair align allows input of multiple fastq files as a convenience, in case you have multiple files per sample. It has no way of keeping track of which reads came from which input file.

Hope this helps!
