### ISSUE TITLE
An error in correct step

### ISSUE THREAD

**Issue by cym0304** [BrooksLabUCSC/flair#15]
Hello，
I met an error in correct step. The error message is like this:

>   File "/path/flair-master/bin/ssCorrect.py", line 304, in <module>
>     main()
>   File "/path/flair-master/bin/ssCorrect.py", line 269, in main
>     outDict[chrom] = open("%s_temp_reads.bed" % chrom,'w')
> IOError: [Errno 24] Too many open files: 'NW_017860819.1_temp_reads.bed'
> Exception KeyError: KeyError(<weakref at 0x2b95b617ac00; to 'tqdm' at 0x2b95b61efd50>,) in <bound method tqdm.__del__ of Step 4/5: Preparing reads for correction: 11379698it [00:24, 154307.47it/s]> ignored
> usage: script.py psl ref.gtf/ref.gp isos_matched.psl
> rm: cannot remove ‘test.cDNA_all_corrected.unnamed.psl’: No such file or directory

I check the ssCorrect.py and I think the error may be caused by my reference. This reference is not assembled very well. It has more than 9000 scaffolds and does not have the chromosomes. Maybe the script can't handle so many scaffolds. But the point is how can I solve this problem? I can't find other version of the reference genome. Could you give me some suggestions about this?

**Comment by csoulette** [comment]
Hi Cym0304,

Have you tried setting your ulimit to more than the number of scaffolds in your annotations? I'm not sure what operating system you are on, but if you are on linux of unix, you should be able to `ulimit -n 10000` without a problem.

Thanks

Best,
CMS

**Comment by knewl** [comment]
Hi,

I'm also using a very fragmented genome assembly had the same error in one of my samples:

> $ python flair.py correct -f ../../reference/GCF_000004195.3_Xenopus_tropicalis_v9.1_genomic.gtf -c ../../reference/chrom_lengths_edited.txt -q ../flair_alignments/BC11.flair.bed -o BC11.flair.correct -g ../../reference/GCF_000004195.3_Xenopus_tropicalis_v9.1_genomic.fna
> Traceback (most recent call last):
>   File "/flair/bin/ssCorrect.py", line 370, in <module>██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1623/1623 [00:02<00:00, 615.22it/s]
>     main()
>   File "/flair/bin/ssCorrect.py", line 327, in main
>     outDict[chrom] = open(os.path.join(tempDir,"%s_temp_reads.bed" % chrom),'w')
> OSError: [Errno 24] Too many open files: '../flair_correct/tmp_6eebebae-f0ea-46a7-9167-d9e8c86a8fcd/NW_016688703.1_temp_reads.bed'
> Correction command did not exit with success status

I'm using linux, but don't have permission to change ulimit (although it seems to say it's unlimited?).

> $ ulimit -n 10000
> -bash: ulimit: open files: cannot modify limit: Operation not permitted
> $ ulimit
> unlimited
> 

Is there any way of limiting the number of simultaneously open files?

Thanks again,

Katherine

**Comment by csoulette** [comment]
Hey Katherine,

Apologies for getting to this so late. 

There is a workaround for you that is not part of the main flair pipeline, but it requires splitting your reads file into individual chromosome files. Depending on the amount of data, having a tool like parallel could help reduce the runtime of this workaround. The following attached bash script should do the trick. 

After running `flair.py correct [params]`, you should obtain a directory with bed files containing junction information for each chromosome. Just input the name of that temporary directory (first line of script), the path to your bed12 reads (second line of script), and the path to ssPrep.py in the flair bin (line 10). **Warning, there are 3 `rm` statements in the bash script to get rid of intermediate files. Comment them out or just make sure nothing else will get deleted when those statements get executed. 

```
juncDir="./tmp_dbbed9d5-69c2-4c0a-8523-dbd47ad8f6fc/"
bed12Reads="../flair.minimap2.aligned.bed12"

awk -F"\t" '{print>$1"_temp_reads.bed"}' $bed12Reads

for readFile in `ls ./*_temp_reads.bed`
do
    root=`echo $readFile | sed 's/\.\///' | sed 's/_temp_reads.bed//'`
    juncFile=$juncDir$root"_known_juncs.bed"
    `python ~/bin/flair/bin/ssPrep.py -i $readFile -j $juncFile -o $root -f hg19.fixed.fa --workingDir ./`

done

cat *_corrected.bed > flair.all.corrected.bed
cat *_inconsistent.bed > flar.all.inconsistend.bed
rm *_corrected.bed
rm *_inconsistent.bed
rm *_temp_reads.bed

```

-CMS

**Comment by leafiezyt** [comment]
Hi,

I was running flair correct step today and had the following error message.
***********************************************************************************
File "/mnt/tools/flair/bin/ssCorrect.py", line 410, in <module>
    main()
  File "/mnt/tools/flair/bin/ssCorrect.py", line 392, in main
    with open(os.path.join(tempDir, "%s_inconsistent.bed" % chrom),'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/RNAseq_July2019/Flair_MB231/flair/tmp_90f77561-e57b-4ecd-abb6-f7742d68c057/chr1_inconsistent.bed'
Correction command did not exit with success status
***********************************************************************************************
I checked the tmp folder and there's no bed files generated in the format of *_inconsistent.bed. For each chromosomes, two bed files were generated. For example, 
chrY_temp_reads.bed
chrY_known_juncs.bed

I wonder if you could help me here.

Thanks very much.
Yeting

**Comment by csoulette** [comment]
Hi leaiezyt,

Check out the discussion on issues related to yours here  #26 .

Thanks~

-CMS

**Comment by knewl** [comment]
Hi CMS,

Thanks for getting back to me. I'll give the workaround a go and get back to you with any problems.

Cheers,

Katherine
