### ISSUE TITLE
Rpy2 vs numpy: compatibility issues

### ISSUE THREAD

**Issue by leticia-castro** [BrooksLabUCSC/flair#151]
Hi, 

I seem to be having issues with `rpy2` and `numpy` compatibility when using the flair python environment. The error for `diffExp` was rectified when I upgraded `numpy` to 1.19.5. Unfortunately, when I went on to run `diffSplice`, the same issue arose. So, I reverted to the original versions specified in the environment `.yaml` file, but `diffSplice` still failed with the same `ValueError: Buffer for this type not yet supported` error. I also tried `rpy2 3.1*` as recommended below, to no avail. 

Thanks,
Leticia

Ozge - Thanks for attaching some of your counts matrix. It looks fine to me. Thanks for also trying it with both versions of flair in the conda environment. 
From googling the ValueError, it appears that this may be an issue with certain numpy versions that are incompatible with rpy2. I was able to reproduce the ValueError when my numpy version was 1.18.5. When I changed to version 1.9 (`conda install numpy=1.9`) which is the version specified in the conda environment .yaml, I was able to get the diffExp module working. I also had to make sure that the numpy version actually got switched to 1.9 using `export PYTHONNOUSERSITE=True`. There should be DGE, DIE, and DIU results outputs. Let me know if this solves your issue. An alternative solution may be to upgrade rpy2 to 3.1*. 

@chalybes - it may be helpful for me to see your counts matrix. Your errors seem to be related to problems with input.

_Originally posted by @belgravia in https://github.com/BrooksLabUCSC/flair/issues/100#issuecomment-646262951_

**Comment by MustafaElshani** [comment]
This issue persists even with the latest conda .yaml files there are many incompatibles with packages and conflicts especially with pandas, numpy and rpy2. `diffExp` completes without error however only below files are the output 
```
dge_stderr.txt  
filtered_gene_counts_ds2.tsv  
filtered_iso_counts_drim.tsv  
filtered_iso_counts_ds2.tsv  
formula_matrix.tsv
```
Has anyone else got the diffExp working with all of the expected output files ?

**Comment by Jeltje** [comment]
Please try running Flair from its docker container

`docker pull brookslab/flair:latest`

You can then run flair commands like so
``docker run -v `pwd`:/mydata -w /mydata brookslab/flair:latest flair diffExp (...)``

(note that you no longer need the .py extension after flair)

If this solves your problem to your satisfaction, please close this ticket.

We are working to make Flair conda installable but this might take a while.

**Comment by Jeltje** [comment]
[Flair is now conda installable.](https://flair.readthedocs.io/en/latest/index.html)
