### ISSUE TITLE
diffExp

### ISSUE THREAD

**Issue by aheravi** [BrooksLabUCSC/flair#153]
Hello,
Could you please comment on my error in diffExp here:
```
python $flair/flair.py diffExp -q counts_matrix.tsv -o ./diffExp/
Traceback (most recent call last):
  File "/flair-1.5/bin/deFLAIR.py", line 348, in <module>
    main()
  File "/flair-1.5/bin/deFLAIR.py", line 258, in main
    groups  = [x.split("_")[1] for x in header]
IndexError: list index out of range
```

**Comment by Jeltje** [comment]
Thanks for reporting.

Diffexp expects your column headers to contain information on sample ID, group, and batch, separated by `_`, for instance `CF7sample1_conditionA_batch1`

We have updated Flair's error messaging to be more helpful.
