### ISSUE TITLE
predictProductivity.py error

### ISSUE THREAD

**Issue by zoucheng123** [BrooksLabUCSC/flair#155]
**Hi, I got an error stated as below when I ran predictProductivity.py.** 
Traceback (most recent call last):
  File "/home/zhuofeng/zoucheng/software/flair-master/bin/predictProductivity.py", line 372, in <module>
    main()
  File "/home/zhuofeng/zoucheng/software/flair-master/bin/predictProductivity.py", line 338, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "/home/zhuofeng/zoucheng/software/flair-master/bin/predictProductivity.py", line 253, in predict
    isoDict[read].strand = intersection[5]
KeyError: 'e6d9617c-e5d1-4432-abc0-2f292c4278bb_1:123000'

**And here is the command I used:** 
command_dir=/home/zhuofeng/software/flair-master/bin
gtf=/home/human_genome/ensembl/Homo_sapiens.GRCh38.98.gtf
fasta=/home/human_genome/ensembl/Homo_sapiens.GRCh38.dna.primary_assembly.fa
python ${command_dir}/predictProductivity.py -i ../flair_collapse_no_Y34.isoforms.bed -g ${gtf} -f ${fasta} --longestORF > productivity.bed

I've tried to select some lines with known transcriptID/geneID ("ENST00000374618_ENSG00000189180") from flair_collapse_no_Y34.isoforms.bed and ran predictProductivity.py again, but it reported the same error.
Could you please help me with this problem？Thank you in advance.

**Comment by amnrojas** [comment]
Hi Zoucheng, I have the same problem. Where you able to solve it?

**Comment by CSdady** [comment]
Hi, have you had a luck to figure out this error?
I didn't get this error an half year ago but I started to have the error recently.
Only difference between now and then is that I up-to-dated python and required packages.

**Comment by Jeltje** [comment]
Hey everyone. I think I found the problem. Please either git clone the latest master branch or replace your predictProductivity.py with the latest version.

The issue was due to bedtools versioning. We developed predictProductivity.py using v25 and my change now makes it run in v30. If you have any more problems, please let us know the bedtools version you are using.

Thanks!

**Comment by Jeltje** [comment]
Pleae reopen this ticket if you still have issues.
