### ISSUE TITLE
losing crucial reads due to correct step

### ISSUE THREAD

**Issue by mvheetve** [BrooksLabUCSC/flair#156]
Hi flair crew, 

while analyzing cDNA from a sample with a known heterozygous splice variant I noticed i could not find the isoform produced by the variant (skip of the first part of an exon, confirmed with Sanger and Illumina) in the count files. Looking at the bam file (produced with flair align) there are clearly reads with the aforementioned skip. Closer examination of the all_corrected and all_inconsistent bed files showed that the reads I'm most interested in for this sample do not make the cut and end up in the inconsistent bedfile. 

Can you advise on how to deal with this situation? I'm currently trying the following to see if I can solve the problem:
1. concatenate all_corrected and all_inconsistent and run flair collapse => still running
2. bamTobed to create a bed file of all reads in the bam file and then run flair collapse => following error occured:
```
Annotated ends extracted from GTF
Traceback (most recent call last):
  File "/kyukon/home/apps/CO7/skylake-ib/software/FLAIR/1.5.1-20200630-foss-2019b-Python-3.7.4/bin/collapse_isoforms_precise.py", line 616, in <module>
    junctions, junccoord = get_junctions_bed12(line)
  File "/kyukon/home/apps/CO7/skylake-ib/software/FLAIR/1.5.1-20200630-foss-2019b-Python-3.7.4/bin/collapse_isoforms_precise.py", line 76, in get_junctions_bed12
    return junctions, (starts[0]+sizes[0], starts[-1])
IndexError: list index out of range
```

Regards
Mattias

**Comment by Jeltje** [comment]
Hello Mattias, 

Do you still see this issue with the latest version of the code? Please note that you can now use conda to install flair with all its dependencies:
`conda create -n flair -c conda-forge -c bioconda flair`

If you still see this behavior I would love to have a closer look.

**Comment by mvheetve** [comment]
Hi Jeltje,

thank you very much for you response and taking the time to have a look at this issue. I have to admit I haven't worked on the project where we used flair for some time. I'm busy with other work at the moment, but I'd be happy to rerun when I do see some time and report back on the splice variant. If the issue still persists I would be happy to share some data.

If I do not reply in a reasonable amount of time (let's say somewhere in November), you are welcome to remind me of this.
