### ISSUE TITLE
error reading junctions

### ISSUE THREAD

**Issue by noncodo** [BrooksLabUCSC/flair#16]
Full command: 
`python /work/flair/flair.py align -t 16 -c /biodata/genome_indexes/hg38noAlt.fa.fai -p -v1.3 -r ../file.fastq.gz -g /biodata/genome_indexes/hg38noAlt.fa`

Maps, converts, sorts, then fails: 

> Converting sam output to bed
> [bam_sort_core] merging from 16 files and 16 in-memory blocks...
> Traceback (most recent call last):
>   File "/work/flair/bin/bam2Bed12.py", line 144, in <module>
>     main();
>   File "/work/flair/bin/bam2Bed12.py", line 124, in main
>     for num, readData in enumerate(sObj.readJuncs(),0):
>   File "/work/flair/bin/samJuncs.py", line 174, in readJuncs
>     chromosome = read.reference_name
> AttributeError: 'pysam.calignmentfile.AlignedSegment' object has no attribute 'reference_name'

**Comment by noncodo** [comment]
minimap2 2.16-r922

**Comment by belgravia** [comment]
What version of pysam are you using? We've seen this issue happen before with older versions (e.g. 0.8.2.1) and it gets fixed by using a newer version. The version we use is 0.15.1. 

-Alison

**Comment by Psy-Fer** [comment]
pip freeze shows us we are using pysam==0.15.2

Should we roll back to  0.15.1?

**Comment by noncodo** [comment]
Confirming, pysam==0.8.2.1 was used.
