### ISSUE TITLE
Flair collapse not finishing

### ISSUE THREAD

**Issue by jchang97** [BrooksLabUCSC/flair#160]
Hi there,

I have been running multiple fastq's together in the Flair collapse step, but the run keeps going for a while and would not finish - I've been running for 8 days now and I'm wondering whether you would have any suggestions for this? There are no obvious errors from the error files. 

I am attaching the error + log files here.
[24574191.log](https://github.com/BrooksLabUCSC/flair/files/6201346/24574191.log)
[tmpjgnw3s3h.firstpass.txt](https://github.com/BrooksLabUCSC/flair/files/6201356/tmpjgnw3s3h.firstpass.txt)

Thank you so much in advance!

**Comment by aline2593** [comment]
Did you manage to solve your issue? I am having a similar one.. 
#164 
Thanks

**Comment by Jeltje** [comment]
[Today's commit](https://github.com/BrooksLabUCSC/flair/commit/04c42bd96c91c926d9ab20faea292709bd5c5e04)  no longer outputs a gigantic SAM file. This should fix the problem.

If not, please reopen this ticket.
