### ISSUE TITLE
No differential isoform usage output?

### ISSUE THREAD

**Issue by wigge206** [BrooksLabUCSC/flair#161]
Hi
I have run diffExp on a few datasets, including one uploaded by a user in a previous issue (https://github.com/BrooksLabUCSC/flair/issues/47#issuecomment-530761202). I only get output for differential isoform analysis (die) and differential gene expression analysis (dge). I have no errors while running or in dge_stderr.txt. 
What would be causing this?

**Comment by Jeltje** [comment]
Do you have the R package DRIMSeq installed?

It might be easier to run Flair from its docker container:

`docker pull brookslab/flair:latest`

You can then run flair commands like so
``docker run -v `pwd`:/mydata -w /mydata brookslab/flair:latest flair diffExp (...)``

(note that you no longer need the .py extension after flair)

If this solves your problem to your satisfaction, please close this ticket.

We are working to make Flair conda installable but this might take a while.

**Comment by Jeltje** [comment]
Flair is now conda installable:

`conda install -c conda-forge -c bioconda flair`

Please reopen this ticket if you still have problems.
