### ISSUE TITLE
too many single-exon transcripts

### ISSUE THREAD

**Issue by robinycfang** [BrooksLabUCSC/flair#162]
Hi,

I see FLAIR can generate many novel single exon transcripts (more than 50% in my data), and a lot of them are from intergenic regions. Actually, transcripts discovered from intergenic regions are all single-exon. Any thoughts on the existence of these single-exon transcripts? Are they for real or mostly likely due to algorithmic bias?

Thanks!

**Comment by brunaeus** [comment]
Hi,
I'm also facing the same issue. Many single-exon isoforms and most are intergenic. 

I have corrected alignments using the SJ.out.tab files from STAR and passed the GTF file. I'm using encode ChR38.v36, both genome and annotation. 

I don't know if it's related but I've also noticed that I am getting a long number string attached to the transcript ID as a name for the isoforms. 

Loving the workflow and would appreciate how to solve this issue.

**Comment by MartinezRuiz-Carlos** [comment]
Hi team, 
Just adding to the thread. I get the same, they are easy enough to filter out, but it seems like a big waste of resources and it is not clear to me this is normal behaviour. Is this expected and a matter of just filtering them post-hoc or is this signalling an issue with the data and/or the parameters used?
Many thanks!

**Comment by alexvnesta** [comment]
I just processed some nanopore reads and have a majority of my novel transcripts as single exons - This is unexpected. I am currently reviewing my alignment options. Maybe there is something I overlooked. Following in case anyone has a way to address this issue.

**Comment by alexvnesta** [comment]
I used filtered out low read count isoforms and used SQANTI filtering. Ended up eliminating almost all of the single exon transcripts. I am still investigating if this is an issue with FLAIR, alignment, or something else.

**Comment by Jeltje** [comment]
Flair was written for identifying different splice variants and isn't as well equipped for dealing with single exon genes.  You might try running with the latest version, we did make some improvements.
