### ISSUE TITLE
flair quantify --tpm option

### ISSUE THREAD

**Issue by callumparr** [BrooksLabUCSC/flair#163]
If I understand correctly, flair is designed to accurately assign both annotated and novel splice junctions and can also be used to quantify transcript abundance and differential usage using long-read data.

I notice there is an option to output TPM but I am confused as from understanding TPM is used to normalize for read depth but also transcript length. In this case we don't need to worry about this as can assume 1 read ~ 1 original RNA molecule that makes up the expression abundance of a gene isoform. Is this a modified TPM that only normalizes for sequencing depth?

**Comment by XNXQC** [comment]
the script bin/counts_to_tpm.py has a optional parameter [iso.sizes].if no isoform size file is provided, no length normalization will be done (just reads per million).
