### ISSUE TITLE
FLAIR COLLAPSE

### ISSUE THREAD

**Issue by aline2593** [BrooksLabUCSC/flair#164]
#160 
I am having a similar problem. I am running the FLAIR collapse on 41 samples (direct RNA seq) but after two day run the analysis give me FAILED to write result error after the minimap2 alignment step.
I check for memory and time li its but this seems not to be the problems. I was wondering if the problem could be collapsing all samples reads in one single file when running the analysis after the -r option.
That happens to some of you as well? should i run collapse independently for each sample?

Thanks a lot

**Comment by Jeltje** [comment]
Today's commit should solve this problem, see #160
