### ISSUE TITLE
Unable to handle soft-masked reference genome

### ISSUE THREAD

**Issue by ctl43** [BrooksLabUCSC/flair#168]
Hi Alison, thanks for creating this wonderful package for us. However, I encountered a problem that when a transcript is negatively stranded, the extracted transcript is not right occasionally.

Later, I found that it is because the `revcomp` function in psl_to_sequence.py can only handle uppercased sequences. If the corresponding regions contain soft-masked (lowercased) sequences, the `revcomp` function will not be able to fully reverse complement the sequences.

Adding `pulledseq=pulledseq.upper()` after using `get_sequence` 
or
letting `revcomp` to handle lowercased sequences will fix the problem.

I think this may need an urgent fix because quite a number of reference sequences are soft-masked, the failure of this step filtered out some true transcripts with soft-masked sequences at the `collapse` step. As the pulled sequence is wrong, reads cannot be aligned to a right sequence and are falsely assigned to another similar one. Sequenquently, the true transcript will be discarded because of lacking enough supporting reads.

**Comment by lvclark** [comment]
This is related to #187.  It's a problem for me as well!  I converted my genome to all uppercase but now am having other issues.

**Comment by Jeltje** [comment]
Thanks!
revcomp() has been added to `psl_to_sequence.py` and `mark_productivity.py`

**Comment by Jeltje** [comment]
Thanks!
This was fixed in a commit in October 2021 and is part of release 1.5.1 (which is a pre-release, we hope to do another one within a few weeks).
Please reopen this ticket if you have any more issues
