### ISSUE TITLE
python version confusion

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#169]
It appears that FLAIR works on either python2 or python3, however, the documentation isn't clear on this.  Many users assume that it does not work on python3 if it is explicitly stated.

however, kerneltree doesn't install on python3.9 and the site says it is no longer maintained
https://github.com/biocore-ntnu/kerneltree

I would suggest just giving up on python2, it is obsolete.

**Comment by diekhans** [comment]
a requirements.txt file would be really useful

**Comment by herber4** [comment]
agreed. have you had any success running flair, if so, which Conda version are you using?

**Comment by diekhans** [comment]
I ran it previously with py 2.7, but that was a couple of years ago.

**Comment by Jeltje** [comment]
We have removed support for py 2.7. Please run Flair using python3 or, even easier:

`conda install -c conda-forge -c bioconda flair`
