### ISSUE TITLE
Missing chromosomes in annotation cause collapse to fail

### ISSUE THREAD

**Issue by noncodo** [BrooksLabUCSC/flair#17]
After successfully correcting reads using gencode and a custom, unique splice junction file, FLAIR collapse fails, presumably because it can't fin the decoy chromosomes in the reference chromosome library.  

Can you recommend a solution that doesn't involve stripping out non-Gencode chromosomes from the mappings/annotations/corrected reads? 

Error log:
> Collapsing isoforms
Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Traceback (most recent call last):
  File "/home/jamfer/work/flair/bin/collapse_isoforms_precise.py", line 545, in <module>
    res = p.map(run_se_collapse, chrom_names)
  File "/home/jamfer/work/python-2714/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/jamfer/work/python-2714/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'chr1_KI270706v1_random'

Command used: 
`python flair.py collapse -t 24 -f gencode.v30.annotation.gtf -e comprehensive -r reads.fastq -q flair_all_corrected.psl -g hg38noAlt.fa`

**Comment by belgravia** [comment]
Thanks for your patience! I pushed a fix to the collapse module that should deal with chromosomes in the reads psl that do not appear the the annotation file. Please try rerunning flair-collapse. Let me know how it goes!
-Alison

**Comment by noncodo** [comment]
Lovely! Will give it a spin next iteration. Removing the "random" or "alt" contigs from the psl worked.
