### ISSUE TITLE
DiffExp - problems with rpy2 and R

### ISSUE THREAD

**Issue by LilyWC** [BrooksLabUCSC/flair#171]
Hello,
I tried using DiffExp after installing all the required modules but encountered this problem:
**AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'**

The rpy2 that I used was 3.4.5 so I reinstalled 2.9.4, but it resulted in other errors. Installing older versions of numpy and pandas also did not help.
Can people who had no problem with DiffExp please let me know the version of each module they used?

In addition, the error message was followed by the following:
**R[write to console]:  library '/usr/share/R/library' contains no packages**

Does this mean that problem was related to the lack of access to R modules? 
I downloaded the modules to my personal home directory, so it is different from the one listed. If that is the problem, how can I solve it?

I would really appreciate having some help with this. Thank you!

**Comment by Jeltje** [comment]
Hi,

Yes, it looks like you don't have the correct R packages installed.

It might be easier to run Flair from its docker container:

`docker pull brookslab/flair:latest`

You can then run flair commands like so
``docker run -v `pwd`:/mydata -w /mydata brookslab/flair:latest flair diffExp (...)``

(note that you no longer need the .py extension after flair)

If this solves your problem to your satisfaction, please close this ticket.

We are working to make Flair conda installable but this might take a while.

**Comment by Jeltje** [comment]
Flair is now conda installable:

`conda install -c conda-forge -c bioconda flair`
