### ISSUE TITLE
.yaml file does not solve

### ISSUE THREAD

**Issue by pgupta3005** [BrooksLabUCSC/flair#176]
The yaml file provided does not solve when setting up a conda environment. I downloaded the requirements individually to proceed instead. Can you check what may have caused this? Thanks.

**Comment by herber4** [comment]
I am also having this issue. has anything been done to help resolve this issue yet?

**Comment by kudasonya** [comment]
Hello, I am not sure if people are still having this issue but removing pip from dependencies (kerneltree can be installed via the bioconda channel) seems to have solved it for me.

**Comment by Jeltje** [comment]
We have made flair conda and pip installable, which omits the need for using the .yaml file.

Please try
`conda install -c conda-forge -c bioconda flair`
