### ISSUE TITLE
diffsplice not producing the p-value with --test

### ISSUE THREAD

**Issue by dar19** [BrooksLabUCSC/flair#177]
Hi Thank you in advance:
I am running the step of "diffsplice" with --test option, but I am not able to get the p-values (or corrected p-values as shown in supplementary file) for the two conditions each with three replicates.
My command:
python3 ./flair/flair.py diffSplice \
	--threads 32 \
	--isoforms results/concated_files/collapse/collapse.isoforms.bed \
	--counts_matrix results/concated_files/quantify/quantify.tpm.tsv \
	--test \
	--batch \
	--conditionA sample1_control_batch1 \
	--conditionB sample4_treatment_batch1  \
	--output diffSplice

It only produces the file with below output:
feature_id	coordinate	sample1_control_batch1	sample2_control_batch2	sample3_control_batch3	sample4_treatment_batch1	sample5_treatment_batch2	sample6_treatment_batch3	isoform_ids
inclusion_1:1091990	1:1091990-1091609_1:1091990-1091565	10.279994937102494	9.099837962218686	7.083788466742321	14.763867216832844	5.2825329745613026	6.979623686609313	6d122257-0335-4785-82a2-b8edd3e47fc9
exclusion_1:1091990	1:1091990-1091609_1:1091990-1091565	4.497497784982341	6.066558641479124	8.500546160090785	5.600087565005562	6.603166218201627	12.563322635896764	6ae7d9c0-7c09-4d0d-80ea-4506c58db5be,ENST00000421241

However I am getting an stderrfile too (attached below):
-------------------------------------------------------------------------------------------------------------
/home/darsa/.pyenv/versions/3.7.6/lib/python3.7/site-packages/rpy2/robjects/vectors.py:980: UserWarning: R object inheriting from "POSIXct" but without attribute "tzone".
  warnings.warn('R object inheriting from "POSIXct" but without '
Traceback (most recent call last):
  File "/home/darsa/workspace/stress/analysis/isoform_FLAIR/flair/bin/runDS.py", line 197, in <module>
    main()
  File "/home/darsa/workspace/stress/analysis/isoform_FLAIR/flair/bin/runDS.py", line 156, in main
    samples      = pandas2ri.py2ri(formulaDF)
AttributeError: module 'rpy2.robjects.pandas2ri' has no attribute 'py2ri'
R[write to console]: Warning messages:
R[write to console]: 1: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages
R[write to console]: 2: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages
R[write to console]: 3: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages
R[write to console]: 4: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
R[write to console]:  library ‘/usr/share/R/library’ contains no package
R[write to console]: 5: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages
R[write to console]: 6: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages
R[write to console]: 7: 
R[write to console]: In (function (package, help, pos = 2, lib.loc = NULL, character.only = FALSE,  :
R[write to console]: 
 
R[write to console]:  library ‘/usr/share/R/library’ contains no packages
-------------------------------------------------------------------------------------------------------------

**Comment by Jeltje** [comment]
Thanks for reporting this problem.

The rpy package is a bit hard to work with, but I think we have solved this issue. Please try conda installing flair:
`conda install -c conda-forge -c bioconda flair`

or run it using the docker image `brookslab/flair:latest`

If this solves the problem, please close this ticket.
