### ISSUE TITLE
Another error when using collapse

### ISSUE THREAD

**Issue by ttmgr** [BrooksLabUCSC/flair#179]
After aligning and correcting flair.py collapse does not output any .gtf even when an annotation is provided. 

This keeps happening for every sample and it does not matter which annotation or reference genome is used during the analysis.

When I try to use psl_to_gtf.py to get the isoforms, i get way too many intergenic transfrags. Is there any other way to get the .gtf from the collapsing step?

**Comment by Jeltje** [comment]
The new release (1.6.1) is out
You can get it from github, or by running `pip install brookslab-flair`
There is also a docker image: `docker pull brookslab/flair:1.6.1`

If this release does not resolve your problem, please reopen this ticket. Thanks!
