### ISSUE TITLE
incorrect documentation on chromsize input

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#18]
The documentation claims that flair takes chromsizes in TSV format, which is not correct.  TSV files as similar to CSV files, in that the first row is a header of column names.
[https://en.wikipedia.org/wiki/Tab-separated_values](https://en.wikipedia.org/wiki/Tab-separated_values)

The code expects a simple tab separate file without a header, which is fine, as that is the format the ucsc browser provides.

**Comment by belgravia** [comment]
I removed the tsv specification from the README. The flair.py --help describes the chromsizes file as a "chromosome sizes tab-separated file" without mentioning tsv format.
-Alison
