### ISSUE TITLE
A false transcript cooordinate?

### ISSUE THREAD

**Issue by OlgaVT** [BrooksLabUCSC/flair#182]
Hi,

after flair collapse a transcript seems to have wrong coordinates. flair reports
2       FLAIR   transcript      65056416        65084522        .       +       .       gene_id "ENSG00000011523"; transcript_id "ENST00000377990";

But in the Ensembl 99 annotation that I used the coordinates are:
2	ensembl_havana	transcript	65056416	65087004	.	+	.	gene_id "ENSG00000011523"; gene_version "14"; transcript_id "ENST00000377990"; transcript_version "7";

The command lines I used:

python flair.py align -r my.fastq -g Homo_sapiens.GRCh38.dna.primary_assembly.fa
python  flair.py correct -q flair.aligned.bed -g Homo_sapiens.GRCh38.dna.primary_assembly.fa -f Homo_sapiens.GRCh38.99.gtf
python  flair.py  collapse -r my.fastq -g Homo_sapiens.GRCh38.dna.primary_assembly.fa  -q flair_all_corrected.bed -f Homo_sapiens.GRCh38.99.gtf

Do you know what might be wrong?

Thank you!

**Comment by Jeltje** [comment]
Hi OlgaVT, 

Apologies for the delay in replying. I believe the underlying code for this step has been updated since your question, would you mind trying your run with the current version? Please reopen this ticket if you have the same issue.
