### ISSUE TITLE
Error in ssCorrect.py when using Docker

### ISSUE THREAD

**Issue by Eduardo-vsouza** [BrooksLabUCSC/flair#186]
When running the FLAIR pipeline using the docker image, I encountered the error:

`  File "/usr/local/flair/bin/ssCorrect.py", line 368, in <module>
    main()
  File "/usr/local/flair/bin/ssCorrect.py", line 283, in main
    if gtf != None: juncs, chromosomes = gtfToSSBed(gtf)
  File "/usr/local/flair/bin/ssCorrect.py", line 173, in gtfToSSBed
    txn = cols[-1].split(";")[1].split()[-1].replace('"','')
`
Looking at local Flair folder (outside docker), this same line is commented in the ssCorrect.py script. Maybe this was left out during testing, but I cannot comment this line in the script being used by the docker image for obvious reasons. Any possible solutions? I'd like to run docker as I am facing some other problems when running the local version

**Comment by Jeltje** [comment]
Sorry about that, the docker image was really old.
You can get the most recent one from hub.docker.com using
`docker pull brookslab/flair:1.6.1`

If this does not solve your issue, please reopen this ticket.
