### ISSUE TITLE
Problem with revcomp() in psl_to_sequence.py

### ISSUE THREAD

**Issue by bmm514** [BrooksLabUCSC/flair#187]
Reverse complementing of the sequence is not working if the genome fasta is in lowercase. Would be useful to add in line to make sure sequence is in upper case. Could be add:
```
seq = seq.upper()
```
between line 42 and 43 in psl_to_sequence.py

**Comment by Jeltje** [comment]
Thanks!
This was fixed in a commit in October 2021 and is part of release 1.5.1 (which is a pre-release, we hope to do another one within a few weeks).
Please reopen this ticket if you have any more issues
