### ISSUE TITLE
No filter_isoforms_by_proportion_of_gene_expr.py

### ISSUE THREAD

**Issue by bmm514** [BrooksLabUCSC/flair#189]
Hello, I was trying to run FLAIR with a --support 0.1, as a percentage of expression but the script (bin/filter_isoforms_by_proportion_of_gene_expr.py) that is required for this section is not in the bin directory. Is this feature still supported by FLAIR?

```
/opt/anaconda3/bin/python3: can't open file '/path/to/flair/bin/filter_isoforms_by_proportion_of_gene_expr.py': [Errno 2] No such file or directory
```

**Comment by Jeltje** [comment]
I have readded the code, it should work if you check out the current version.
