### ISSUE TITLE
5' ends not well defined

### ISSUE THREAD

**Issue by lananh-ngn** [BrooksLabUCSC/flair#191]
Hello,
I ran flair collapse with and without providing CAGE peak data in the -p parameter. However, by providing the data, some isoforms are not detected while they should be there (evidence supported by Northern Blots). I tried to change the window size with no success. The isoforms are not detected before the first pass, therefore I was wondering which parameters can be changed to prevent this?

![image](https://user-images.githubusercontent.com/91305037/153389855-a510ba7c-fbe3-45ed-9818-295e6d5fdc04.png)
Please find attach a screenshot of the IGV with the CAGE peaks in orange, the annotation file obtained after collapse step but without providing the CAGE peaks in gray, and the annotation file obtained after collapse step but with the CAGE peaks in blue-green.

Thank you in advance!

**Comment by Jeltje** [comment]
I do not see introns in the gtf tracks, does that mean you used just startpos/enpdos for the isoforms? If these isoforms are truly single exon, they should all be merged, I think? I'm going to assume there are introns (correct me if I'm wrong).

By providing `-p` you're asking flair to only find isoforms that include the input TSS. 
This means that it starts by removing all reads that do not overlap  TSS, and then it builds the isoforms from that reduced set.

If you do not ask flair to filter the input reads, it will base its isoforms on all reads. This larger set is very likely to be more complex, with reads that cannot be merged into the same isoform. 

So what I think happens is that in the non CAGE run, reads are split up in more and different isoforms.

**Comment by lananh-ngn** [comment]
Hello,
Thank you a lot for your answer. For these particular transcripts there are no introns, and I did not only start and end positions. These isoforms have an alternative 5' end compared to the main loci _fbp1_ from the fission yeast _Schizosaccharomyces pombe_. Please find attached a screenshot providing the current annotation on the database with the coverage (in bigwig file) with the CAGE peaks clearly showing that there are four overlapping transcripts. However, on the previous screenshot, when I provide the CAGE peaks file, two of them are discarded. After some time spending on this problem, I found that they are not wiped out during the TSSs filtering stage but after, just before the first alignment (during the collapse stage?). Is there any way for flair to keep these since they have been proven existing using Northern blot? 
Thank you again for your help!!

**Comment by lananh-ngn** [comment]
Hello,
Thank you a lot for your answer. For these particular transcripts there are no introns, and I did not only start and end positions. These isoforms have an alternative 5' end compared to the main loci _fbp1_ from the fission yeast _Schizosaccharomyces pombe_. Please find attached a screenshot providing the current annotation on the database with the coverage (in bigwig file) with the CAGE peaks clearly showing that there are four overlapping transcripts. However, on the previous screenshot, when I provide the CAGE peaks file, two of them are discarded. After some time spending on this problem, I found that they are not wiped out during the TSSs filtering stage but after, just before the first alignment (during the collapse stage?). Is there any way for flair to keep these since they have been proven existing using Northern blot?
Thank you again for your help!! 

![image](https://user-images.githubusercontent.com/91305037/176083069-d18f27a9-29cf-4ac7-82c3-11e606a29962.png)
