### ISSUE TITLE
I tried every annotation in python flair.py align but gets this issue

### ISSUE THREAD

**Issue by seongwoohan** [BrooksLabUCSC/flair#192]
Hello, thanks for this wonderful software! I am curious if other people get this kind of error. Is this because of annotation issue? Happy for any advice!

<img width="1029" alt="Screen Shot 2022-02-15 at 11 45 48 AM" src="https://user-images.githubusercontent.com/19489536/154110695-d3265a60-62d2-4e32-a5a2-a9b3e95d0c10.png">

**Comment by Jeltje** [comment]
Hi, 

It looks like you are trying to align against a gtf file. The `-g` parameter in `flair.py align` is for the genome, flair expects a fasta file here. You can use an annotation in the `flair correct` step (option `-f`)

If you run `flair.py align --help` it will show all the options.
