### ISSUE TITLE
firstpass.q. sam is empty

### ISSUE THREAD

**Issue by AnastasiyaKazachenka** [BrooksLabUCSC/flair#194]
Hello, 
I am trying to run flair from conda environment. 
I have aligned reads "$f1".fastq.gz using minimap2 and samtools. Then I used flair/bin/bam2Bed12.py to convert obtained bam files to bed
Next I am using the next command
python $HOME/FLAIR/flair-master/flair.py collapse -s 1 -t 32 --mm2_args=-t32 -g $HOME/hg38.fa/hg38.fa -r "$f1".fastq.gz -q "$f1".bed -o "$f1" --keep_intermediate --temp_dir $HOME/TMP_DIR  -f $HOME/gencode.v37/gencode.v37.basic.annotation.gtf 2> $HOME/TMP_DIR/"$f2"_error_gencodeannot.txt

For some reason it does work for some of my files, but for another I get 0 output in the files
For files that dont work rporperly I do get output in *.firstpass.sam and *.firstpass.bed.... but nothing in the *.firstpass.q.sam, *.firstpass.q.counts 

*.firstpass.q.samtools_stderr file says next:
[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 2
[main_samview] truncated file.

I can not figure out why, because same type of command does work when I am using other datasets as an input

Maybe you could suggest me what I am doing wrong?

Kind regards,
Anastasiya

**Comment by callumparr** [comment]
Were you able to fix this issue? I noticed you closed the issue so presume it was resolved. I am having similar issues.

**Comment by AnastasiyaKazachenka** [comment]
> Were you able to fix this issue? I noticed you closed the issue so presume it was resolved. I am having similar issues.

Hey. Looks like the issue is with a memory assigned to minimap for index generation. It is default 4G (-I 4G). If this default memory isn't enough then minimap split the index and cannot align sam file properly within flair package at least

the way I fixed it was increasing this RAM memory by adding -I16G parameter in --mm2_args

python $HOME/FLAIR/flair-master/flair.py collapse -s 1 -t 32 --mm2_args=-I16G -g $HOME/hg38.fa/hg38.fa -r "$f1".fastq.gz -q "$f1".bed -o "$f1" --keep_intermediate --temp_dir $HOME/TMP_DIR -f $HOME/gencode.v37/gencode.v37.basic.annotation.gtf 2> $HOME/TMP_DIR/"$f2"_error_gencodeannot.txt

**Comment by callumparr** [comment]
Thank you for the reply. Sounds will try to use this memory fix.
