### ISSUE TITLE
diffsplice_fishers_exact.py produces adjusted pvalue?

### ISSUE THREAD

**Issue by MarLee39** [BrooksLabUCSC/flair#195]
Thank you for developing nice tools!  Just a question.  
Are p-values in the output of diffsplice_fishers_exact.py adjusted or not?

**Comment by Jeltje** [comment]
I believe they are not adjusted. You can read up on it here:
https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.fisher_exact.html

In the new releases, diffsplice_fishers_exact.py has been renamed to diff_iso_usage.py and moved to `/src`
Please let us know if you have any other questions (we're monitoring the tickets more closely now).
