### ISSUE TITLE
plot_isoform_usage.py can not create gene_name_isoforms.png

### ISSUE THREAD

**Issue by kabanowa47** [BrooksLabUCSC/flair#199]
Hi Developers,
Many thanks for this lovely package!
Do you have any idea why plot_isoform_usage.py gives me only one plot instead of two plots? I can create only gene_name_usage.png, which is nice, however, I would like to get more. Any ideas about what might be missing here? There is no warning. I am running this script on docker and all the necessary python libraries (seaborn, matplotlib) seem to be installed in the right way. 
Thanks for your attention :)

**Comment by Jeltje** [comment]
Hi, 

Glad you like it!

Unfortunately I can't repeat this problem. I'm attaching my test files, please  unzip and run
```
plot_isoform_usage.py test.collapse.isoforms.bed counts_matrix.2.tsv ENST00000256078.9_ENSG00000133703.12  -o myoutput
```
You should get `myoutput_isoforms.png` and  `myoutput_usage.png`

If you are still having problems, please reopen this ticket and attach (a small version of) your input files.

[isoUsa.zip](https://github.com/BrooksLabUCSC/flair/files/8972084/isoUsa.zip)
