### ISSUE TITLE
flair align - no mapping

### ISSUE THREAD

**Issue by steffi778** [BrooksLabUCSC/flair#2]
Hello,

I just found your tool and I am really excited to try it out for my PacBio data.
However, I tried at first flair align and it did not work at all. It seems it skips the mapping because my generated bam file is empty... 

Of course I can map my data independently but maybe you can check the wrapper function?

Here my command & output:

python ~/programs/flair/flair.py align -r filtered.A_Nipponbare.fasta -g Oryza_sativa.IRGSP-1.0.dna.toplevel.fa -sam samtools1.9 -o test_Nipponbare -m ~/programs/minimap2/minimap2

Aligning to the genome with minimap2
Converting output sam
[E::hts_open_format] Failed to open file test_Nipponbare.sam
samtools view: failed to open "test_Nipponbare.sam" for reading: No such file or directory
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
[E::hts_open_format] Failed to open file test_Nipponbare.bam
samtools index: failed to open "test_Nipponbare.bam": No such file or directory

**Comment by belgravia** [comment]
Hello! So I forgot to uncomment some important lines for minimap2 alignment. I have fixed this now and the wrapper should work. Let me know if there are more issues.
-Alison

**Comment by steffi778** [comment]
Cool, thanks.
Just tried it out and the mapping is working now.

Problem now to sort the bam file. I gave my file an output name with the -o flag and I got a "name.unsorted.bam". Samtools tells me now "name.bam": No such file or directory. 

Maybe you can add the "unsorted" to the output name in your script and then it should work?

Cheers,
Stephie
