### ISSUE TITLE
flair exits with success status on error cases

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#20]
There are many places where flair exits with a zero status when an error occurs.  This makes it impossible to build a robust pipeline with flair.

for example
`        except:
                sys.stderr.write('Possible minimap2/samtools error, specify paths or make sure they are in $PATH\n')
                sys.exit()
`

**Comment by belgravia** [comment]
We've updated the wrapper script to exit with exit code 1 when an error is caught.
-Alison
