### ISSUE TITLE
list index out of range while retraining TARSClassifier

### ISSUE THREAD

**Issue by zeos** [BrooksLabUCSC/flair#201]
while training a few shots tars classifier on a news dataset, I get this:

```
trainer.train(base_path='models/tars-base-refined.multilingual/',  # path to store the model artifacts
  File "../.local/lib/python3.8/site-packages/flair/trainers/trainer.py", line 516, in train
    dynamic_embeddings = identify_dynamic_embeddings(batch[0])
  File "../.local/lib/python3.8/site-packages/flair/training_utils.py", line 399, in identify_dynamic_embeddings
    first_token = data_point[0]
  File "../.local/lib/python3.8/site-packages/flair/data.py", line 975, in __getitem__
    return self.tokens[subscript]
IndexError: list index out of range
```
my corpus:
Corpus: "Corpus: 95775 train + 10642 dev + 39152 test sentences"
I have 15 labels, some have more documents associated, other less

I am using cuda, Ubuntu 20.04, Python 3.8
 
how can I avoid the error " list index out of range" in this case?

thanks for any feedback

**Comment by Jeltje** [comment]
Hi Zeos,

For reasons I'm not yet clear on, flair requires python3.6. Is it possible for you to create a `virtualenv` with python 3.6.5 and try again?

**Comment by Jeltje** [comment]
I think you are referring to a different flair, probably this one: https://github.com/muellerzr/flair
