### ISSUE TITLE
no .bed out from flair.py align

### ISSUE THREAD

**Issue by MustafaElshani** [BrooksLabUCSC/flair#206]
Using latest builds there are no .bed files in the output folder from running flair.py align, running latest samtools version 1.15.1.  In addition, there are no sorted .bam files either.

the only files I get is 
.psl 
.sam 
.unsorted.bam and 
unsorted.bam.stderr

Any help is very much appreciated

Kind Regards

**Comment by MustafaElshani** [comment]
This seems to resolve with ` -v1.3 `
Maybe this should be arranged to accommodate only latest samtools since v1.3 is now ol

**Comment by Jeltje** [comment]
Thank you for this bug report. I have updated the code to improve version checking, it should now work with all samtools versions >= 1.3. We will soon do a new release that includes this fix. 
If you want to start using the latest version, please `git clone git@github.com:BrooksLabUCSC/flair.git`

Please reopen this ticket if this does not solve your problem.
