### ISSUE TITLE
flair correct error

### ISSUE THREAD

**Issue by guandailu** [BrooksLabUCSC/flair#207]
Command: flair.py correct -q flair.aligned.bed -g ../00_ref/Gallus_gallus.GRCg6a.dna_sm.toplevel.fa -f ../00_ref/Gallus_gallus.GRCg6a.102.gtf

Step 1/5: Splitting junctions from GTF by chromosome: 100%|████████████████████████████████████| 39288/39288 [00:00<00:00, 57308.79it/s]
Step 3/5: Preparing annotated junctions to use for correction: 100%|█████████████████████████████████| 160/160 [00:01<00:00, 140.47it/s]
Step 4/5: Preparing reads for correction: 187929it [00:01, 183547.76it/s]███████████████████████████▌| 158/160 [00:01<00:00, 348.46it/s]
Step 5/5: Correcting Splice Sites: 100%|████████████████████████████████████████████████████████████████| 50/50 [00:00<00:00, 50.59it/s]
Traceback (most recent call last):  90%|█████████████████████████████████████████████████████████▌      | 45/50 [00:00<00:00, 50.73it/s]
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/24_flair/flair/bin/ssCorrect.py", line 425, in <module>
    main()
  File "/group/zhougrp/dguan/nanopore_annotation/Chicken/24_flair/flair/bin/ssCorrect.py", line 407, in main
    with open(os.path.join(tempDir, "%s_inconsistent.bed" % chrom),'rb') as fd:
FileNotFoundError: [Errno 2] No such file or directory: '/group/zhougrp/dguan/nanopore_annotation/Chicken/24_flair/tmp_c484aeea-2f06-4058-9a1a-de123aefec21/MT_inconsistent.bed'
Correction command did not exit with success status

<img width="1512" alt="image" src="https://user-images.githubusercontent.com/33689045/178519091-2105e368-d206-4911-a0e2-4047594df2fd.png">

**Comment by Jeltje** [comment]
It looks like `Gallus_gallus.GRCg6a.102.gtf` has annotations for chromosomes that are not present in `Gallus_gallus.GRCg6a.dna_sm.toplevel.fa`
Can you make sure that all chromosomes in the first field of the `gtf` are present _with the exact same name_ in the fasta file?
For instance, if your annotation uses `MT` but the sequence is present as `>chrMT` or `>mt` you will get this error.

**Comment by Jeltje** [comment]
Correction, I was wrong. I had introduced a bug that caused `flair correct` to die if no introns were found (which is expected with mitochondrial annotations).
Release `v1.6.1` fixes this.

Please reopen this ticket if this didn't solve your problem.
