### ISSUE TITLE
make sure psl are valid and pass pslCheck

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#21]
The alignment statistics are not filled in. While not possible without an RNA sequence, at least set them to all bases matching so that pslCheck can be used to validate alignments.

**Comment by belgravia** [comment]
I've updated the script flair-correct that outputs the psl file of corrected reads (in particular, tNumInsert and tBaseInsert following the c code you provided). Now when I run pslCheck on it, none of the reads fail. I have pushed these changes, hopefully it's correct now.
-Alison

**Comment by diekhans** [comment]
Awesome.  I am working on doing a big FLAIR run and will try it.
