### ISSUE TITLE
assign reads into isoforms without mapping

### ISSUE THREAD

**Issue by xieyy46** [BrooksLabUCSC/flair#211]
Hi flair team! I wonder if I can assign reads into isoforms without using the minimap2 mapping step? As you konw, I have mapped my reads to genome before using flair. What I want to do is grouping reads into isoforms whatever new isoforms or annotated isoforms from GTF.

**Comment by Jeltje** [comment]
I'm not sure I understand the question. If you want to assign reads to isoforms, you need to do a mapping step at some point. Either you align the reads to the genome (that's what `flair align` does) and then use the coordinates to map them to the isoform coordinates, or you align the reads to the transcripts (which is in part what `flair collapse` does).

Can you be a bit more specific? What is your end goal?

**Comment by Jeltje** [comment]
Please reopen this ticket if you have more information
