### ISSUE TITLE
FLAIR correct error with chr1_inconsistent.bed?

### ISSUE THREAD

**Issue by seongwoohan** [BrooksLabUCSC/flair#217]
Hi there, I would like to run FLAIR correct with the given command line. I am not sure if "tmp_[]" file should be automatically generated. Also, in that file, all bed files looks like in the screenshot below. Can somebody help to run this command line properly without errors, please?

<img width="1107" alt="Screen Shot 2022-09-06 at 4 52 18 PM" src="https://user-images.githubusercontent.com/19489536/188737109-c41617a3-45d1-42ba-9ed4-1a1170beb9dd.png">
<img width="998" alt="Screen Shot 2022-09-06 at 5 02 01 PM" src="https://user-images.githubusercontent.com/19489536/188737518-85233d73-6996-4e56-aade-1daa36fc4adf.png">

**Comment by SEVEN-XYCHEN** [comment]
I have also encountered this problem. Have you resolved it?
