### ISSUE TITLE
DRIMSeq was triggered even without specifiying '--test' for flair diffSplice 

### ISSUE THREAD

**Issue by yjx1217** [BrooksLabUCSC/flair#220]
Hello,

I was running flair (v1.6.3 installed via conda) for my testing data with only two replicates for each comparison group, therefore I used the following command to perform flair diffSplice analysis >>

```
$flair_dir/flair diffSplice -i $isoform_bed_file -q $quantification_tsv_file -t $threads --conditionA $conditionA --conditionB conditionB -o $prefix.output.txt
```
According to the manual, this should not trigger DRIMSeq given that I didn't specify "--test" in my command. However, the error message below that I received suggested DRIMSeq testing has been triggered somehow and that caused the error. 

```
DRIMSeq testing for each AS event type
Traceback (most recent call last):
  File "/public/jxyue/Projects/flair_Test/build/flair_conda_env/bin/flair", line 10, in <module>
    sys.exit(main())
  File "/public/jxyue/Projects/flair_Test/build/flair_conda_env/lib/python3.10/site-packages/flair/flair.py", line 1180, in main
    status = diffSplice()
  File "/public/jxyue/Projects/flair_Test/build/flair_conda_env/lib/python3.10/site-packages/flair/flair.py", line 1086, in diffSplice
    subprocess.check_call(ds_command + ['--matrix', args.o+'.es.events.quant.tsv', '--prefix', args.o+'.es'], stderr=ds_stderr)
  File "/public/jxyue/Projects/flair_Test/build/flair_conda_env/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/public/jxyue/Projects/flair_Test/build/flair_conda_env/bin/python', '/public/jxyue/Projects/flair_Test/build/flair_conda_env/lib/python3.10/site-packages/flair/runDS.py', '--threads', '32', '--drim1', '6', '--drim2', '3', '--drim3', '15', '--drim4', '5', '--conditionA', 'TENT5A_MUT', '--conditionB', 'TENT5A_MUT', '--matrix', 'Batch_polyA.TENT5A_MUT-TENT5A_WT.differential_spliced_isoforms.raw.txt.es.events.quant.tsv', '--prefix', 'Batch_polyA.TENT5A_MUT-TENT5A_WT.differential_spliced_isoforms.raw.txt.es']' returned non-zero exit status 1.

```
Could you help me out? Thanks in advance!

**What else do we need to know?**
***How did you install Flair?***

1. bioconda (e.g. `conda create -n flair -c conda-forge -c bioconda flair`)

**Comment by yjx1217** [comment]
Me again. A closer look suggests the source of the problem should be triggered by line 1072 in the file `flair_conda_env/lib/python3.10/site-packages/flair/flair.py`

 ```
if args.test or args.conditionA:
                sys.stderr.write('DRIMSeq testing for each AS event type\n')
```
 
Shouldn't the "or" be "and" instead ?

Best,
Jia-Xing

**Comment by Jeltje** [comment]
Thanks for reporting this problem!

I think the documentation is unclear but the code is correct: if you don't want to run diffSplice you don't need to specify conditionA or conditionB. I will add that information to the documentation and have the program throw a warning.

Hope that helps. If so, please close this ticket.

**Comment by yjx1217** [comment]
Hi Jeltje,

I see. Thanks for the quick reply! I will close the ticket.

Best,
Jia-Xing
