### ISSUE TITLE
Slow processing speed for the large number of samples (collapse stage)

### ISSUE THREAD

**Issue by hd00ljy** [BrooksLabUCSC/flair#224]
Hello,

I have >50 RNA-seq samples to run and at the flair collapse stage I merged all samples as suggested in the manual.
That is, I concatenated all the corrected.bed file into a single file

But it took too much time to process all samples on 28 cores 500gb RAM

I have 2 questions regarding this,

Q1. What is your suggestion for large number of samples?

Q2. Do you have plans to make options for cluster computing? (such as PBSpro, SGE, Slurm)
      At least for the "collapse" stage.

Thank you
Jin-Young

**Comment by hd00ljy** [comment]
Oh, sorry. I just found out on the collapse range bash script you provided.
it would also possible to submit to PBS using this

Thank you!

**Comment by Jeltje** [comment]
Great! Please create a new ticket if that causes any issues, we have recently been streamlining the code but didn't get to that section yet.
An alternative to creating ranges is splitting by chromosome, which is fairly easily to do manually beforehand.
