### ISSUE TITLE
--fusion_dist option in collapse module

### ISSUE THREAD

**Issue by Drosofriends** [BrooksLabUCSC/flair#227]
Hi, I tried to run collapse module  on one single sample  with the option --fusion_dist and this error occured:

Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Renaming isoforms using gtf
Aligning reads to first-pass isoform reference
A valid isoforms bed file needs to be specified: 
Failed at counting step for isoform read support

If I run the collapse module on one single sample  without the option --fusion_dist everything works
Any help?
thank you!

**Comment by Jeltje** [comment]
Did you give it an isoform bed file?

Please include the full command you used when you create a ticket.

**Comment by Drosofriends** [comment]
python /home/Documents/FLAIR/flair-master/flair.py collapse --genome /home/Documents/gtf_genome/Dmel6.32.dna.toplevel.fa --reads /home/Documents/Fastq_files/Sample.fastq --query /home/Documents/FLAIR/flair_collapse/Sample_single_output/Sample.isoforms.bed --gtf /home/Documents/gtf_genome/Dmel6.32.106.gtf --threads 8 --support 3  --fusion_dist 10 --temp_dir /home/Documents/Elements/ --output /home/Documents/FLAIR/flair_collapse/Sample_single_output/sample

I tried to run this code once using the isoforms.bed generated by the collapse module and once using the corrected.bed in --query but the same error occured.
What kind of .bed file I have to use?

**Comment by Jeltje** [comment]
Thank you! You did indeed find a bug.

Please replace your flair.py with [the current version](https://github.com/BrooksLabUCSC/flair/blob/master/src/flair/flair.py). 

Reopen this ticket if this did not fix the problem.

**Comment by Drosofriends** [comment]
python /home/Documents/FLAIR/flair-master/flair.py collapse --genome /home/Documents/gtf_genome/Dmel6.32.dna.toplevel.fa --reads /home/Documents/Fastq_files/Sample.fastq --query /home/Documents/FLAIR/flair_collapse/Sample_single_output/Sample.isoforms.bed --gtf /home/Documents/gtf_genome/Dmel6.32.106.gtf --threads 8 --support 3 --fusion_dist 10 --temp_dir /home/Documents/Elements/ --output /home/Documents/FLAIR/flair_collapse/Sample_single_output/sample

```
  File "/home/Documents/FLAIR/flair-master/flair.py", line 49
    sys.stderr.write(f'Check that read file {rfile} exists\n')
                                                            ^
SyntaxError: invalid syntax

Hi I tried to run your  corrected flair.py but this error occured. Why?
thank you for your support

**Comment by Jeltje** [comment]
I can't repeat this problem. That section of the code did not change and it's from an unrelated part of the program (flar align instead of flair collapse). 
How did you download the code?

**Comment by Drosofriends** [comment]
I downloaded again the folder "flair-master" (with your corrected flair.py) and I replaced the old version flair-master with the new corrected one.

**Comment by Jeltje** [comment]
Fusion_dist was implemented to deal with reads derived from fusion genes. When such reads are aligned to a regular genome they tend to split between their genes of origin, and this was a way to be able to count them. 
We plan to remove this option in a future release as it's not really useful and creates confusion.
