### ISSUE TITLE
Should I turn on or turn off the "--u_substitution" for guppy basecalling if I use Flair for my downstream analysis?

### ISSUE THREAD

**Issue by yjx1217** [BrooksLabUCSC/flair#228]
Dear developers,

Should I turn on or turn off the "--u_substitution" option for guppy basecalling if I use Flair for my downstream analysis?
Not sure how Flair treat U in the transcript sequences. At least in Flair's plot_isoform_usage script, I saw 'U' is not defined in variables such as base_colors  and reverse_complement.
Thanks in advance!

Best,
Jia-Xing

**Comment by Jeltje** [comment]
Flair runs minimap2, which I believe does not expect U bases, so it's best to turn them into Ts.
