### ISSUE TITLE
Input for diff_iso_usage.py

### ISSUE THREAD

**Issue by drc111** [BrooksLabUCSC/flair#23]
I have a problem figuring out which columns are used as input in the diff_iso_usage.py script.

Before appending the counts to .psl, it is clear that the columns containing the read counts are #2 and #3 in my counts_matrix.tsv file. 

But after appending to .psl, I cannot figure out the right columns to specified as input in my output.psl file for diff_iso_usage.py.

[tsv_psl.tar.gz](https://github.com/BrooksLabUCSC/flair/files/3176943/tsv_psl.tar.gz)

**Comment by belgravia** [comment]
I checked your counts_matrix.tsv and output.psl and it looks like the appending behaved as expected. The last two columns of output.psl contain expression values for your two samples. So the command to run the script on your data would look like 
`python /pathtoflair/bin/diff_iso_usage.py output.psl 21 22 diff_iso_output.txt`. The columns need to be specified 0-indexed, and I realize that might have caused confusion. 
-Alison
