### ISSUE TITLE
diffSplice showing the same value for all replicates

### ISSUE THREAD

**Issue by fburdet** [BrooksLabUCSC/flair#235]
Hello,

I have an ONT experiment with 2 conditions, 4 replicates per conditions.

I used reads from pychopper, alidnted, corrected, merged (I used the 8 replicates to generate a bed file), collapsed into an isoforms bed, quantified.

Then I used diffSplice using the collapsed bed and the counts.tsv table, and the --test option.

Everything ran without an error.

What is weird is in the 4 drimseq files. The 4 replicates always have the same value, eg

==> drimseq_ir_DKO_v_WT.tsv <==
feature_id	gene_id	DKO1_DKO_batch1	DKO2_DKO_batch1	DKO3_DKO_batch1	DKO4_DKO_batch1	WT1_WT_batch1	WT2_WT_batch1	WT3_WT_batch1	WT4_WT_batch1	lr	adj_pvalue
exclusion_chr14:47006354-47007289+	chr14:47006354-47007289	0.953	0.953	0.953	0.953	0.472	0.4720.472	0.472	506.01	1.02e-107
inclusion_chr14:47006354-47007289+	chr14:47006354-47007289	0.047	0.047	0.047	0.047	0.528	0.5280.528	0.528	506.01	1.02e-107
exclusion_chr14:47002497-47004632+	chr14:47002497-47004632	0.961	0.961	0.961	0.961	0.537	0.5370.537	0.537	451.98	2.93e-96
inclusion_chr14:47002497-47004632+	chr14:47002497-47004632	0.039	0.039	0.039	0.039	0.463	0.4630

That looks suspiciously weird... is that normal?

Thanks in advance!

**Comment by Jeltje** [comment]
It is normal behavior, see #234
