### ISSUE TITLE
Test data set

### ISSUE THREAD

**Issue by drc111** [BrooksLabUCSC/flair#24]
I am looking much into this tool for differential isoform usage analysis, and I was wondering if you could make a data set available as well as your results for such data set to evaluate if FLAIR is working correctly on my system prior to running my own data.

That would be greatly appreciated!

**Comment by drc111** [comment]
I know you already have made some example data available, however, it would be great to compare my own results to yours (if made available).

**Comment by belgravia** [comment]
Currently we don't have any samples of our own to provide to you for using FLAIR differential isoform usage analysis. 

You could use the example data from the RNA consortium to assemble isoforms using FLAIR (flair-align/corrrect/collapse). We have experience running FLAIR on that data. For the differential isoform usage analysis, you could potentially take long reads from another publication for now.

FLAIR doesn't take too long to run, so unless you have reason to believe FLAIR would not work on your system I would suggest running FLAIR on your data and posting any issues you have along the way here. I can give you a rough time estimate on how long FLAIR would take you depending on the number of reads you have if you'd like. Also, we have a docker container that you can use if the system is a concern.

-Alison

**Comment by drc111** [comment]
Okay, I will try that. Thanks!
