### ISSUE TITLE
flair align: bed file did not generate

### ISSUE THREAD

**Issue by shamsbhuiyan** [BrooksLabUCSC/flair#25]
Hello,

I ran flair align on my reads and I believe that the correct sam file is generated as well as a bam file. However, there is no bed file that generates. I get this output after minimap finishes running:

```
[M::main] Real time: 73222.383 sec; CPU: 731142.740 sec
Converting sam output to bed
[bam_sort] Use -T PREFIX / -o FILE to specify temporary and final output files
Usage: samtools sort [options...] [in.bam]
Options:
  -l INT     Set compression level, from 0 (uncompressed) to 9 (best)
  -m INT     Set maximum memory per thread; suffix K/M/G recognized [768M]
  -n         Sort by read name
  -t TAG     Sort by value of TAG. Uses position as secondary index (or read name if -n is set)
  -o FILE    Write final output to FILE rather than standard output
  -T PREFIX  Write temporary files to PREFIX.nnnn.bam
      --input-fmt-option OPT[=VAL]
               Specify a single input file format option in the form
               of OPTION or OPTION=VALUE
  -O, --output-fmt FORMAT[,OPT[=VAL]]...
               Specify output format (SAM, BAM, CRAM)
      --output-fmt-option OPT[=VAL]
               Specify a single output file format option in the form
               of OPTION or OPTION=VALUE
      --reference FILE
               Reference sequence FASTA FILE [null]
  -@, --threads INT
               Number of additional threads to use [0]
If using samtools v1.3+, please specify -v1.3 argument
```
My samtools version is 1.8 and I'm ran flair align like this:

`python ~/flair/flair.py align -m ~/minimap2/ -t 10 -r /space/collaborator/upload/Chip158_N90_pass.fq -g /space/grp/Pipelines/rnaseq-pipeline/Assemblies/Rattus_norvegicus/Ensembl/Rnor_6.0/Sequence/WholeGenomeFasta/genome.fa`

I also saw that there was previous issue in January to just run the bam2bed.py script as follows: `python pathtoflair/bin/bam2Bed12.py -i sorted.bam > sorted.bed`
However, this resulted in this 

```
Traceback (most recent call last):
  File "/home/sbhuiyan/flair/bin/bam2Bed12.py", line 22, in <module>
    from samJuncs import SAM
  File "/home/sbhuiyan/flair/bin/samJuncs.py", line 24, in <module>
    from tqdm import *
ImportError: No module named tqdm
```
What should I do?

**Comment by belgravia** [comment]
Can you try adding `-v1.3` to your command if you haven't already? 

`python ~/flair/flair.py align -m ~/minimap2/ -t 10 -r /space/collaborator/upload/Chip158_N90_pass.fq -g /space/grp/Pipelines/rnaseq-pipeline/Assemblies/Rattus_norvegicus/Ensembl/Rnor_6.0/Sequence/WholeGenomeFasta/genome.fa -v1.3` should work.
I think this may be error found in [issue 2](https://github.com/BrooksLabUCSC/flair/issues/2) where different versions of samtools sort have different command line syntaxes.

Let me know how that goes!
-Alison

**Comment by shamsbhuiyan** [comment]
Worked! Thanks!
