### ISSUE TITLE
Fresh flair install fails align test. [makefile:26: test-align] Error 1

### ISSUE THREAD

**Issue by Hans4984** [BrooksLabUCSC/flair#258]
(flair) hans4984@BensXPS:~/flair/test$ make test

**How did you install Flair?**
installed using in amamba enviroment using:
mamba create -n flair -c conda-forge -c bioconda flair

I just installed flair and ran the test. it failed during the align test. produced all 3 bam/bami/bed outputs.

```
mkdir -p test_output
mkdir -p test_diffs
flair align -r test_input/reads.fa --genome test_input/genome.fa -t 4 -o test_output/test.align
[M::mm_idx_gen::4.718*1.44] collected minimizers
[M::mm_idx_gen::5.974*1.97] sorted minimizers
[M::main::5.974*1.97] loaded/built the index for 3 target sequence(s)
[M::mm_mapopt_update::6.496*1.89] mid_occ = 262
[M::mm_idx_stat] kmer size: 15; skip: 5; is_hpc: 0; #seq: 3
[M::mm_idx_stat::6.816*1.85] distinct minimizers: 49293178 (70.30% are singletons); average occurrences: 1.945; average spacing: 2.930; total length: 280976917
[M::worker_pipeline::7.942*2.14] mapped 1883 sequences
[M::main] Version: 2.26-r1175
[M::main] CMD: minimap2 -ax splice --secondary=no -t 4 test_input/genome.fa test_input/reads.fa
[M::main] Real time: 7.970 sec; CPU: 17.033 sec; Peak RSS: 2.723 GB
diff <(sort test_expected/test.align.bed) <(sort test_output/test.align.bed) > test_diffs/test.align.diff
make: *** [makefile:26: test-align] Error 1
```
We know it's ugly but we promise it helps us solve problems faster.

**What else do we need to know?**
Go ahead, every bit helps.

**Comment by Jeltje** [comment]
That's odd, sorry to hear that.
Could you copy (the first few lines of) test_diffs/test.align.diff ?
And what's the result of `wc -l test_expected/test.align.bed  test_output/test.align.bed` ?

**Comment by Jeltje** [comment]
I cannot reproduce the error. Please reopen this ticket if you want to continue this conversation.
