### ISSUE TITLE
Error in filter_isoforms_by_proportion_of_gene_expr.py

### ISSUE THREAD

**Issue by eschiks** [BrooksLabUCSC/flair#261]
I was getting an error message when using a --support value below 0 for the collapse module. There was an error in the script filter_isoforms_by_proportion_of_gene_expr.py. I changed 2 lines, which fixed it:

line 58: gene_total = float(sum([**float(iso[0][-1]**) for iso in genes[gene]])) CHANGED TO gene_total = float(sum(**[float(iso[-1]**) for iso in genes[gene]]))

line 62: if float(**iso[0][-1]**)/gene_total >= s: CHANGED TO if float(**iso[-1]**)/gene_total >= s:

It works fine for me now, just wanted to alert you of this issue!

**Comment by Jeltje** [comment]
That's quite a big bug you found there, thanks! Fixed. Will do new release soon.
