### ISSUE TITLE
Flair collapse returns isoform as same as reference

### ISSUE THREAD

**Issue by NHoang98** [BrooksLabUCSC/flair#262]
Hello,
I'm having my very first experiment with flair for my ONT data. But while running the collapse module, I'm facing the issue when the *.isoform.gtf somehow keeps returning isoforms the same as the reference annotation. I've checked the exon boundary manually (both in genome viewer and gtf files) and didn't see the difference.

![Luamau](https://github.com/BrooksLabUCSC/flair/assets/111427687/f52423bf-4e59-4cc7-979e-59f4695acd77)

The script was:
 `flair collapse -g Documents/Luamau/Ref/R498.fasta -q Documents/Luamau/FLAIR2/correct/correct/Luamau.bed -r Documents/Luamau/Trim-read/*.fastq -f Documents/Luamau/Ref/R498.gtf -o Documents/Luamau/FLAIR2/collapse/Luamau_ultraII -t 16 --generate_map --stringent --isoformtss --annotation_reliant generate --check_splice --keep_intermediate --support 0.1 --filter nosubset --no_redundant best_only`

Could you please explain to me what I've done that led to this problem?

Bests,
Hoang

**Comment by Jeltje** [comment]
It may have to do with your last option `--no_redundant best_only`
This asks flair to report only the most supported isoform, and that's probably the reference one.

Removing that should give you better results.

**Comment by Jeltje** [comment]
Closing because no response. Please reopen if your issue was not resolved.
