### ISSUE TITLE
Error while running collapse

### ISSUE THREAD

**Issue by kundariyahardik** [BrooksLabUCSC/flair#267]
*Copy and paste the exact command you tried to run**

flair-master/bin/flair collapse -g TAIR10_chr_all.fa -q  Chr1_all_corrected.bed \
-r vegetable.flw_1.subreads.fastq.gz,vegetable.flw_2.subreads.fastq.gz \
--output flw --gtf Arabidopsis_thaliana.TAIR10.38.gtf \
--threads 6 --generate_map --annotation_reliant generate

**How did you install Flair?**
(We'd prefer it if you used one of the top two because they are the least likely to have package compatibility problems.)
4. downloaded latest release from github

**What happened?**
I am getting following error while running collapse
```
Starting collapse...
Writing temporary files to /tmp/tmpxuyylh47/
Making transcript fasta using annotated gtf and genome sequence
Traceback (most recent call last):
  File "/data5/hsk13/IsoSeq/flair-master/src/flair/gtf_to_bed.py", line 108, in <module>
    if blockcount > 1 and blockstarts[0] > blockstarts[1]:  # need to reverse exons
IndexError: list index out of range
Traceback (most recent call last):
  File "/data5/hsk13/IsoSeq/flair-master/bin/flair", line 1126, in <module>
    main()
  File "/data5/hsk13/IsoSeq/flair-master/bin/flair", line 1047, in main
    status = collapse()
  File "/data5/hsk13/IsoSeq/flair-master/bin/flair", line 523, in collapse
    subprocess.check_call([sys.executable, path+'gtf_to_bed.py', args.f, args.annotated_bed, '--include_gene'])
  File "/data5/hsk13/anaconda3/envs/py3.10/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/data5/hsk13/anaconda3/envs/py3.10/bin/python3', '/data5/hsk13/IsoSeq/flair-master/src/flair/gtf_to_bed.py', '/data5/hsk13/IsoSeq/Arabidopsis_thaliana.TAIR10.38.gtf', 'flw.annotated_transcripts.bed', '--include_gene']' returned non-zero exit status 1.

```

**What else do we need to know?**
I tried running gtf_to_bed.py using following command:
/data5/hsk13/IsoSeq/flair-master/src/flair/gtf_to_bed.py /data5/hsk13/IsoSeq/Arabidopsis_thaliana.TAIR10.38.gtf TAIR10_38_gtf.bed

Gives following error:
Traceback (most recent call last):
  File "/data5/hsk13/IsoSeq/flair-master/src/flair/gtf_to_bed.py", line 108, in <module>
    if blockcount > 1 and blockstarts[0] > blockstarts[1]:  # need to reverse exons
IndexError: list index out of range

**Comment by Jeltje** [comment]
Could your gtf file be corrupted? Do the last lines look OK? This error comes from the final gene.

It looks like your gtf was downloaded from [Ensembl](https://plants.ensembl.org/info/data/ftp/index.html). I can't find version 38 anymore, but I downloaded the current file (57) and do not get your error.

**Comment by Jeltje** [comment]
Closing because no response; please reopen if your problem has not been resolved.

**Comment by byee4** [comment]
I hit this error too and could use some help. In order to process my dataset, I split up the data per chromosome as recommended, but it seems to dislike the last gene in mm39 chr12 ([Gencode V35](https://ftp.ebi.ac.uk/pub/databases/gencode/Gencode_mouse/release_M35/gencode.vM35.chr_patch_hapl_scaff.annotation.gtf.gz)). Below is my command, also I've attached the gzipped GTF file:
`
python /home/bay001/software/miniconda_tscc2/envs/flair-2.0.0/lib/python3.8/site-packages/flair/gtf_to_bed.py reference.chr12.gtf expt.isoforms.chr12.annotated_transcripts.bed --include_gene`

[reference.chr12.gtf.gz](https://github.com/user-attachments/files/15573197/reference.chr12.gtf.gz)
