### ISSUE TITLE
FLAIR collapse stringency

### ISSUE THREAD

**Issue by drc111** [BrooksLabUCSC/flair#27]
When I am running FLAIR collapse, it looks like the module is too strict and removes even some isoforms that are clearly present, while the firstpass isoforms appear to be a more accurate representation of the isoforms present in my samples.

GAPDH locus after FLAIR correct for the untreated sample (before FLAIR collapse)
![flair correct](https://user-images.githubusercontent.com/50618973/59279203-cc5feb80-8c63-11e9-800e-625f3257501e.png)

GAPDH locus after FLAIR collapse:
![flair collapse](https://user-images.githubusercontent.com/50618973/59279234-dc77cb00-8c63-11e9-9d10-a829f6772dc9.png)

The goal is to investigate differentially used isoforms between two samples with high confidence, but also to obtain a broad image of the genes affected globally. Do you have any suggestions regarding the stringency criteria for such analysis? Note, that I am only using the annotation GTF during correction since no short read data is available to me, and I have 100.000 reads for each of two conditions. 

Thanks in advance!

**Comment by belgravia** [comment]
Thanks for posting images of the reads, it's super helpful. Just to make sure we're on the same page, it looks like you've combined the reads from both your conditions and are showing the combined corrected reads, firstpass isoforms, and final isoforms. The file of corrected reads is given to flair-collapse to make the firstpass isoforms, a non-redundant representation of the corrected reads. The firstpass isoforms are then filtered using the combined read fastq file. 

Assuming you ran flair collapse with all the default options, a firstpass isoform with fewer than 3 supporting reads (`-s` argument) from the combined read fastq file will be removed. You can decrease this number to increase your sensitivity. The second and third GAPDH isoform in the firstpass panel have retained introns in the last and fifth-to-last splice junctions. Looking at the reads, it looks like there are only two reads that would support either one of those retentions. Thus, if there's only 1 supporting read for either of those isoforms, they will get removed.

I realize that the corrected reads screenshot is only a subset of all corrected reads. If you think that there are 3+ supporting reads for the firstpass isoforms that were removed and that they are removed in error, I will of course look into this issue more.

If you have other features you would like to see added for increasing sensitivity, please let me know!

-Alison

**Comment by drc111** [comment]
In the upper image, only the corrected reads for the untreated samples i shown.
For the lower image, the corrected reads from both conditions were combined prior to flair collapse exactly as you describe. 

Thanks for the suggestion involving the -s argument, and I see that the isoforms with intron retention are unsupported according to the default criteria.

However, as you see on the upper image, it looks like an isoform containing all exons except the first is supported by 3+ reads EXCEPT that the reads slightly deviate in their 5' end and thus does not pass the flair collapse criteria (I have zoomed in on these reads on the image below).

![flair correct2](https://user-images.githubusercontent.com/50618973/59592956-4e7f6280-90f1-11e9-8b0c-e3d84c0ccf2c.png)

Do you think that isoform should have passed flair collapse?

Since I am also interested in how splicing is globally affected, I have also been using the corrected reads directly after flair correct as input for the mark_intron_retention.py script, which have allowed me to detect global differences between treated(untreated samples. This works, I assume, since the corrected reads in this case is used as "isoforms".

**Comment by belgravia** [comment]
Hi,

There is a step of FLAIR collapse that filters out subset isoforms by default. So for this example, since a longer version of these reads is already represented, the shorter isoform missing just the first exon is removed. If you would like to keep these subset isoforms, you can specify `-e comprehensive`!

Thank you for extreme patience! I missed this post by accident until now that I'm cleaning through old issues. If this ever happens again feel free to poke me more. 
-Alison

**Comment by drc111** [comment]
Thanks a lot for your help!
- Sebastian
