### ISSUE TITLE
FLAIR silently continues if no short read junctions are added 

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#275]
If FLAIR fails to add any splice junctions, possibly due to file format issue, it continues to run with no obvious indication that it is not using this evidence.

Unless one carefully digs through the noise in the log files, this is not obvious and the actually reason is not reported

**Comment by cafelton** [comment]
Is this in FLAIR correct and referencing the --shortread input?
Related to #278 ?

**Comment by diekhans** [comment]
this is related to #273 as well

**Comment by diekhans** [comment]
Jeltje fixed this so that it will generate an error if no junctions were read from the files.
