### ISSUE TITLE
FLAIR need obvious succes or failure message

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#277]
" If you do not see this message, please check your run."

is not that helpful; something that is obviously SUCCESS or FAILED and documented as such would be very helpful

**Comment by Jeltje** [comment]
I'm not sure how to signify FAILED other than the error messages you get when it does...?

**Comment by diekhans** [comment]
I think this complaint (which is passed on) was more that it didn't say that it succeeded.

Probably need to just give all the message a review at some point to see if they
make sense.
