### ISSUE TITLE
Error in collapse

### ISSUE THREAD

**Issue by knewl** [BrooksLabUCSC/flair#30]
Hello,

I've just noticed a tiny bug in the collapse stage which causes the following error:

```
Filtering isoforms
Renaming isoforms
Traceback (most recent call last):
  File "../flair/bin/identify_gene_isoform.py", line 105, in <module>
    tn_to_juncs[chrom][this_transcript] = junctions
KeyError: 'NC_006839.1'

```

This is my command:

`$ python flair.py collapse -r reads.fastq.gz -g ../../reference/GCF_000004195.3_Xenopus_tropicalis_v9.1_genomic.fna -q flair.correct.psl -o flair.collapse -f ../../reference/GCF_000004195.3_Xenopus_tropicalis_v9.1_genomic.gtf -t 8`

I think it's due to the fact that the final chromosome in my gtf file (NC_006839.1) is the mitochondrial genome which has no exons. So in may case I had to remove 3 lines of code (105-107) in identify_gene_isoform.py and it worked fine.

Cheers,

Katherine

**Comment by belgravia** [comment]
Thanks Katherine for notifying me of this. I've added an extra condition in front of those statements (`if this_transcript != prev_transcript:`) to address this for the users who have GTFs that end with chromosomes with exons on them. Glad to hear that your fix was all you needed to get it to work!

**Comment by knewl** [comment]
Sounds good! Thank you :)
