### ISSUE TITLE
diffSplice files are empty

### ISSUE THREAD

**Issue by ghofrankothoum** [BrooksLabUCSC/flair#307]
Command:
python3 flair-2.0.0/flair.py diffSplice -q quantify.tsv -i all.isoforms.bed -o final_diff -of

**How did you install Flair?**

2. `docker pull brookslab/flair:latest`

**What happened?**
diffsplice output files are empty  except for the header

```


**What else do we need to know?**
I had to split the input by chromosome for the collapse command. for flair quantify and diffSplice, I merged (using cat) all of the individual bed and fasta files from collapse.

**Comment by Jeltje** [comment]
This means it found no differentially expressed isoforms.
Have a look at your input count matrix to see if this makes sense.  You'll need to see substantial differences between group averages.
