### ISSUE TITLE
Running Flair with multiple samples and replicates

### ISSUE THREAD

**Issue by benpiticaru** [BrooksLabUCSC/flair#308]
**I have read the paper (https://doi.org/10.1038/s41467-020-15171-6)  
and the manual (https://flair.readthedocs.io/en/latest/) and I still have a question about**

- collapse

I am a little confused as to how to properly collapse my data.

I am running a differential splice analysis on 3 different cell lines. Each cell line has 4 replicates that consist of a treatment and control group. All 24 samples were barcoded and pooled and I performed 3 sequencing runs to collect as much data as possible. My question is, how would I go about collapsing my data to give accurate results with Flair.

Thanks.

**Comment by Jeltje** [comment]
Combine everything to run flair collapse, then use flair quantify to get per-isoform counts for each replicate.

All you're trying to do with collapse is get every supported isoform. By default an isoform needs at least 3 reads to be supported but they can come from any input file.
With your depth of sequencing you might want to set --support to a higher number of reads so avoid artefacts.
