### ISSUE TITLE
Set isoform abundance cutoff to FLAIR quantify

### ISSUE THREAD

**Issue by ulbivin** [BrooksLabUCSC/flair#321]
Hi, I have a set of samples for which I am running FLAIR. Some samples have a unique isoform which make up a substantial fraction of the gene transcript from that specific sample, but only a small fraction of the combined isoforms from all samples. Hence it is filtered out when running FLAIR quantify.

Is there a way to set the filter for FLAIR quantify to include less abundant isoforms in the count.tsv file?

**Comment by Jeltje** [comment]
When I go to the `flair/test` directory and run 
`flair quantify -r test_input/reads_manifest.txt -i test_input/test.collapse.isoforms.fa -o test_out/quant`
and then look at the first ten lines of test_out/quant.counts.tsv:
```
ids     A1_A_b0 A2_A_b0 A3_A_b0 B1_B_b0 B2_B_b0 B3_B_b0
ENST00000225792.10_ENSG00000108654.15   22.0    12.0    10.0    11.0    15.0    13.0
ENST00000256078.9_ENSG00000133703.12    7.0     6.0     7.0     15.0    11.0    7.0
ENST00000311936.8_ENSG00000133703.12    10.0    9.0     7.0     19.0    18.0    7.0
ENST00000348547.6_ENSG00000125991.19    38.0    36.0    46.0    66.0    47.0    46.0
ENST00000451605.1_ENSG00000125991.19    13.0    29.0    16.0    29.0    28.0    16.0
ENST00000557334.5_ENSG00000133703.12    3.0     0.0     4.0     8.0     10.0    4.0
HISEQ:1287:HKCG7BCX3:1:1101:14093:55880_ENSG00000133703.12      0.0     0.0     1.0     0.0     3.0     1.0
```
The last line has single read counts for two of the samples.

What is your command precisely, and which version of FLAIR are you running?

**Comment by kwonej0617** [comment]
@ulbivin 

I extracted a few lines of my result from flair quantify. I also had a bunch of lines with a small read number.  Here is my command line "flair quantify -r ../reads_manifest.tsv -i flair.collapse.isoforms.fa --threads 10" 
```
ENST00000000233.10_ENSG00000004059.11   134.0   220.0   74.0    193.0   202.0   198.0
ENST00000000412.8_ENSG00000003056.8     10.0    18.0    4.0     15.0    43.0    27.0
ENST00000000442.11_ENSG00000173153.15   0.0     6.0     0.0     1.0     3.0     2.0
ENST00000001008.6-0_ENSG00000004478.8   56.0    101.0   30.0    28.0    84.0    66.0
ENST00000002125.9-0_ENSG00000003509.16  0.0     1.0     0.0     2.0     1.0     0.0
ENST00000002165.11-0_ENSG00000001036.14 3.0     2.0     0.0     3.0     5.0     5.0
ENST00000002165.11_ENSG00000001036.14   0.0     0.0     0.0     2.0     0.0     2.0
ENST00000002501.11_ENSG00000003249.14   5.0     8.0     3.0     2.0     9.0     8.0
ENST00000002829.8_ENSG00000001617.12    1.0     2.0     0.0     0.0     2.0     0.0
ENST00000003100.13_ENSG00000001630.17   0.0     2.0     0.0     0.0     5.0     3.0
ENST00000005257.7_ENSG00000006451.8     0.0     2.0     0.0     1.0     1.0     2.0
ENST00000005259.8-0_ENSG00000075790.10  2.0     0.0     1.0     0.0     1.0     0.0
ENST00000005260.9-0_ENSG00000006453.14  0.0     0.0     0.0     0.0     1.0     0.0
ENST00000005260.9_ENSG00000006453.14    0.0     3.0     1.0     2.0     4.0     2.0
```

**Comment by cafelton** [comment]
FLAIR quantify does not filter for read depth. However, depending on the parameters you use for quantify vs collapse, you can get different support for different transcripts
