### ISSUE TITLE
add --split-prefix to collapse minimap command

### ISSUE THREAD

**Issue by Jeltje** [BrooksLabUCSC/flair#326]
Via Colette:
Another weird bug from my synthetic genome runs -  in order for FLAIR-collapse to work, I had to modify the minimap command as follows:
```
if not args.quiet:
   sys.stderr.write('Aligning reads to reference transcripts\n')
if subprocess.call(['minimap2', '-a', '-t', str(args.t), '-N', '4', '--split-prefix', 'minimap2transcriptomeindex', args.annotation_reliant] + args.r,
   stdout=open(args.o+'annotated_transcripts.alignment.sam', 'w'),
   stderr=open(args.o+'annotated_transcripts.alignment.mm2_stderr', 'w')):
   sys.stderr.write('Minimap2 issue, check stderr file\n')
   return 1
```
The changed bit is the --split-prefix thing. The reason I had to implement it is because I have so many annotated transcripts minimap2 has to make its indices differently. I think the ideal fix for this bug would be to check how many chromosomes (how many lines?) are in the annotated_transcripts.fa file and if they’re over a certain threshold, append the --split-prefix stuff to the minimap command. IDK if there’s any downside to just adding it to the command all the time though

**Comment by cafelton** [comment]
Have done a bunch of testing on this. It does fix the issue but can also create other issues in different scenarios. If other users have this problem, try giving this option to --mm2_args in flair collapse
