### ISSUE TITLE
How to count the isoforms corresponding to each gene.

### ISSUE THREAD

**Issue by anxuan-web** [BrooksLabUCSC/flair#329]
Hi,
I want to count the number of isoforms per gene.

As shown in the figure. How do I try.
![image](https://github.com/BrooksLabUCSC/flair/assets/77531332/4a89f408-bdd5-48ec-a8b7-65dfd035fd4a)

I  have get the collapse.isoforms.gtf file.

**Comment by Jeltje** [comment]
```grep -P '\ttranscript\t' test_output/collapse.isoforms.gtf | cut -f2 -d'"' | uniq -c```

**Comment by anxuan-web** [comment]
Thanks!
