### ISSUE TITLE
isoforms shorter and missing introns 

### ISSUE THREAD

**Issue by taylor-shi** [BrooksLabUCSC/flair#33]
Hi,
I am having an issue where many of the isoforms identified by flair collapse are shortened and miss reads mapped to much longer regions of the genome (see picture from IGV). Additionally, none of the isoforms seen in both the firstpass debugging and final psl files include introns; they only span a single exon or UTR. The top view is the corrected alignments (from flair correct), the following two  are debugging files, the next one is the file containing the final isoforms (from flair collapse), and the bottom view are the original mapped reads. My data is Nanopore long reads from a human cell line.

I mapped my reads separately with Minimap2 and proceeded with your protocol starting from flair correct, after converting my bam file to bed12 format.

bam_input='2019-6-25_A431/minimap_ontLR/transcriptclean_VA/_clean_sorted.bam'
python software/flair/bin/bam2Bed12.py -i bam_input > 2019-6-25_A431/minimap_ontLR/transcriptclean_VA/_clean_sorted.bed12 

#correct
bedfile='2019-6-25_A431/minimap_ontLR/transcriptclean_VA/_clean_sorted.bed12' 
genome='2019-6-13_A431/GRCh38_trimmed.fa'
output_dir='2019-6-25_A431/minimap_ontLR/transcriptclean_VA/flair/'
annot='software/flair/GRCh38_latest_genomic.gff'
samtools faidx {genome}
python3 software/flair/flair.py correct 
    -c software/bedtools2/genomes/human.hg38.genome.chrom.sizes 
    -g {genome} 
    -q {bedfile} 
    -o {output_dir}
    -f {annot}

#collapse
reads='2019-6-13_A431/fasta/merged.fasta'
query='2019-6-25_A431/minimap_ontLR/transcriptclean_VA/flair/flair_all_corrected.psl'
output_file='2019-6-25_A431/minimap_ontLR/transcriptclean_VA/flair/flair.collapse' 
python3 software/flair/flair.py collapse 
    -g {genome} 
    -r {reads} #raw reads before alignment
    -f {annot}
    -s 1   # minimum number of supporting reads for an isoform (3) -s 
    -o {output_file} 
    -q {query}

If you have any advice for how to troubleshoot this or need any additional information in order to resolve this issue, please let me know! Thank you in advance ~

![flair_troubleshoot](https://user-images.githubusercontent.com/52465564/60537095-93dc8c00-9cbc-11e9-9342-1f26f19b3cb8.PNG)

**Comment by belgravia** [comment]
Thanks for looking into the debugging files. So it looks like all the multiexonic isoforms are being filtered out in the collapse step. Would you be able to send me the entries from `flair.collapse.firstpass.unfiltered.psl` for a single gene? That would be most illuminating for me. Thanks!

In the meantime, you could run collapse with the additional argument `-e comprehensive` and that should keep all of your multiexonic reads in the `flair.collapse.firstpass.psl` file. 

-Alison

**Comment by taylor-shi** [comment]
Thanks for the quick response Alison! So a new development occurred in the past 24 hours. I tried to recreate the flair_all_corrected.psl output from the flair correct script and am now  seeing that all of the mapped reads from the bed12 input are being collapsed into one large isoform, even given different splice junctions from the mappings. However, the collapse step is successfully retaining multiexonic isoforms now. I wasn't able to locate flair_all_corrected.psl file shown in the picture from my first post unfortunately, so the main issue now is not having the reads collapse in the flair correct step. 

I used the same exact command as posted above, so I have no idea why this issue is suddenly happening. 
See the picture below, and let me know if you have any feedback!
![flair_troubleshoot2](https://user-images.githubusercontent.com/52465564/60615871-0153ef80-9d85-11e9-8403-b384c423570f.PNG)

**Comment by belgravia** [comment]
It might be easier to tell what's going on if you switch your IGV view of the psl tracks to 'squished'. It looks like there are more isoforms in the unfiltered file than your screenshot is showing.

If I'm interpreting this correctly-- (1) the flair correct script only gives you 1 corrected read now. If this is the case, we will work on this. We've been working on updating the correction script so if you updated your copy of FLAIR recently, that may explain why the same command gave you different results. (2) You ran your other file of corrected reads through flair-correct and were able to get the multiexonic results that you expect. 
-Alison

**Comment by taylor-shi** [comment]
Your interpretation (2) is correct. Thank you for suggesting the view change on IGV. It turns out when I switch into the "Squished" view, multiexonic transcripts that were hidden on the "Collapsed" view now appear. So there are in fact multiple transcripts that were identified and quantified for the highly expressed genes in both the correct and collapse steps of flair, not just a single corrected read. This was my first time using IGV, I apologize for not realizing my mistake earlier. Thank you so much for your patience and responsiveness.
