### ISSUE TITLE
How to concatenate bed files before flair collapse

### ISSUE THREAD

**Issue by chenxing-zhang** [BrooksLabUCSC/flair#332]
I  run flair-correct for each samples and then obtain corrected.bed for each samples. 
Before i run flair-collapse, i notice that 
"If there are multiple samples to be compared, the flair-corrected read bed files should be concatenated prior to running flair-collapse."
How to concatenate bed files before flair collapse?

**Comment by diekhans** [comment]
BEDs are line-orient files, you can use the cat command.

**Comment by chenxing-zhang** [comment]
> BEDs are line-orient files, you can use the cat command. chenxing-zhang ***@***.***> writes:
> BED 是面向行的文件，可以使用 cat 命令。
> 
> chenxing-zhang ***@***.***>写道：
> […](#)
> I run flair-correct for each samples and then obtain corrected.bed for each samples. Before i run flair-collapse, i notice that "If there are multiple samples to be compared, the flair-corrected read bed files should be concatenated prior to running flair-collapse." How to concatenate bed files before flair collapse? -- Reply to this email directly or view it on GitHub: #332 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>
> 我对每个样本运行 flair-correct，然后为每个样本获取 corrected.bed。
> 在我运行 flair-collapse 之前，我注意到
> “如果要比较多个样本，则应在运行 flair-collapse 之前将经过天赋校正的读取床文件串联起来。”
> 如何在天赋崩溃之前连接床文件？
> 
>  --
> 直接回复此电子邮件或在 GitHub 上查看：
>  #332 
> 您收到此消息是因为您订阅了此线程。
> 
> 消息 ID：***@***.***>


Thanks. The following code is what I used, share it with others:

cat <list of corrected.bed>  | sort -k1,1 -k2,2n -k3,3n > concatenated_corrected.bed

**Comment by chenxing-zhang** [comment]
> BEDs are line-orient files, you can use the cat command. chenxing-zhang ***@***.***> writes:
> […](#)
> I run flair-correct for each samples and then obtain corrected.bed for each samples. Before i run flair-collapse, i notice that "If there are multiple samples to be compared, the flair-corrected read bed files should be concatenated prior to running flair-collapse." How to concatenate bed files before flair collapse? -- Reply to this email directly or view it on GitHub: #332 You are receiving this because you are subscribed to this thread. Message ID: ***@***.***>

Thanks. The following code is what I used, share it with others:

cat <list of corrected.bed>| sort -k1,1 -k2,2n -k3,3n > concatenated_corrected.bed

**Comment by chenxing-zhang** [comment]
Thanks. The following code is what I used, share it with others:

`cat <list of corrected.bed>| sort -k1,1 -k2,2n -k3,3n > concatenated_corrected.bed`

**Comment by cafelton** [comment]
Note that you also need to concatenate your fastq or fasta read files before collapse in a similar manner
