### ISSUE TITLE
Hello, after splitting the BED file by chromosomes, we found that a single chromosome's BED file is 1.03G, which is larger than 1G. Can Flair Collapse currently handle a BED file of 1.03G?

### ISSUE THREAD

**Issue by 991031liurui** [BrooksLabUCSC/flair#334]

**Comment by wdesaintjean** [comment]
I think it's an advice, because FLAIR consume lot of memory. If you have enough RAM on your computer/sever, you can try. On the server of my team, a bed with a size lightly superior to 1Go working well .

**Comment by cafelton** [comment]
Yes, this should be fine. We are working on improving the efficiency of FLAIR. Also see #391 for more info on splitting by chromosome
