### ISSUE TITLE
flair quantify problem error

### ISSUE THREAD

**Issue by wdesaintjean** [BrooksLabUCSC/flair#337]
Hello,

**Copy and paste the exact command you tried to run**

```
cat $iso_fa >> flair_all_iso.fa
flair quantify -r $reads_manifest -i flair_all_iso.fa --sample_id_only 
cat $iso_bed >> flair_all_iso.bed
flair diffSplice -i flair_all_iso.bed -q flair.quantify.counts.tsv --out_dir results_diffsplice
```

**How did you install Flair?**
I use the docker image in a nextflow pipeline:
docker pull brookslab/flair:latest`

**What happened?**

I try to use flair in a nextflow pipeline, but the process fail at the step "flair quantify". Previously, I run flair collapse on each chromosome .bed, as recommended in the repository for big bed input. After that, I combine the output .fa with all isofroms to run flair quantify. But with 8 samples, the program seems to stop after running on 4 samples:

```
 Command error:
  Writing temporary files with prefixes similar to /tmp/tmp12j7ykc1
  Step 1/3. Aligning sample WT12_1, 1/8
  Step 1/3. Aligning sample WT9_2, 2/8
  Step 1/3. Aligning sample WT784_3, 3/8
  Step 1/3. Aligning sample WT13_4, 4/8
  Check /tmp/tmplfsvo041.sam.mm2_stderr.txt file
```
Curiously, flair works perfectly well on test data (4 samples with 1M reads), but return bug when running on the final dataset of 8 sample with 20M reads

Can you help me?

**Comment by 0317miaomiao** [comment]
I have the same error with you, and I try one way to solve it. I guess that this error may happen if you aren't set --temp_dir test.quant.temp, you can try to use it. Here are my command: $ flair quantify -r flair_long.tsv -i flair.collapse.isoforms.fa --temp_dir test.quant.temp --tpm -o test.quantify
After using it, everything is ok. Hope this can solve your problem.

**Comment by 0317miaomiao** [comment]
> Hello,
> 
> **Copy and paste the exact command you tried to run**
> 
> ```
> cat $iso_fa >> flair_all_iso.fa
> flair quantify -r $reads_manifest -i flair_all_iso.fa --sample_id_only 
> cat $iso_bed >> flair_all_iso.bed
> flair diffSplice -i flair_all_iso.bed -q flair.quantify.counts.tsv --out_dir results_diffsplice
> ```
> 
> **How did you install Flair?** I use the docker image in a nextflow pipeline: docker pull brookslab/flair:latest`
> 
> **What happened?**
> 
> I try to use flair in a nextflow pipeline, but the process fail at the step "flair quantify". Previously, I run flair collapse on each chromosome .bed, as recommended in the repository for big bed input. After that, I combine the output .fa with all isofroms to run flair quantify. But with 8 samples, the program seems to stop after running on 4 samples:
> 
> ```
>  Command error:
>   Writing temporary files with prefixes similar to /tmp/tmp12j7ykc1
>   Step 1/3. Aligning sample WT12_1, 1/8
>   Step 1/3. Aligning sample WT9_2, 2/8
>   Step 1/3. Aligning sample WT784_3, 3/8
>   Step 1/3. Aligning sample WT13_4, 4/8
>   Check /tmp/tmplfsvo041.sam.mm2_stderr.txt file
> ```
> 
> Curiously, flair works perfectly well on test data (4 samples with 1M reads), but return bug when running on the final dataset of 8 sample with 20M reads
> 
> Can you help me?
I have the same error with you, and I try one way to solve it. I guess that this error may happen if you aren't set --temp_dir test.quant.temp, you can try to use it. Here are my command: $ flair quantify -r flair_long.tsv -i flair.collapse.isoforms.fa --temp_dir test.quant.temp --tpm -o test.quantify
After using it, everything is ok. Hope this can solve your problem.

**Comment by wdesaintjean** [comment]
It's working with your command line!
I had this problem for one month, I'm very happy to be able to run FLAIR on my datas

Thank you very much for your help.

**Comment by 0317miaomiao** [comment]
> It's working with your command line! I had this problem for one month, I'm very happy to be able to run FLAIR on my datas
> 
> Thank you very much for your help.

Good luck with the research！
