### ISSUE TITLE
FLAIR plot_isoform_usage transcripts flipped

### ISSUE THREAD

**Issue by lilif99** [BrooksLabUCSC/flair#342]
Hi, 
I have been using FLAIR to look at different transcript isoforms of the FCGR2C gene.
My most recent sample, the plot appears to have flipped the transcripts so they are backwards.
Here is an image of the mapped transcripts in IGV: 
![image](https://github.com/BrooksLabUCSC/flair/assets/147354320/578be091-5cbe-40f0-b4af-cd142efd0900)
And here is the resulting plot from FLAIR:
![ENSG00000244682 8_isoforms](https://github.com/BrooksLabUCSC/flair/assets/147354320/9220b6e7-f092-488a-906b-6de59b7078eb)
Is there a reason why the transcripts have flipped orientation? and is there a way to un-flip them?

Many thanks :)

**Comment by wdesaintjean** [comment]
I think your isoforms map on a reverse transcript, his annotation must be from right to left in IGV. Plot_isoform always plot the beginning of the transcript at the left, even if the transcript is reverse.
