### ISSUE TITLE
Flair correct returns blank file

### ISSUE THREAD

**Issue by NatashaJorge** [BrooksLabUCSC/flair#36]
Hello,

I ran flair correct on my Nanopore direct RNA sequencing data. It ran without any problems, but the flair_all_corrected files were blank. Please, can you help me? What did I do wrong? 

Thanks in advance,
Natasha

This is my command line:

python ~/Tools/flair-master/flair.py correct -f Homo_sapiens.GRCh38.95.gtf -c /scr/becherovka/natasha/Alzheimer/hg38.extended.chr_sizes.txt -q second_call.minimap2.sort.bed12 -t 8 -n

This was the last output:

Step 5/5: Correcting Splice Sites: 0it [00:00, ?it/s]0:00, 507387.35it/s]██████████████████████████████████████████████████████████████████████████████████████████████████████████| 47/47 [00:06<00:00,  7.79it/s]

And these are the contents of the output directory:

-rw-r--r-- 1 natasha staff  16M Jul  8 16:02 second_call.minimap2.sort.bed12
-rw-r--r-- 1 natasha staff 411M Jul  8 16:33 Homo_sapiens.GRCh38.95.gff3
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 GL000009.2_known_juncs.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 GL000216.2_known_juncs.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 GL000218.1_known_juncs.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 GL000225.1_known_juncs.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 KI270442.1_known_juncs.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 KI270744.1_known_juncs.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 KI270750.1_known_juncs.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 flair_all_inconsistent.bed
-rw-r--r-- 1 natasha staff    0 Jul  8 16:37 flair_all_corrected.bed
-rw-r--r-- 1 natasha staff 1.1G Jul  8 16:56 Homo_sapiens.GRCh38.95.gtf
-rw-r--r-- 1 natasha staff    0 Jul  8 16:58 flair_all_corrected.psl
-rw-r--r-- 1 natasha staff 2.3M Jul  8 17:06 1_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.9M Jul  8 17:06 2_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.5M Jul  8 17:06 3_known_juncs.bed
-rw-r--r-- 1 natasha staff 956K Jul  8 17:06 4_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.1M Jul  8 17:06 5_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.1M Jul  8 17:06 6_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.2M Jul  8 17:06 7_known_juncs.bed
-rw-r--r-- 1 natasha staff 780K Jul  8 17:06 X_known_juncs.bed
-rw-r--r-- 1 natasha staff 880K Jul  8 17:06 8_known_juncs.bed
-rw-r--r-- 1 natasha staff 900K Jul  8 17:06 9_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.4M Jul  8 17:06 11_known_juncs.bed
-rw-r--r-- 1 natasha staff 928K Jul  8 17:06 10_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.4M Jul  8 17:06 12_known_juncs.bed
-rw-r--r-- 1 natasha staff 437K Jul  8 17:06 13_known_juncs.bed
-rw-r--r-- 1 natasha staff 823K Jul  8 17:06 14_known_juncs.bed
-rw-r--r-- 1 natasha staff 930K Jul  8 17:06 15_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.1M Jul  8 17:06 16_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.5M Jul  8 17:06 17_known_juncs.bed
-rw-r--r-- 1 natasha staff 413K Jul  8 17:06 18_known_juncs.bed
-rw-r--r-- 1 natasha staff 533K Jul  8 17:06 20_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.4M Jul  8 17:06 19_known_juncs.bed
-rw-r--r-- 1 natasha staff  87K Jul  8 17:06 Y_known_juncs.bed
-rw-r--r-- 1 natasha staff 535K Jul  8 17:06 22_known_juncs.bed
-rw-r--r-- 1 natasha staff 282K Jul  8 17:06 21_known_juncs.bed
-rw-r--r-- 1 natasha staff  694 Jul  8 17:06 MT_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.5K Jul  8 17:06 KI270728.1_known_juncs.bed
-rw-r--r-- 1 natasha staff  887 Jul  8 17:06 KI270727.1_known_juncs.bed
-rw-r--r-- 1 natasha staff  193 Jul  8 17:06 GL000194.1_known_juncs.bed
-rw-r--r-- 1 natasha staff  130 Jul  8 17:06 GL000205.2_known_juncs.bed
-rw-r--r-- 1 natasha staff  161 Jul  8 17:06 GL000195.1_known_juncs.bed
-rw-r--r-- 1 natasha staff   99 Jul  8 17:06 KI270733.1_known_juncs.bed
-rw-r--r-- 1 natasha staff   93 Jul  8 17:06 GL000219.1_known_juncs.bed
-rw-r--r-- 1 natasha staff 1.2K Jul  8 17:06 KI270734.1_known_juncs.bed
-rw-r--r-- 1 natasha staff  594 Jul  8 17:06 GL000213.1_known_juncs.bed
-rw-r--r-- 1 natasha staff   99 Jul  8 17:06 GL000220.1_known_juncs.bed
-rw-r--r-- 1 natasha staff   62 Jul  8 17:06 KI270731.1_known_juncs.bed
-rw-r--r-- 1 natasha staff  210 Jul  8 17:06 KI270721.1_known_juncs.bed
-rw-r--r-- 1 natasha staff   62 Jul  8 17:06 KI270726.1_known_juncs.bed
-rw-r--r-- 1 natasha staff 2.0K Jul  8 17:06 KI270711.1_known_juncs.bed
-rw-r--r-- 1 natasha staff   62 Jul  8 17:06 KI270713.1_known_juncs.bed

**Comment by csoulette** [comment]
Hi NatashaJorge,

There is a step in correction where reads aligned to chromosomes not found in annotation files are left out of the analysis. Can you confirm that the chromosome names in your *_known_juncs.bed files and your reads.bed12 (assuming it's  second_call.minimap2.sort.bed12 ) are the same?

-CMS

**Comment by NatashaJorge** [comment]
Dear csoulette,

yes! That was the problem. Fixing the annotation (adding "chr") solved the problem. Thank you!
