### ISSUE TITLE
conda package for flair

### ISSUE THREAD

**Issue by mmiladi** [BrooksLabUCSC/flair#37]
Hello,

Thanks for this great tool. I was wondering if you have already planned or considered providing a conda package for flair? Since conda pacakge can be installed in one line command, by taking care of all dependencies and versioning, It would make the tool more accessible and deployable. 

As I checked, almost all dependencies should be available in bioconda and other channels.

Best,

**Comment by belgravia** [comment]
Hi,

This is a great idea! I've never made a conda package before so I will try making one. It should definitely help more users with installation :)

-Alison

**Comment by belgravia** [comment]
Well I wrote a conda environment! It works on my macos and on centos, so hopefully it will work for other people too. It's in `misc/flair_conda_env.yaml`. There's a link to the installation instructions in the readme. 
-Alison

**Comment by mmiladi** [comment]
Wonderful! Thanks Alison. This now makes it also easier to create a bioconda recipe for flair itself.  Would you like to have this option, i.e. having something like `conda install flair`? 
I can try setting it up.

**Comment by belgravia** [comment]
Hmm... you are welcome to try it, or coach me if you know how to do it. I want to do this but I also don't know enough about how to make one. Would I have to substantially rewrite or restructure flair? It's currently a bunch of separate python scripts bound together by the flair.py wrapper. 

-Alison

**Comment by mmiladi** [comment]
Conda recipes are fairly straightforward. I have now add a PR to the bioconda : https://github.com/bioconda/bioconda-recipes/pull/17245

A missing part is the kerneltree dependency. Since it's not available in conda and seems to be deprecated (?). However the `ncls` is available. But I don't think it would be compatible.

The other (minor) issue is that the main .py file needed to be executable, so I added a patch, Then the flair in conda would need to be invoked directly as `flair.py`   (without python)

Also it might be useful if you could add a license file to the repo for the future releases.

--Milad

**Comment by mmiladi** [comment]
So now FLAIR is available on bioconda!  
The users should be able to `conda install flair`, then `pip install kerneltree`. And start using it out of the box. 
Please feel free to make PR to bioconda in case of upgrades or missing dependencies.

**Comment by Jeltje** [comment]
We have updated bioconda flair with the latest release and will continue to do so. 
Thanks for getting us started @mmiladi !
