### ISSUE TITLE
too few isoforms

### ISSUE THREAD

**Issue by YuLiu-PetersLab** [BrooksLabUCSC/flair#370]
flair was install by conda.

I successfully run through align, correct, and collapse, but the number of isoforms is much smaller than expected (compared to other programs). flair outputs about 2000 isoforms, but other programs give me 10 times more.

Any suggestions?

**I have read the paper (https://doi.org/10.1038/s41467-020-15171-6)  
and the manual (https://flair.readthedocs.io/en/latest/) and I still have a question about**

- align
- correct
- collapse
- quantify
- diffExp
- diffSplice
- something else

**Comment by diekhans** [comment]
It is really not possible to even being to speculate without a
lot more information about the experiment.  Even then, it is a
big effort left to the research to understand the results given
the sensitive vs specificity trade-offs required.

However, FLAIR did very well in specificity in the LRGASP evaluation.
   https://www.nature.com/articles/s41592-024-02298-3

Personally, if I am willing to do more work to look for
something rare in a small number of genes in a larger number of
false-positives, I would go for more transcripts.  If I want
more genes covered with higher confidence, I would want fewer
transcripts.
