### ISSUE TITLE
path to Minimap2

### ISSUE THREAD

**Issue by taylor-shi** [BrooksLabUCSC/flair#39]
Hi,
I am running into an issue in flair quantify; it is asking me to provide the executable path for Minimap2. I have provided it as you can see in my code below (also tried software/flair/minimap2/) but I keep receiving the same error. I did not have to specify the minimap2 path for flair collapse, which has ran successfully consecutive times. Do you have any insight into this issue?

python software/flair/flair.py quantify -m software/flair/minimap2 --tpm -r 2019-7-8_3CL/SHSY5Y/SHSY5Y_reads_manifest.txt -o 2019-7-8_3CL/SHSY5Y/trcl_VA/flair/counts_matrix.tsv -i 2019-7-8_3CL/SHSY5Y/trcl_VA/flair/3.flair.collpase.isoforms.fa

Thank you,
Taylor

**Comment by belgravia** [comment]
Can you write what the error you're getting is? If you didn't need to specify it for collapse to work, then it should be in your path and you won't need to specify it for quantify. Also check to see that the isoform fasta file isn't empty.
-Alison

**Comment by taylor-shi** [comment]
Hi Alison,

Thanks for the suggestion, it turns out that the fasta file name I was calling to the program had a small typo so the file I was calling was non-existent. If you are still curious, the error message I was receiving was "Possible minimap2 error, specify executable path with -m"

**Comment by belgravia** [comment]
That's what I was thinking, good to have it confirmed. Glad that that worked :)
