### ISSUE TITLE
overlapping annotations

### ISSUE THREAD

**Issue by dandepledge** [BrooksLabUCSC/flair#40]
Hi,

I'm trying to get a handle on how FLAIR handles overlapping annotations.

For instance, if I have two RNAs that share the same 3' termination but have different 5' start sites, would these be counted as distinct isoforms?

**Comment by belgravia** [comment]
Yes, FLAIR would consider two isoforms distinct as long as there is a splice site, transcription start site, or transcription end site that is different. There should not be any duplicate isoforms after the flair-collapse step.

You may want to note that isoforms that contain the exact same splice junctions and differ only by the TSS/TES will have the same isoform base name with the addition of a number at the end to give them unique names (e.g. ENST00000323963.9, ENST00000323963.9-1, ENST00000323963.9-2...). You can control the TSS/TES for a particular splice junction chain that FLAIR finds using `--max_ends`, `-w`, `-i`, and/or `-n` arguments for flair-collapse. Hope this helps.

-Alison

**Comment by dandepledge** [comment]
Thank you very much for this.

Unfortunately I am currently stuck at the 'correct' step. I am only trying
to correct ~1000 read so do not expect this to take long. However when I
run the command I get the following

python /gpfs/share/apps/flair/1.3/flair.py correct -n -q
CHX.flair.aligned.bed -c dumas.txt -g dumas.fasta -j chx_junctions.bed -o
chx
Step 2/5: Processing additional junction file chx_junctions.bed ...
Step 5/5: Correcting Splice Sites:   0%|

                                              | 0/1 [00:00<?, ?it/s]

I'm not sure what's going on at the missing steps (1,3,4) but it just hangs
indefinitely at 0% at Step 5 (I have left this for hours).

My chx_junctions.bed file contains only four lines. My chromosome id is
dumas.fasta but I still get the same issue if I change it to chrdumas in
all relevant files.

The chromosome sizes file just looks like this (one line)
chrdumas \t 124844

I'd appreciate any thoughts you have on this

Dan

**Comment by dandepledge** [comment]
And just as an update. I have the same problem using the test datasets mentioned on the Github page. The problem persists regardless of whether I supply a gtf or junctions file

**Comment by csoulette** [comment]
Hi @dandepledge,

Since you are using such a small dataset, the messages for your "missing" steps are probably just taking so little time that you don't actually see them come up in your terminal window.

As for the hanging, I would double check that all of the requirements for correct are installed. This includes kerneltree.

Last, i'm trying to hunt down the annotation file for the organism you are using. Are you using NC_001348 reference sequence? If so, is there a publicly available annotation you are able to link or share? Thanks.

Thanks~
-CMS

**Comment by dandepledge** [comment]
Hi - you are absolutely correct about the missing messages. I can see them when I run larger datasets or if I pipe the processing information to an outfile.

I have resolved the hanging issue by installing the latest version of flair but now I am getting a different error... 

  File "/gpfs/home/depled01/flair/bin/ssCorrect.py", line 416, in <module>
    main()
  File "/gpfs/home/depled01/flair/bin/ssCorrect.py", line 398, in main
    with open(os.path.join(tempDir, "%s_inconsistent.bed" % chrom),'rb') as fd:
IOError: [Errno 2] No such file or directory: '/gpfs/scratch/depled01/FLAIR/test/tmp_7d39fe4a-163f-4978-af31-122cb4ca2eb4/chrX_inconsistent.bed'
Correction command did not exit with success status

This error is generated when running the correct command on the test dataset but I also get the same error when I run on my own dataset. 

To answer your other question - you have the correct reference sequence but the only public annotation is the one provided on genbank and this is missing lots of important detail (such as splicing) which is why I am trying to use FLAIR (transcript isoform discovery and then quantification)

**Comment by dandepledge** [comment]
update: I see others on this forum have experienced similar errors and everything traces back to kerneltree. I have installed this now as a local module (rather than relying on the local HPC install) and the correction step now works correctly on both the test dataset and my own.

I'm going to finish going through the rest of the FLAIR pipeline and if everything looks good then I will close this thread.

Thanks for your help and for making this great tool!
