### ISSUE TITLE
Decreased number of isoform when comparing multiple samples

### ISSUE THREAD

**Issue by martynakgajos** [BrooksLabUCSC/flair#41]
When I run the flair collapse and quantification step for 3 samples:
```
python $flair collapse -r $base".fastq"  -q $base".corrected_all_corrected.psl" -g $genome -m $minimap -o $base -f $annotation -sam $samtools
echo -e $base"\t"$base"\t"$base"\t"$base".fastq" > "manifest.tsv"
python3 $flair quantify -i $base".isoforms.fa" -r "manifest.tsv" -m $minimap
```
I get the following number of isoforms for a gene (in this case TEAD3):
> sample1: 6 (in quantification: 154 reads in total)
> sample2: 7 (in quantification: 123 reads in total)
> sample3: 13 (in quantification: 430 reads in total)

I would like to compare the samples, therefore I concatenated the flair-corrected read psl files, concatenated the manifest files and gave raw read files as a comma-separated list for -r.
`python $flair collapse -r $base1".fastq,"$base2".fastq",$base3".fastq" -q "concatenated_corrected.psl" -g $genome -m $minimap -f $annotation -sam $samtools`

In this case, flair.collapse.isoforms.gtf does not contain any exons for the gene and consequently there are no isoforms detected or quantified for this gene.

How should I proceed in this case? 
Thanks!

**Comment by belgravia** [comment]
Hi,

Thanks for the details. There's a bug here somewhere...
1. Did you get any error messages? 
2. Can you run with the option `--keep_intermediate` so you can see at which step the failure is occurring? You may also want to specify the directory of intermediate files (`--temp_dir`) to somewhere more convenient for you to look at. It would be nice to know if there are empty/badly formatted files early on in the pipeline that are responsible for the failure.

-Alison

**Comment by martynakgajos** [comment]
1. I didn't get any failure message.
2. In general, I do get results, however many isoforms detected for a given sample are absent in the results if I analyze together multiple samples.

**Comment by belgravia** [comment]
Ok, it's possible what's happening is that with additional data, you are getting a greater amount of firstpass isoforms (you can verify this by running flair-collapse with `--keep_intermediate` and you can specify a `--temp_dir` if you like), which would mean _more ambiguity_ when assigning reads to isoforms, which causes fewer reads to be aligning with mapping quality>0, which in turn results in fewer isoforms that pass the coverage threshold of 3. 

You could try running collapse with `--quality 0` to allow the primary alignments of reads that align equally well to multiple isoforms to be counted. This could potentially add more noise to the dataset, but I expect it should prevent the problem of more reads -> fewer final isoforms.

-Alison
