### ISSUE TITLE
junctions_from_sam crashes with ValueError: invalid literal for int() with base 10: '11=' error

### ISSUE THREAD

**Issue by NatashaJorge** [BrooksLabUCSC/flair#43]
Hello!

thanks for creating Flair!! It looks like a really great tool! I am trying to use Illumina PE reads to correct Nanopore DRS reads. So the first thing I did was trying to run junctions_from sam.py but it died with the error below:

   Traceback (most recent call last):
  File "/homes/brauerei/natasha/Tools/flair-master/bin/junctions_from_sam.py", line 820, in <module>
    if __name__ == "__main__": main()
  File "/homes/brauerei/natasha/Tools/flair-master/bin/junctions_from_sam.py", line 438, in main
    downstr_len = int(n_split.pop().rstrip("M"))
ValueError: invalid literal for int() with base 10: '11='

My command line is:
$ python ~/Tools/flair-master/bin/junctions_from_sam.py -s UU_Library_X09_S44_mapped_sorted_unique.sam -n UU_Library_X09_S44_mapped_sorted_unique.sj

I am inside a conda environment with Python 3.7.2

The log is this:
Parsing sam/bam file
Not supporting softclipping, yet e.g., 4S21=
Expecting a junction read: 92=
Expecting a junction read: 92=
Expecting a junction read: 150=
Expecting a junction read: 24=1X15=1X8=1X4=1X5=1X42=1X47=
Expecting a junction read: 23=1X15=1X8=1X4=2X4=1X41=2X47=
Expecting a junction read: 23=1X15=1X8=1X4=1X5=1X42=1X47=
Expecting a junction read: 22=1X15=1X8=1X4=1X5=1X42=1X49=
Expecting a junction read: 22=1X15=1X8=1X4=1X5=1X42=1X49=
Expecting a junction read: 22=1X15=1X8=1X4=1X5=1X42=1X49=
Expecting a junction read: 1=1X149=
Expecting a junction read: 151=
Expecting a junction read: 151=
Expecting a junction read: 4=1X15=1X8=1X4=1X5=1X42=1X16=1X50=
Expecting a junction read: 3=2X15=1X8=1X4=1X5=1X42=1X67=
Expecting a junction read: 2=1X15=1X8=1X4=1X5=1X42=1X68=
Expecting a junction read: 15=1X8=1X4=1X5=1X42=1X71=
Expecting a junction read: 15=1X8=1X4=1X5=1X42=1X71=
Expecting a junction read: 15=1X8=1X4=1X5=1X42=1X72=
Expecting a junction read: 151=
Expecting a junction read: 151=
Expecting a junction read: 1=1X42=1X5=1X84=1X15=
Expecting a junction read: 42=1X67=1X22=1X15=
Expecting a junction read: 37=1X108=1X1=
Expecting a junction read: 37=1X85=1X22=1X4=
Expecting a junction read: 37=1X110=
Expecting a junction read: 34=1X116=
Expecting a junction read: 30=1X66=
Expecting a junction read: 30=1X75=
Expecting a junction read: 25=1X123=
Expecting a junction read: 25=1X125=
Expecting a junction read: 25=1X124=
Expecting a junction read: 25=1X124=
Expecting a junction read: 24=1X111=
Expecting a junction read: 24=1X111=
Expecting a junction read: 150=
Expecting a junction read: 1X22=1X122=
Expecting a junction read: 1X22=1X122=
Expecting a junction read: 23=1X113=
Expecting a junction read: 23=1X113=
Expecting a junction read: 16=1X134=
Expecting a junction read: 149=
Expecting a junction read: 149=
Expecting a junction read: 1X15=1X24=1X79=
Expecting a junction read: 1X15=1X24=1X79=
Expecting a junction read: 14=1X50=1X10=1X73=
Expecting a junction read: 14=1X135=
Expecting a junction read: 10=1X139=
Expecting a junction read: 10=1X140=
Expecting a junction read: 10=1X139=
Expecting a junction read: 43=1X107=
Expecting a junction read: 8=1X142=
Expecting a junction read: 7=1X142=
Expecting a junction read: 7=1X118=
Expecting a junction read: 7=1X118=
Expecting a junction read: 4=1X145=
Expecting a junction read: 4=1X145=
Expecting a junction read: 2=1X147=
Expecting a junction read: 1=1X149=
Expecting a junction read: 1=1X37=1X64=1X17=1X27=
Expecting a junction read: 151=
Expecting a junction read: 66=1X82=
Expecting a junction read: 151=
Expecting a junction read: 151=
Expecting a junction read: 151=
Expecting a junction read: 143=
Expecting a junction read: 143=
Expecting a junction read: 151=
Expecting a junction read: 111=
Expecting a junction read: 111=
Expecting a junction read: 151=
Expecting a junction read: 64=1X86=
Expecting a junction read: 151=
Expecting a junction read: 131=
Expecting a junction read: 131=
Expecting a junction read: 143=1X7=
Expecting a junction read: 4=1X11=1X3=1X10=1X1=1X104=1X3=1X7=
Expecting a junction read: 150=
Expecting a junction read: 151=
Expecting a junction read: 151=
Expecting a junction read: 149=
Expecting a junction read: 150=
Expecting a junction read: 148=
Expecting a junction read: 150=
Expecting a junction read: 148=
Expecting a junction read: 150=
Expecting a junction read: 134=1X5=1X1=1X5=
Expecting a junction read: 148=
Expecting a junction read: 101=
Expecting a junction read: 101=
Expecting a junction read: 148=
Expecting a junction read: 148=
Expecting a junction read: 150=
Not supporting insertions, yet e.g., 148=1I1=1X
Expecting a junction read: 144=1X3=1X
Expecting a junction read: 138=
Expecting a junction read: 138=
Traceback (most recent call last):
  File "/homes/brauerei/natasha/Tools/flair-master/bin/junctions_from_sam.py", line 820, in <module>
    if __name__ == "__main__": main()
  File "/homes/brauerei/natasha/Tools/flair-master/bin/junctions_from_sam.py", line 438, in main
    downstr_len = int(n_split.pop().rstrip("M"))
ValueError: invalid literal for int() with base 10: '11='

I also tried with the sorted bam file but got the same error. Please, can you help me? 

best wishes,
Natasha

**Comment by belgravia** [comment]
Hi Natasha,

Thanks for the helpful report. It looks like your aligner uses `=`/`X` for match and mismatch, and `junctions_from_sam.py` was expected `M` for matches. I can probably update the script to account for other kinds of formats.  Could you tell me the aligner and command you used to generate the sam? That would help.

-Alison

**Comment by NatashaJorge** [comment]
Hi Alison,

yes, you're right. I colleague of mine aligned the reads using segemehl3. Please find below an example of the bam file.

best wishes,
Natasha

NB551369:69:HVCGNBGXB:4:12608:8057:9667 2:N:0:AGTCAACA+AGATCTCG	2201	chr1	11053	1	4S21=	*	0	0	CCCGGGCGCCGGGCTGGGGCGGGGG	////<E/////////EEA//EA/EA	HI:i:0	NH:i:1	NM:i:0	MD:Z:21	XC:Z:chr10,26622800,-,105,47,3,1	XP:Z:chr22_KI270733v1_random,134152,+,1,79,0,1	XX:i:80	XY:i:104	XI:i:1	XH:i:1	XJ:i:3	RG:Z:A1	YZ:Z:8
NB551369:69:HVCGNBGXB:3:22602:20354:3355 2:N:0:AGTCAACA+AGATCTCG	147	chr1	13311	60	92=	=	13311	92	CCTGGATCTGAGCCCTGGTGGAGGTCAAAGCCACCTTTGGTTCTGCCATTGCTGCTGTGTGGAAGTTCACTCCTGCCTTTTCCTTTCCCTAG	EEE<EEEEEEEE/E<E<EE/EE/EEEEAAEEEAA<EAEEEEEEEEE/AEEEEEEEEAEEEEEEEEEEAEEEEEEEEEE/EEEEEEEEAAAAA	HI:i:0	NH:i:1	NM:i:0	MD:Z:92	RG:Z:A1	YZ:Z:0

**Comment by belgravia** [comment]
I took a look at the segemehl documentation and it looks like it can output extended cigar strings. So now I've changed the script to look for `=` and `X` now as `M` as well and consider `N` as introns to work for files like yours. Please update FLAIR and try running the junctions from sam command again!
-Alison

**Comment by NatashaJorge** [comment]
Hi Alison!

thanks for the reply and all your effort! It's working great now! Thank you very much!

best,
Natasha
