### ISSUE TITLE
Minor bug

### ISSUE THREAD

**Issue by hastreiter** [BrooksLabUCSC/flair#49]
Hi,

just found another small thing. When aligning reads to first-pass isoform reference including salmon, the samtools call fails since it cannot open the output file.
Fixed the issue for me by replacing stdout=open(alignout+'.mapped.sam')): with  stdout=open(alignout+'.mapped.sam', "w")):  (Line 277)

Best,

**Comment by belgravia** [comment]
Thanks for finding this. The fix is implemented in the latest commit :)
