### ISSUE TITLE
Flair Align no bed file

### ISSUE THREAD

**Issue by jchang97** [BrooksLabUCSC/flair#5]
Hi there,

I was using the recommended default commands for flair align (shown below) but it only generates sam and bam files, and not bed files. 

Would you kindly be able to let me know how I can get these bed files?

Thank you

python "/media/Programmes/flair/flair.py" align -r "/media/BRCA12D.FASTA" -g "/media/GRCh38.genome.fa"

**Comment by belgravia** [comment]
`flair.py align` should give a bed file automatically, which means either an error occurred or the run didn't finish. If you have the sorted and indexed `bam` file, you can just run the last command to generate the bedfile like so: `python pathtoflair/bin/bam2Bed12.py -i sorted.bam > sorted.bed`
