### ISSUE TITLE
License and License file missing

### ISSUE THREAD

**Issue by bgruening** [BrooksLabUCSC/flair#51]
Hi all,

we wanted to use flair and package it for further distribution, unfortunately, it is not clear under which license flair is developed.

I would be great if you could clarify this and maybe add a [license file](https://help.github.com/en/articles/adding-a-license-to-a-repository).

Thanks!
Bjoern

**Comment by anbrooks** [comment]
Thank you for pointing this out, Bjoern. We are currently working on adding license information.

**Comment by bgruening** [comment]
Thanks! We are creating a bioconda package: https://github.com/bioconda/bioconda-recipes/pull/17245

**Comment by belgravia** [comment]
Thank you for creating the bioconda package! :)

We have added a [license](https://github.com/BrooksLabUCSC/flair/blob/master/LICENSE.txt) for flair. 

Separate question, will the conda package need to be updated with each release of flair? 

Thanks again,
Alison

**Comment by bgruening** [comment]
Yes. But if you put out a new tagged release here on github, we have a bot that helps to update the recipe. So it becomes like this:

1. create a new github release
2. after a few hours there is a new PR on the bioconda-recipes repo
3. review and merge this bioconda PR for changed dependencies and such
4. new bioconda package and Biocontainer is available

Thanks for the License!
Bjoern
