### ISSUE TITLE
conda install flair errors

### ISSUE THREAD

**Issue by q1134269149** [BrooksLabUCSC/flair#54]
Hi, 
I used conda install flair by code: conda install -c bioconda flair, but reported the following errors:
"""
(flair_cor) [qinh@node29 ~]$ conda install -c bioconda flair
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Solving environment: \
Found conflicts! Looking for incompatible packages.                                                                                                                            failed

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Package sqlite conflicts for:
python=3.6.5 -> sqlite[version='>=3.22.0,<4.0a0|>=3.23.1,<4.0a0']
Package pysam conflicts for:
flair -> pysam
Package xz conflicts for:
python=3.6.5 -> xz[version='>=5.2.3,<6.0a0']
Package minimap2 conflicts for:
flair -> minimap2
Package pip conflicts for:
python=3.6.5 -> pip
Package libstdcxx-ng conflicts for:
python=3.6.5 -> libstdcxx-ng[version='>=7.2.0']
Package bedtools conflicts for:
flair -> bedtools
Package samtools conflicts for:
flair -> samtools
Package bioconductor-drimseq conflicts for:
flair -> bioconductor-drimseq
Package seaborn conflicts for:
flair -> seaborn
Package bioconductor-stager conflicts for:
flair -> bioconductor-stager
Package pybedtools conflicts for:
flair -> pybedtools
Package ncls conflicts for:
flair -> ncls
Package tk conflicts for:
python=3.6.5 -> tk[version='>=8.6.7,<8.7.0a0']
Package r-qqman conflicts for:
flair -> r-qqman
Package r-ggplot2 conflicts for:
flair -> r-ggplot2=2.2.1
Package numpy conflicts for:
flair -> numpy
Package pandas conflicts for:
flair -> pandas
Package tqdm conflicts for:
flair -> tqdm
Package ncurses conflicts for:
python=3.6.5 -> ncurses[version='>=6.0,<7.0a0']
Package matplotlib conflicts for:
flair -> matplotlib
Package libgcc-ng conflicts for:
python=3.6.5 -> libgcc-ng[version='>=7.2.0']
Package rpy2 conflicts for:
flair -> rpy2
Package libffi conflicts for:
python=3.6.5 -> libffi[version='>=3.2.1,<4.0a0']
Package readline conflicts for:
python=3.6.5 -> readline[version='>=7.0,<8.0a0']
Package bioconductor-deseq2 conflicts for:
flair -> bioconductor-deseq2
Package zlib conflicts for:
python=3.6.5 -> zlib[version='>=1.2.11,<1.3.0a0']
Package openssl conflicts for:
python=3.6.5 -> openssl[version='>=1.0.2o,<1.0.3a']
Package intervaltree conflicts for:
flair -> intervaltree
"""
I tried various versions of python, such as 2.7/3.6.5/3.6.9/3.7, all versions report this mistake. 
In the previous several installations, I've installed the packages of Cython, intervaltree, kerneltree, tqdm, pybedtools, pysam-v0.15, minimap2 and bedtools, but still gave same mistakes.
Could you give me some advice? Thanks. 

And I had installed   in previous installations,

**Comment by q1134269149** [comment]
> Hi,
> I used conda install flair by code: conda install -c bioconda flair, but reported the following errors:
> """
> (flair_cor) [qinh@node29 ~]$ conda install -c bioconda flair
> Collecting package metadata (repodata.json): done
> Solving environment: failed with initial frozen solve. Retrying with flexible solve.
> Solving environment: 
> Found conflicts! Looking for incompatible packages. failed
> 
> UnsatisfiableError: The following specifications were found to be incompatible with each other:
> 
> Package sqlite conflicts for:
> python=3.6.5 -> sqlite[version='>=3.22.0,<4.0a0|>=3.23.1,<4.0a0']
> Package pysam conflicts for:
> flair -> pysam
> Package xz conflicts for:
> python=3.6.5 -> xz[version='>=5.2.3,<6.0a0']
> Package minimap2 conflicts for:
> flair -> minimap2
> Package pip conflicts for:
> python=3.6.5 -> pip
> Package libstdcxx-ng conflicts for:
> python=3.6.5 -> libstdcxx-ng[version='>=7.2.0']
> Package bedtools conflicts for:
> flair -> bedtools
> Package samtools conflicts for:
> flair -> samtools
> Package bioconductor-drimseq conflicts for:
> flair -> bioconductor-drimseq
> Package seaborn conflicts for:
> flair -> seaborn
> Package bioconductor-stager conflicts for:
> flair -> bioconductor-stager
> Package pybedtools conflicts for:
> flair -> pybedtools
> Package ncls conflicts for:
> flair -> ncls
> Package tk conflicts for:
> python=3.6.5 -> tk[version='>=8.6.7,<8.7.0a0']
> Package r-qqman conflicts for:
> flair -> r-qqman
> Package r-ggplot2 conflicts for:
> flair -> r-ggplot2=2.2.1
> Package numpy conflicts for:
> flair -> numpy
> Package pandas conflicts for:
> flair -> pandas
> Package tqdm conflicts for:
> flair -> tqdm
> Package ncurses conflicts for:
> python=3.6.5 -> ncurses[version='>=6.0,<7.0a0']
> Package matplotlib conflicts for:
> flair -> matplotlib
> Package libgcc-ng conflicts for:
> python=3.6.5 -> libgcc-ng[version='>=7.2.0']
> Package rpy2 conflicts for:
> flair -> rpy2
> Package libffi conflicts for:
> python=3.6.5 -> libffi[version='>=3.2.1,<4.0a0']
> Package readline conflicts for:
> python=3.6.5 -> readline[version='>=7.0,<8.0a0']
> Package bioconductor-deseq2 conflicts for:
> flair -> bioconductor-deseq2
> Package zlib conflicts for:
> python=3.6.5 -> zlib[version='>=1.2.11,<1.3.0a0']
> Package openssl conflicts for:
> python=3.6.5 -> openssl[version='>=1.0.2o,<1.0.3a']
> Package intervaltree conflicts for:
> flair -> intervaltree
> """
> I tried various versions of python, such as 2.7/3.6.5/3.6.9/3.7, all versions report this mistake.
> In the previous several installations, I've installed the packages of Cython, intervaltree, kerneltree, tqdm, pybedtools, pysam-v0.15, minimap2 and bedtools, but still gave same mistakes.
> Could you give me some advice? Thanks.
> 
> And I had installed in previous installations,

**Comment by azharmajeed** [comment]
Hi I am facing the same issue while installing flair through conda. Did you find any alternatives for installing it?

**Comment by whosnothungry** [comment]
same issue here

**Comment by hayux** [comment]
I have the same issue, then I tried to uninstall anaconda and re-install it again, but the same problem occurs
