### ISSUE TITLE
run diffSplice error

### ISSUE THREAD

**Issue by q1134269149** [BrooksLabUCSC/flair#56]
**Hi,
when I ran diffSplice module, I got the error as following:**
"""
_nohup: ignoring input
Traceback (most recent call last):
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 315, in <module>
    main()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 302, in main
    geneID = re.search('(ENSG[^\.]+|chr\S+)',iso).group(1)
AttributeError: 'NoneType' object has no attribute 'group'_
 """
**And the file of "flair.diffSplice.es.events.tsv" in the results is empty.
Could you give me some advice? 
Thanks.**

**Comment by q1134269149** [comment]
The flair.collapse.isoforms.psl.bed file (ori: Nanopore direct RNA sequencing data) are the following:
"""
1       5667473 5668259 5aed510e-c515-4150-b462-0b1712b0fb5f_Basecall_1D_template_1:5667000     1000    +       5667473 5668259 0,0,0   1       786,    0,
1       23294549        23294836        076139e5-316f-4328-aed7-c8dcd3fe8685_Basecall_1D_template_1:23294000    1000    +       23294549        23294836        0,0,0   1       287,    0,
1       24614912        24615374        8c39a2a9-6baf-4db8-aff5-8de759dfd7a7_Basecall_1D_template_1:24614000    1000    -       24614912        24615374        0,0,0   1       462,    0,
1       28592165        28592707        be09d758-f332-4aac-b1ae-e868a2831e11_Basecall_1D_template_1:28592000    1000    +       28592165        28592707        0,0,0   1       542,    0,
1       3015472 3015811 6cfcd917-c7ef-4c86-8770-18d907e4c20f_Basecall_1D_template_1:3015000     1000    +       3015472 3015811 0,0,0   1       339,    0,
1       4269007 4269445 1a36c24c-86e7-4576-93ac-8bba6411dd18_1:4269000  1000    -       4269007 4269445 0,0,0   1       438,    0,
1       4824435 4824623 1465a9fb-1bdb-41f6-bbf0-4ed620cbfeac_1:4824000  1000    -       4824435 4824623 0,0,0   1       188,    0,

"""

**Comment by belgravia** [comment]
For calling exon skipping events, we group the isoforms by their genes. To do so, we use the annotation to group the isoforms into genes. 

You will need to rename and then (possibly) rerun flair-quantify with the renamed isoforms. To rename the isoforms, you can use the script `identify_gene_iso.py`, which takes your isoforms, a genome annotation, and an output file name as arguments. Your isoform names will be formatted with the gene name like so:  `isoname_genename` as opposed to just the isoname you have now. You then need to rename the isoforms in your counts file. You could match the new names to the original names and then use that the alter the names in your count_matrix.tsv, rerun flair-quantify with the new isoform file, or I could whip up a script if you'd like.

Sorry it's a little inconvenient. The naming happens automatically if you provide a gtf to flair-collapse.  

I will add a note to the Readme saying if users wish to run diffsplice and other downstream modules, providing the gtf in flair-collapse is ideal. I will also work on making the way the exon skipping events are called to be more accepting of different naming formats, although this will probably take longer.

Hope that helps. Let me know how it goes.
-Alison

**Comment by q1134269149** [comment]
> For calling exon skipping events, we group the isoforms by their genes. To do so, we use the annotation to group the isoforms into genes.
> 
> You will need to rename and then (possibly) rerun flair-quantify with the renamed isoforms. To rename the isoforms, you can use the script `identify_gene_iso.py`, which takes your isoforms, a genome annotation, and an output file name as arguments. Your isoform names will be formatted with the gene name like so: `isoname_genename` as opposed to just the isoname you have now. You then need to rename the isoforms in your counts file. You could match the new names to the original names and then use that the alter the names in your count_matrix.tsv, rerun flair-quantify with the new isoform file, or I could whip up a script if you'd like.
> 
> Sorry it's a little inconvenient. The naming happens automatically if you provide a gtf to flair-collapse.
> 
> I will add a note to the Readme saying if users wish to run diffsplice and other downstream modules, providing the gtf in flair-collapse is ideal. I will also work on making the way the exon skipping events are called to be more accepting of different naming formats, although this will probably take longer.
> 
> Hope that helps. Let me know how it goes.
> -Alison

Hi,
Thank you very much. Because the process is quite complicated, can you  whip up a script for me for this. 
Thanks!

**Comment by q1134269149** [comment]
> For calling exon skipping events, we group the isoforms by their genes. To do so, we use the annotation to group the isoforms into genes.
> 
> You will need to rename and then (possibly) rerun flair-quantify with the renamed isoforms. To rename the isoforms, you can use the script `identify_gene_iso.py`, which takes your isoforms, a genome annotation, and an output file name as arguments. Your isoform names will be formatted with the gene name like so: `isoname_genename` as opposed to just the isoname you have now. You then need to rename the isoforms in your counts file. You could match the new names to the original names and then use that the alter the names in your count_matrix.tsv, rerun flair-quantify with the new isoform file, or I could whip up a script if you'd like.
> 
> Sorry it's a little inconvenient. The naming happens automatically if you provide a gtf to flair-collapse.
> 
> I will add a note to the Readme saying if users wish to run diffsplice and other downstream modules, providing the gtf in flair-collapse is ideal. I will also work on making the way the exon skipping events are called to be more accepting of different naming formats, although this will probably take longer.
> 
> Hope that helps. Let me know how it goes.
> -Alison

**Hi,
When I ran flair-collapse before, I  have already used .gtf annotation files instead of second-generation junction files. And all of the following module is done bsed on the output from flair_collapse using .gtf annotation. The codes as following:**
"""
##flair collapse the concatenated psl
python $soft/flair.py collapse **-g** $genomefa **-f** $genomegtf --keep_intermediate --temp_dir $tempdir **-t** 8 **-r** $LR/col0_1qf.fastq,$LR/col0_2qf.fastq,$LR/col0_3qf.fastq,$LR/fip37_1qf.fastq,$LR/fip37_2qf.fastq,$LR/fip37_3qf.fastq **-q** $collapse_mergedir/col0_fip37_123_concatenated_corrected.psl **-o** cf_123_concatenated_flair.collapse
""" 

**And when I ran flair_diffSplice, except for calling exon skipping events, the other works, for example .alt3.events, .alt5.events and .ir.events,  are OK. The following files are outputs:**
"""
_-rw-rw-r-- 1 shihan shihan  109740 Sep 26 10:08 cf_123_flair.diffSplice.alt3.events.quant.tsv
-rw-rw-r-- 1 shihan shihan   83341 Sep 26 10:08 cf_123_flair.diffSplice.alt5.events.quant.tsv
-rw-rw-r-- 1 shihan shihan     139 Sep 26 10:14 cf_123_flair.diffSplice.es.events.quant.tsv
-rw-rw-r-- 1 shihan shihan       0 Sep 26 10:14 cf_123_flair.diffSplice.es.events.tsv
-rw-rw-r-- 1 shihan shihan 1673375 Sep 26 10:14 cf_123_flair.diffSplice.ir.events.quant.tsv_
"""
**A part of _cf_123_flair.diffSplice.alt3.events.quant.tsv_ as following:**
"""
**feature_id      coordinate      col01_wt_batch1 col02_wt_batch1 col03_wt_batch1 fip371_mut1_batch1      fip372_mut1_batch1      fip373_mut1_batch1      isoform_ids**
inclusion_1:421633      1:421633-421719_1:421633-421734 0.0     0.0     2.0     1.0     1.0     2.0     0e04d253-4e61-4878-a947-77c562cf72b3
exclusion_1:421633      1:421633-421719_1:421633-421734 17.0    31.0    47.0    33.0    30.0    18.0    **transcript:AT1G02205.2**,e5610bcc-aba9-4c7e-a231-2e96305fb487_Basecall_1D-1_template,a19c26a5-c2bc-4722-be7d-661202768614_Basecall_1D_template,93bf220d-237d-4118-9259-e380d9d7edaa
inclusion_1:631858      1:631858-631927_1:631858-632008 0.0     0.0     1.0     3.0     6.0     8.0     **transcript:AT1G02850.2-1**
exclusion_1:631858      1:631858-631927_1:631858-632008 4.0     0.0     0.0     20.0    17.0    39.0    **transcript:AT1G02850.1**-1,a15133df-f2e8-49d5-8829-2da798955028_Basecall_1D_template,49eb4a64-d3d5-46a5-8081-83929feddd24
inclusion_1:1054200     1:1054200-1054284_1:1054200-1054662     1.0     3.0     4.0     0.0     4.0     2.0     0c9a3bc0-1f64-4c63-aa1b-83b94562e8fc_Basecall_1D_template
exclusion_1:1054200     1:1054200-1054284_1:1054200-1054662     16.0    18.0    23.0    25.0    17.0    25.0    **transcript:AT1G04080.1,transcript:AT1G04080.4-1**,fd2cbdcb-1c33-4eab-9faf-9d0eaeaf4033-1
inclusion_1:1399322     1:1399322-1399422_1:1399322-1399569     0.0     1.0     8.0     8.0     3.0     6.0     df32f63f-f537-4f02-9c55-cef0e8a813fb_Basecall_1D_template
"""

**Comment by belgravia** [comment]
Ok, thank you for pointing out that you did supply the gtf. I see that your names are formatted `iso_gene` so there is no need to rename.

The exon skipping calling was written using a graphical approach clustering the isoforms by gene. I have rewritten it such that the gene name doesn't matter (it looks by chromosome now) so please try running flair-diffSplice again with your original data and let me know if there's an error at es_as.py again. 

Side note, I see that some of the isoform names were matched with annotated ones (e.g. AT1G02859.2) but were any genes properly identified for your isoforms? The `chromosome:coordinate` format is used when a gene isn't identified.

-Alison

**Comment by q1134269149** [comment]
> Ok, thank you for pointing out that you did supply the gtf. I see that your names are formatted `iso_gene` so there is no need to rename.
> 
> The exon skipping calling was written using a graphical approach clustering the isoforms by gene. I have rewritten it such that the gene name doesn't matter (it looks by chromosome now) so please try running flair-diffSplice again with your original data and let me know if there's an error at es_as.py again.
> 
> Side note, I see that some of the isoform names were matched with annotated ones (e.g. AT1G02859.2) but were any genes properly identified for your isoforms? The `chromosome:coordinate` format is used when a gene isn't identified.
> 
> -Alison

**Hi,
I ran the program again today and still reported it wrong. The reault of flair.diffSplice.es.events.quant.tsv is also 0 byte. The following is the contents of the log:**
>>>
_nohup: ignoring input
Traceback (most recent call last):
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 315, in <module>
    main()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 311, in main
    gobj.buildGraphv2()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 86, in buildGraphv2
    j1 = (self.spliceSites[previousDonor], self.spliceSites[acceptor])_
_KeyError: 21746499_
<<<

**In addition, I just want to get the numbers of events and the corresponding gene id of exon-skip, intron_retention, alt_3prime, alt_5prime, mult_exon_skip, mutex_exons etc. in each sample respectively.
Could you give some advices? Thanks!**

**Comment by q1134269149** [comment]
> Ok, I think I have fixed the keyerror. Please try running diffsplice again, thanks for your patience.
> 
> As for your second question, from your successful output of alt 3prime/5prime/IR event files there should be enough information to give you the number of events per sample.
> 
> > feature_id coordinate col01_wt_batch1 col02_wt_batch1 col03_wt_batch1 fip371_mut1_batch1 fip372_mut1_batch1 fip373_mut1_batch1 isoform_ids
> > inclusion_1:421633 1:421633-421719_1:421633-421734 0.0 0.0 2.0 1.0 1.0 2.0 0e04d253-4e61-4878-a947-77c562cf72b3
> > exclusion_1:421633 1:421633-421719_1:421633-421734 17.0 31.0 47.0 33.0 30.0 18.0 transcript:AT1G02205.2,e5610bcc-aba9-4c7e-a231-2e96305fb487_Basecall_1D-1_template,a19c26a5-c2bc-4722-be7d-661202768614_Basecall_1D_template,93bf220d-237d-4118-9259-e380d9d7edaa
> 
> Each event has two lines, one for the counts each of your samples for the inclusion event and another line for the counts of the alternative exclusion event. So if you want the number of alt 3prime events for the sample col01_wt_batch1, you could check how many counts in column three of your outputfile are nonzero. You could get your gene ids matching the transcript id's in the diffsplice output with your counts matrix ids. Hope that is helpful.
> 
> -Alison

**Hi,
I ran the es_as.py after update, but still got the same error as follow:**
>>>
_nohup: ignoring input
Traceback (most recent call last):
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 315, in <module>
    main()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 311, in main
    gobj.buildGraphv2()
  File "/home/shihan/qinhang/softs_pkgs/flair/bin/es_as.py", line 86, in buildGraphv2
    j1 = (self.spliceSites[previousDonor], self.spliceSites[acceptor])
KeyError: 98024_
<<<
Can you give me some advice?
Thanks!
-hqin

**Comment by jchang97** [comment]
Hi Alison, 

I just wanted to clarify with you regarding the response you gave below - so if there is one event but classified into two sub-events (inclusion and exclusion of the same region), are both sub-events counted for the total number of events? I'm just a bit confused about this - e.g. for exon skipping, my initial thought would be to only count the 'exclusion' events from the es files and leave the 'inclusion' ones? Please let me know what your thoughts are. 

Thank you!

`Each event has two lines, one for the counts each of your samples for the inclusion event and another line for the counts of the alternative exclusion event. So if you want the number of alt 3prime events for the sample col01_wt_batch1, you could check how many counts in column three of your outputfile are nonzero. You could get your gene ids matching the transcript id's in the diffsplice output with your counts matrix ids. Hope that is helpful.`
