### ISSUE TITLE
mark_productivity.py producing no valid transcripts (?)

### ISSUE THREAD

**Issue by shaniAmare** [BrooksLabUCSC/flair#6]
Thank you for the great tool... I'm running `mark_productivity.py` on `flair.py` generated `*isoforms.psl` files. I keep on getting the following message:
`Traceback (most recent call last):
  File "../../../SourceFiles/flair-master/bin/mark_productivity.py", line 228, in <module>
sys.stderr.write('Unproductive proportion estimate ' + str(unproductive / float(valid_transcripts)) + '\n')
ZeroDivisionError: float division by zero`

I believe the script doesn't identify that there are any valid transcripts? But I see that there are transcripts beginning with `ATG` when I look at the `isoforms.fa` files of the predicted isoforms. 

Can you please help me by explaining what's going on? I might be probably missing something here!  One thing I did when running the `flair-collapse` module is not filtering the `firstpass.sam` files based on quality to generate `firstpass.q1.sam` because I wanted to look at all the entries first. So I used `firstpass.sam` to generate the final `.psl` files that I used as input for `mark_productivity.py`

My script for running `mark_productivity.py`:
`for file in ../*.isoforms.psl;`
`do`
`out=${file%%.psl}; out=${out##../};`
`python3 ../../../SourceFiles/flair-master/bin/mark_productivity.py \`
`${file} \` 
`../../../references/GRCh38_ucsc.gtf \`
`../../../references/human38_sequins_cal_merged.fa \`
`> ${out}.productivity.psl;`
`done`

Thanks a lot.

**Comment by shaniAmare** [comment]
Thanks for your reply @belgravia ... So I did two things...

1.  Made the `genome.fa` a oneliner. Do you think it would be good if this is reminded to the users at the beginning of the `mark_productivity.py` script.

2. Replaced the `genome.fa` chromosome names to be identical to those of `gtf` file. I previously changed the chromosome names in the `.fa` file to be `chrZ'\t'rest of the FASTA header` since the `gtf` file had `chrZ`. it worked with the rest of your pipeline. But do you think it would be good to remind users at the beginning of the `flair` pipeline to check whether the chromosome names of `.fa` and `.gtf` file are **identical** (with maybe a simple example, else someone like me would think just having the matching string as a part of the FASTA header would be sufficient - and I also know someone who gave up using the pipeline because they couldn't figure out where the error is coming from).

And the `mark_productivity.py` started running and produced the `.psl` files. However, all of the `.psl` files had 2 as the last value (lncRNA?).  According to your experience, could that happen (i.e. have no productive isoforms)?  I'm tempted to run the `flair` pipeline again with the edited reference file. I will keep you updated in the progress. But for the moment I can assure you that it worked after changing the chromosome names.

**Comment by belgravia** [comment]
When you say oneliner, what do you mean? The script expects fasta format with headers starting with `>` and line/lines of sequence following that.

Yes, I have added to the readme that the names specified in the `gtf` and `fa` need to agree. I would say that the genome fasta is only used in one of my scripts, `psl_to_sequence.py`, in the `flair.py collapse` module so you would at most need to rerun that step again, but not the whole pipeline. 

I will also add that if chromosomes in your `gtf` are formatted like `chr1` chr2` and chromosomes in your fasta look like `>chr1 other_stuff` `>chr2 more_stuff` then you shouldn't experience any weird naming issues with `flair.py collapse`, and that there is no need to rerun that. I fixed that in a previous issue.

I have pushed a newer version of the mark_productivity script that handles chromosome names the way I do in the `collapse` module, like in the example above.

As for the lncRNA issue, have you checked to see if `start_codon` is a field in your `gtf`? It's possible that no annotated start codons are in your `gtf`, hence causing all your isoforms to not have an ORF identified. Maybe it would be helpful for me if you sent me the url from where you downloaded the `gtf` from.

**Comment by shaniAmare** [comment]
Sorry I confused you... Oneliner means I have converted the multi-line FASTA file to be one-line file. e.g. 
`>chr1`
`AABBBBCCCDDDEE`
`FFFEEEEDDDDGGGG`
.....
......

was converted to

`>chr1`
`AABBBBCCCDDDEEFFFEEEEDDDDGGGG........`

I do have a start_codon option in my `gtf` file. I checked it earlier and forgot to mention that in my previous message. I downloaded it from the `UCSC` database according to the steps in https://www.biostars.org/p/174331/#233414

Thanks,
Shani.

**Comment by belgravia** [comment]
I see! Having all the sequence on one line should, in my limited experience, help speed up reading in the file, which is good. It shouldn't be necessary for the scripts to work though.

Again, what is likely happening is that none of your isoforms overlap an annotated start codon and/or the start codon chromosome positions do not correspond to an `ATG` in the genomic sequence because of an indexing error. I just wanted to make sure the gtf you used was 1-indexed, which it is. So if the `gtf` is not at fault then my next guess would be the genome sequence. 

To help me debug, can you send me one line of your isoform `psl` that you expect to have an annotated start codon in it? I assume you are working with hg38. It would also be helpful for you to send me where you downloaded your genome from.

**Comment by shaniAmare** [comment]
Hi @belgravia ...

So I got a `.productivity.psl` file after running `mark_productivity.py` on the `.isoforms.psl` file newly generated with compatible `reference.fa` and `reference.gtf` files. It looked as if the `reference.fa` was the culprit. I now see rows marked `0`, `1` or `2`  in the `.productivity.psl` file... Great!

However at the end of the run of `mark_productivity.py`, I get the following error:
`Traceback (most recent call last):`
  `File "../../SourceFiles/flair-master/bin/mark_productivity.py", line 184, in <module>
    pos = find_tss_pos(entry, tss)`
  `File "../../SourceFiles/flair-master/bin/mark_productivity.py", line 125, in find_tss_pos
    for pos in tss[chrom][strand]:`
`KeyError: '+'`

Thought I should let you know.

Cheers,
Shani.

**Comment by belgravia** [comment]
Ok that's good to hear that you've got the annotation and genome synced up! 

This error means that the file didn't run all the way through, and is telling me that there is a chromosome where all the transcription start sites are all on the same strand. I have added an extra check in the code to make sure there are start codons on that chromosome strand. Please try using the newer script. It should give you more complete results.
-Alison

**Comment by shaniAmare** [comment]
Yup, Now I can run the pipeline `align` > `correct` > `collapse` > `mark_duplicates.py` > `intron-retention.py` without an error - Just for future reference, It is safe to have identical chromosome names in both `reference.fa` file and the `reference.gtf` file.

Thanks @belgravia for all the help! I think it's OK close this issue  :)
