### ISSUE TITLE
flair align with -n flag runs minimap2 twice

### ISSUE THREAD

**Issue by mjblow** [BrooksLabUCSC/flair#61]
Hi, when I run flair.py align with the -n flag, it seems to run minimap2 twice (first with RNA specific params, then with cDNA params, overwriting the first alignment file). I'm running from the docker image, but also note same behaviour from the the cloned git repo. Is the logic for calling minimap2 correct?
Thanks!

**Comment by belgravia** [comment]
Thanks for finding this, the logic is wrong for native rna data. It was running it once with the native rna parameters and then a second time with the default parameters. I've fixed it in the most recent commit.
