### ISSUE TITLE
psl generated with a block size of -1

### ISSUE THREAD

**Issue by diekhans** [BrooksLabUCSC/flair#62]
I am running flair correct + collapse on ONT cDNAs and it is generated some PSLs with
the last block size in the list being -1.

See attached file.  This is from a very large run, so it will take some time to get the sample reads, but if you see anything in the code, I can try rerunning it.

[bad.psl.gz](https://github.com/BrooksLabUCSC/flair/files/3710475/bad.psl.gz)

**Comment by belgravia** [comment]
I haven't seen this particular error crop up yet and I'm not sure which piece of code is introducing it. 
Do you know if those reads have the -1 after the correct step already? 
-Alison

**Comment by diekhans** [comment]
I am not sure where the error occurs, as the intermediate files were discarded.
I will put together a limited test case.

**Comment by diekhans** [comment]
My latest run didn't produce this problem.  Perhaps because of using different collapse options or the bug was fixed by some other change.
