### ISSUE TITLE
cannot find minimap2 with conda environment

### ISSUE THREAD

**Issue by yejilee-biostat** [BrooksLabUCSC/flair#69]
Hello,

 I am not sure this is the right place to ask this kind of question - if not, please let me know!
 I am trying to use FLAIR under conda environment (it is installed and activated without any problem after following the instruction. However, when I try to run FLAIR align , it keeps saying

"Possible minimap2 error, specify executable path with -m"

 my $PATH have the path to minimap2, (just typing minimap2 on the command line run the program without any error or warning) and I have also tried with "-m <PATH_TO_minimap2>", neither have solved my problem. Could you help me on this? Thanks a lot!

--yeji

**Comment by belgravia** [comment]
Just to be extra sure, can you double check that all of your files (genome fasta, your reads fasta) are openable and not empty? I apologize because that error message is very general; it shows up if something went wrong with the minimap2 command, which typically results from a bad minimap2 path or bad paths to the other files.

Thanks for your patience!
-Alison

**Comment by basicallydean** [comment]
I can confirm that I ran into the same error with the second most recent commit of flair. Haven't tried flair with the most recent updates. 

Checked that the fastqs/as are legitimate and they are all openable and not empty. Running minimap2 standalone was fine so I'm guessing it's something within FLAIR align

**Comment by fbemm** [comment]
Same here. I have minimap2 in PATH and it's executable.

**Comment by fbemm** [comment]
The direct RNA call has a syntax problem I think:

This:

```
                if args.n:
                        if subprocess.call([args.m, '-ax', 'splice', '-uf', '-k14', '-t', args.t, \
                        '--secondary=no', args.g, args.r], stdout=open(args.o+'.sam', 'w')):
                                sys.exit(1)
                elif subprocess.call([args.m, '-ax', 'splice', '-t', args.t, '--secondary=no', args.g]+args.r, \
                                stdout=open(args.o+'.sam', 'w')):
                        sys.exit(1)
```

Needs to be this:

```
                if args.n:
                        if subprocess.call([args.m, '-ax', 'splice', '-uf', '-k14', '-t', args.t, \
                        '--secondary=no', args.g]+args.r, stdout=open(args.o+'.sam', 'w')):
                                sys.exit(1)
                elif subprocess.call([args.m, '-ax', 'splice', '-t', args.t, '--secondary=no', args.g]+args.r, \
                                stdout=open(args.o+'.sam', 'w')):
                        sys.exit(1)
```

`args.g, args.r],` --> `args.g]+args.r,`

**Comment by yejilee-biostat** [comment]
Thanks for all replies! my input files are not empty and I can run minimap2 itself without any problem, too. 
 I will try why @fbemm suggests ( Thanks, @fbemm ).

**Comment by belgravia** [comment]
@fbemm found it. The way flair received the reads arguments was changed recently and I forgot to change it for the -n argument as well. I've fixed it in the most recent commit. Hopefully this is what fixes everyone's issues.

**Comment by yejilee-biostat** [comment]
> @fbemm found it. The way flair received the reads arguments was changed recently and I forgot to change it for the -n argument as well. I've fixed it in the most recent commit. Hopefully this is what fixes everyone's issues.

Thank you, @belgravia - I will try it again with the updated one - and if everything looks OK, then I will close this issue.

**Comment by yejilee-biostat** [comment]
It seems now FLAIR can find minimap2 without any problem, so I will close this issue. Thanks again.
