### ISSUE TITLE
flair.collapse.isoforms.fa sequence

### ISSUE THREAD

**Issue by robinycfang** [BrooksLabUCSC/flair#70]
Hello there,

I used flair collapse mode to generate flair.collapse.isoforms.fa file, and am going to use the sequence provided in this fasta to do more downstream analysis. Just wondering how the sequence in this fasta is generated: is it copped from the reference genome or is it an assembly of consensus sequence from the bam file?

Thanks!

**Comment by belgravia** [comment]
The fasta file is generated from the genome sequence. 

If you think it would be helpful, I could add an option to flair-collapse that would output the read IDs that support each isoform. You could then generate the consensus isoform sequences using the supporting read sequences for each isoform.
-Alison

**Comment by robinycfang** [comment]
Hey Alison,

Thanks for the reply. This idea actually came to my mind too. It would be really helpful if we can know what specific reads are assigned to each isoform, so that we can calculate or average some features over all reads for a particular isoform (e.g., mutation calling). Look forward to seeing this coming out in the next patch.

YC

**Comment by belgravia** [comment]
Thanks for your patience. You'll have to rerun collapse with the `--generate_map` option. The `--generate_map` option will only output your isoform -> read mappings if you _don't_ use salmon to quantify, since the way salmon assigns counts to isoforms is not given to the user according to my cursory understanding of salmon. Alternatively, if you ran collapse previously with `--keep_intermediate` you can find the relevant `.sam` file and run `sam_to_map.py`. Let me know if you run into any issues.

-Alison

**Comment by robinycfang** [comment]
Hey Alison,

Thanks for the update. This option of outputting reads is definitely very helpful, as we often want to analyze each transcript in-depth, which requires assigned reads. On another note, for the transcript sequence in flair.collapse.isoforms.fa, is it oriented from 5' to 3' (i.e., + strand), and I assume if the functional codes are on the reverse strand, we should reverse the sequence manually?

YC

**Comment by rsalz** [comment]
@belgravia is it on purpose that you still haven't reverse complimented the reverse strand transcripts? Having all transcripts in + strand orientation regardless of strandedness isn't so helpful for downstream analysis, which is generally what people will want to do with a fasta file

**Comment by belgravia** [comment]
There was no particular purpose, so I have changed the output fasta to report the plus orientation for transcripts now regardless of strand. 

Thanks for your patience with my very delayed response!!

-Alison
