### ISSUE TITLE
FLAIR collapse issue

### ISSUE THREAD

**Issue by basicallydean** [BrooksLabUCSC/flair#73]
Hello, 

I am running FLAIR collapse with the following commands (within the conda env) 

python ~/Bioinformatics-Programs/flair/flair.py collapse -t 8 -g mm10.fa -r ./RC-EXT_1-2-3_dRNA_Nuc_GV_rawreads.fastq -q ./RC_EXT_1-2-3_dRNA_Nuc_GV_all_corrected.psl -f /GENCODE/vm23/gencode-gene.vM23.comprehensive.annotation.gtf -e comprehensive -o RC_EXT_1-2-3_dRNA_Nuc_GV

The psl files were concatenated from the FLAIR correct output, I have 6 samples total
The fastq reads were also concatenated 

The program terminates with this 

Annotated ends extracted from GTF
Read data extracted
Single-exon genes grouped, collapsing
Filtering isoforms
usage: script.py collapsed.psl (nosubset/default/comprehensive/ginormous) filtered.psl [tolerance]

Chromosomes names are consistent across all files. No previous errors arose from the align-correct stages. 

Any insight would be appreciated.

Cheers
Dean

**Comment by belgravia** [comment]
Quite uselessly, it was not taking anything in for -e unless it 'default'. I have fixed this with the most recent commit. 

Thanks for your patience!  Also thanks for submitting this issue.
-Alison

**Comment by basicallydean** [comment]
Thank you Alison, that fixed the problem - now closing this issue.
