### ISSUE TITLE
list index out of range in flair correct

### ISSUE THREAD

**Issue by NatashaJorge** [BrooksLabUCSC/flair#75]
Hello!

when I run:

$ python flair/flair.py correct -c chr_sizes.tsv -q n1.AD.sort.bed12 -j X09.tophat.bed_junctions.bed -t 8 -o n1.X09.corrected -f Homo_sapiens.GRCh38.95.chr.fixed.gtf -g hg38.extended.fa

I get the following error:

Traceback (most recent call last):
  File "/homes/brauerei/natasha/Tools/flair2/flair/bin/bed_to_psl.py", line 14, in <module>
    chromsizes[line[0]] = line[1]
IndexError: list index out of range

I've created the flair_env conda environment using the yaml file in misc and mapped the nanopore reads with minimap2 and the illumina reads with tophat. I created the junctions file with the junctions_from_sam.py . Please, why am I getting this error?

Thanks in advance!

**Comment by belgravia** [comment]
This has to do with how your chrom.sizes file is formatted. It needs to be tab-delimited with chromosome name in the first column and the number of bases in the second column. 

Option 1: You could reformat your chr_sizes.tsv file. If you think the formatting is correct and you're still getting that error, please attach the file here so I can debug/review.

Option 2: The chrom sizes file is not required for flair-correct. You could omit that argument such that your corrected reads will be output only as bed. The corrected reads bed can be supplied to flair-collapse with `-q`. This would also circumvent your current error.

-Alison

**Comment by NatashaJorge** [comment]
Leaving the chr_sizes.tsv out worked. 

Thanks!! :-)
