### ISSUE TITLE
quantification dependent on sample

### ISSUE THREAD

**Issue by mvheetve** [BrooksLabUCSC/flair#78]
I'm exploring FLAIR for the first time and so far I have two questions:

1) I ran through the flair align, correct and collapse steps for two samples (two fastq files, exact same number of reads). 
sample1.isoforms.fa gave 5 isoforms, sample2.isoforms.fa gave 3. These files contained one isoforms in common. 

When I run flair quantify, the quantification results are different depending on the use of either sample1.isoforms.fa or sample2.isoforms.fa as input. Results for the common isoform shown here:

$python RNAseq/flair/flair.py quantify -r manifest.tsv -i sample1.isoforms.fa
ids	sample1_conditionA_batch1	sample2_conditionB_batch1
ENST00000278616_ENSG00000149311	160.0	172.0

$python RNAseq/flair/flair.py quantify -r manifest.tsv -i sample2.isoforms.fa
ids	sample1_conditionA_batch1	sample2_conditionB_batch1
ENST00000278616_ENSG00000149311	48.0	65.0

Could you explain why the numbers and even ratio's are so different? 

2) As I said X.isoforms.fa gave me 5 and 3 isoforms (one overlapping). The count table provided by flair quantify shows counts (>0) for both samples, even though most of these isoforms are sample specific according to flair collapse. Is this because the isoform is present in one sample and in the other sample the isoform is part of a longer isoform? Or how do I explain this? 

For example, this isoform is unique to sample1.isoforms.fa, but flair quantify count table contains:

ids	sample1_conditionA_batch1	sample2_conditionB_batch1
4a9fc352-898e-4daa-9b99-fc3cb33447ce_ENSG00000149311	42.0	42.0

Many thanks in advance! 
mvheetve

**Comment by belgravia** [comment]
1. I hope you are expecting 5 or 3 isoforms. Unless you were doing targeted sequencing of sorts or have very few reads to work with, I'd expect flair to produce more isoforms. 

Yes you will get different flair-quantify results because you are quantifying two different references. What we recommend is that you combine your two samples (say, prior to the collapse step you can concatenate the two *_corrected.bed/psl files together) and run flair-collapse on all your corrected reads. You should also specify all your read fastq files to flair-collapse `-r`. Then I would rerun quantify with the flair-collapse isoforms.fa that was produced with all your reads to do your sample-specific quantification. 

We can take a closer look at your data and the ratios once you have done the flair collapse and quantify runs properly.

-Alison

**Comment by mvheetve** [comment]
Hej Alison,

Yes, this is targeted sequencing on one gene and only a subset of the data to minimize computing time in order to get acquainted with flair. 

Thank you for the answer, I'll have a look and if I find any other irregularities you'll hear from me. 
-mvheetve

**Comment by halfrt** [comment]
> 
> 
>     1. I hope you are expecting 5 or 3 isoforms. Unless you were doing targeted sequencing of sorts or have very few reads to work with, I'd expect flair to produce more isoforms.
> 
> 
> Yes you will get different flair-quantify results because you are quantifying two different references. What we recommend is that you combine your two samples (say, prior to the collapse step you can concatenate the two *_corrected.bed/psl files together) and run flair-collapse on all your corrected reads. You should also specify all your read fastq files to flair-collapse `-r`. Then I would rerun quantify with the flair-collapse isoforms.fa that was produced with all your reads to do your sample-specific quantification.
> 
> We can take a closer look at your data and the ratios once you have done the flair collapse and quantify runs properly.
> 
> -Alison


Just a quick question on the flair-collapse isoforms.fa created by each sample - should you combine these isoforms.fa files prior to running samples in the flair-quantify step as well?

**Comment by mvheetve** [comment]
If you combine all your bed files after `flair correct ` and run `flair collapse` with all fastq files, you only get one isoform.fa files (containing collapsed isoforms from the corrected reads for all your samples). This is then used as input for `flair quantify` and you specify which data (fastqs) and metadata (batch and condition) belong to each sample in the manifest tsv file. You then end up with a count matrix which contains the isoform counts for every sample.
