### ISSUE TITLE
predictProductivity.py error 

### ISSUE THREAD

**Issue by ozgegizlenci** [BrooksLabUCSC/flair#79]
Hello, 

When I try to run a productivity test with predictProductivity script, I end up with the error stated below:

```
Traceback (most recent call last):
  File "bin/predictProductivity.py", line 353, in <module>
    main()
  File "bin/predictProductivity.py", line 319, in main
    isoformObjs = getSeqs(bed, genome)
  File "bin/predictProductivity.py", line 140, in getSeqs
    read,seq  = entry.split()
ValueError: too many values to unpack (expected 2)
```

Here is the command I used: 

`ssub -c32 --mem=120G python3 bin/predictProductivity.py -i flair.isoforms.merged-ONT10.psl -g gencode.vM21.annotation.gtf -f GRCm38.primary_assembly.genome.fa --longestORF > productivity.ONT-10.bed`

It didn't happened in the previous version of flair. As far as I underston, there is problem with not matching number of columns etc. 

I wonder if you could help me to resolve the problem.

Thank you in advance.

**Comment by belgravia** [comment]
Which version of bedtools are you using and are you running the most updated version of predictProductivity.py?

Just so we're on the same page. We've been addressing some bedtools version-related issues that have been cropping up.
-Alison

**Comment by ozgegizlenci** [comment]
Dear Alison,

Thank you for the quick response. 
I run one of the command with both bedtools v2.28.0 and bedtools v2.29.0, I received the same error:
```

Traceback (most recent call last):
  File "bin/predictProductivity.py", line 353, in <module>
    main()
  File "bin/predictProductivity.py", line 319, in main
    isoformObjs = getSeqs(bed, genome)
  File "bin/predictProductivity.py", line 140, in getSeqs
    read,seq  = entry.split()
ValueError: too many values to unpack (expected 2)
```
Thanks for the help.

**Comment by ozgegizlenci** [comment]
Hello,

I wanted to give an update for the error I was dealing with. I used isoforms file coming from the collapse command for this code below: 
`
python3 bin/predictProductivity.py -i ONT-10-aligned-unfiltered/ONT10.barcoded.merged.isoforms.psl -g gencode.vM21.annotation.gtf -f GRCm38.primary_assembly.genome2upper.fa --longestORF > productivity.ONT-10.merged.bed`

This time the error changed to this one: 

```
	Traceback (most recent call last):
	  File "bin/predictProductivity.py", line 353, in <module>
	    main()
	  File "bin/predictProductivity.py", line 319, in main
	    isoformObjs = getSeqs(bed, genome)
	  File "bin/predictProductivity.py", line 137, in getSeqs
	    bt.sequence(fi=genome, tab=True, s=True, split=True, name=True)
	  File "/bi/home/gizlenco/.local/lib/python3.7/site-packages/pybedtools/bedtool.py", line 840, in decorated
	    result = method(self, *args, **kwargs)
	  File "/bi/home/gizlenco/.local/lib/python3.7/site-packages/pybedtools/bedtool.py", line 345, in wrapped
	    decode_output=decode_output,
	  File "/bi/home/gizlenco/.local/lib/python3.7/site-packages/pybedtools/helpers.py", line 434, in call_bedtools
	    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
	pybedtools.helpers.BEDToolsError: 
	Command was:
	
	bedtools getfasta -tab -split -s -name -fo /tmp/pybedtools.31gp4z41.tmp -fi GRCm38.primary_assembly.genome2upper.fa -bed ONT-10-aligned-unfiltered/ONT10.barcoded.merged.isoforms.psl.bed
	
	Error message was:
	Error: cannot construct subsequence with negative offset or length < 1
```
I used the reference genome converted to uppercase in case the error was persisting; 

`awk '/^>/ {print($0)}; /^[^>]/ {print(toupper($0))}' GRCm38.primary_assembly.genome2.fa>GRCm38.primary_assembly.genome2upper.fa`

however, it did not help either.

Thank you

**Comment by belgravia** [comment]
Hi,

Can you try running pslCheck (can obtain from KentUtils or Anaconda) to make sure that there isn't something misformatted about the psl? 

I assume the error message is occurring because there is an entry that contains a start field that is a negative number or contains a block size that is < 1. If you can check that this is the case and send me the bad lines, that would be helpful. Else, this may be a bedtools issue so I may have to call for @csoulette's expertise.

-Alison

**Comment by csoulette** [comment]
Hi @ozgegizlenci,

It looks like this issue may have been related to issue #84 . I would recommend updating, redoing collapse and proceeding with productivity prediction. Also, regarding the initial issue, I would recommend double checking that there are no spaces in your isoform names.

Thanks~

-CMS

**Comment by ozgegizlenci** [comment]
Hello,

Thank you for your answers. 

I tried both of the recommended solutions. 
1. I run pslCheck in the psl file (the ones after collapse step) and here are the command and output:

`pslCheck -targetSizes=../chromsizes.tsv ONT10.barcode1.isoform`

alignment size (3032) doesn't match counts (2988)
checked: 76647 failed: 75185 errors: 297869

2. As CMS suggested, I updated and re-run the collapse step. Then I ran another pslCheck for one of the barcodes, here is my command:

`pslCheck -targetSizes=chromsizes.tsv -pass=passedONT10b8 -fail=failedONT10b8 ONT-10-analysis-updated/ONT10-new.barcode8.isoforms.psl`

alignment size (1312) doesn't match counts (1314)
checked: 23863 failed: 23326 errors: 101526
I am not sure if I am using correct options with pslCheck. If you could give me an example how to observe a pslcheck output, that would be great.

I attached the pass and fail files as Alison requested.

[failedONT10b8.txt](https://github.com/BrooksLabUCSC/flair/files/3985357/failedONT10b8.txt)
[passedONT10b8.txt](https://github.com/BrooksLabUCSC/flair/files/3985358/passedONT10b8.txt)

I also checked the psl files which were generated by the correct option and they seem to be okay.

`pslCheck -targetSizes=chromsizes.tsv ONT-10-analysis-updated/corrected-8-ONT10-new.flair_all_corrected.psl`

checked: 829471 failed: 0 errors: 0

I will be very happy if you could help me to understand what is the problem with my psl files and why I get many errors after collapse step. 
Thank you very much.

Ozge

**Comment by JuanSilva89** [comment]
Hello,

FLAIR has been a great tool for my analysis of Nanopore sequencing. However, I am having a similar error when running predictProductivity.py as shown below:

(flair_env) [js3274@cbsulogin bin]$ python predictProductivity.py -i flair.collapse.isoforms.bed -g ref_genome.gtf -f ref_genome.fa --firstTIS > productivity.bed
Traceback (most recent call last):
  File "predictProductivity.py", line 372, in <module>
    main()
  File "predictProductivity.py", line 338, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "predictProductivity.py", line 267, in predict
    o.orfs.append(["NGO", exons[0][0], exons[0][0], 0, 0])
IndexError: list index out of range

The annotation was downloaded from NCBI as a gff3 file and converted to gtf using AGAT.
The annotation was converted from gtf into psl using gtf_to_psl.py. Then, I used pslCheck.py and found multiple errors "alignment size doesn't match counts (0)". Unfortunately I do not know how to proceed to fix this issue. Could you please give me some advise?

**Comment by Jeltje** [comment]
Hello, I'm working on the predictProductivity code. If this is still an issue with the latest version of the code (see my comment in #155 ), please let me know and I will try to debug.

**Comment by Jeltje** [comment]
Please reopen this ticket if you still have issues.
