### ISSUE TITLE
Promoter BED for mice

### ISSUE THREAD

**Issue by peterkilfeather** [BrooksLabUCSC/flair#80]
Hi, this is a great package! Thank you

I am interested in using some direct RNA data we have of mouse brain RNA to identify novel isoforms. I saw the option to use a promoter BED file to check for full-length transcripts. Can I ask how you recommend obtaining this? 

So far, I have used the UCSC table browser to produce a BED file of 1000bp upstream of every GENCODE annotated transcript. I can report back on the outcome soon, hopefully

**Comment by belgravia** [comment]
Hi,

We used the regions from the gm12878
from [this paper
](https://scholar.google.com/scholar_lookup?title=Discovery%20and%20characterization%20of%20chromatin%20states%20for%20systematic%20annotation%20of%20the%20human%20genome&journal=Nat.%20Biotechnol.&volume=28&pages=817-825&publication_year=2010&author=Ernst%2CJ&author=Kellis%2CM), which identified promoter chromatin states using ChromHMM on ChIP-Seq data of 9 factors. The tracks are on the browser [here](http://genome.ucsc.edu/cgi-bin/hgTracks?hgsid=779644091_n6VqgODX1Ahn2H4Uxd49dGMjPrjV&hgt_=1574725221&db=hg38&tsCurTab=simpleTab&hgt_tsDelRow=&hgt_tsAddRow=&hgt_tsPage=&tsSimple=h3k4me3&hgt_tSearch=search&tsName=&tsDescr=&tsGroup=Any&tsType=Any). I found a [similar track in mice](http://genome.ucsc.edu/cgi-bin/hgTracks?hgsid=779644091_n6VqgODX1Ahn2H4Uxd49dGMjPrjV&hgt_=1574725610&db=mm10&tsCurTab=simpleTab&hgt_tsDelRow=&hgt_tsAddRow=&hgt_tsPage=0&tsSimple=h3k4me3+encode+chromatin+state&hgt_tSearch=search&tsName=&tsDescr=&tsGroup=Any&tsType=Any) too.

Also, I will add that you should have the table browser produced a bed that is 1000 bp upstream of the annotated start and also ~10 bp downstream of the start. FLAIR does a bedtools-intersect of the valid start regions in the promoter bed file with the corrected reads.

You can then concatenate the bed files you obtained from the chromhmm track + around annotated starts to supply as the promoter bed file.

-Alison
