### ISSUE TITLE
How to classify four AS events of Alt5, Alt3, ES and IR from the results of flair collapse? 

### ISSUE THREAD

**Issue by q1134269149** [BrooksLabUCSC/flair#82]
Hi,
I used the flair collapse to get the results of high-confidence isoforms. But I do not know how to classify the AS events of  Alt5, Alt3, ES and IR. I'd like to know whether flair has scripts to do this or  have any good advice. Thanks.
hqin

**Comment by belgravia** [comment]
Yes, those 4 AS events are what the flair diffsplice module call. 

Please look to the readme for some documentation on that module. It will call the splicing events and quantify the splicing events. An example output table is shown in the readme. 

With the output tables, you can run counts-based statistical tests (like Fisher's test, or DESeq2, or DRIMSeq) to obtain a pvalue for each splicing event. There are plans to automate the statistical testing for this module eventually but it has not been implemented yet.

**Comment by q1134269149** [comment]
> Yes, those 4 AS events are what the flair diffsplice module call.
> 
> Please look to the readme for some documentation on that module. It will call the splicing events and quantify the splicing events. An example output table is shown in the readme.
> 
> With the output tables, you can run counts-based statistical tests (like Fisher's test, or DESeq2, or DRIMSeq) to obtain a pvalue for each splicing event. There are plans to automate the statistical testing for this module eventually but it has not been implemented yet.

Thanks for your quick reply, that would be really helpful!
