### ISSUE TITLE
exon start coordinate > end coordinate after collapse

### ISSUE THREAD

**Issue by defendant602** [BrooksLabUCSC/flair#84]
Hello,

After I run the flair collapse step on my ONT cDNA data, in the output gtf file I have found some "false" exons of which the start coordinate is larger than the end coordinate, typically one base larger.

For example:
chrX	FLAIR	transcript	1273789	1294327	.	+	.	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49";
chrX	FLAIR	exon	1273790	1274842	.	+	1742	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"; exon_number "0";
chrX	FLAIR	exon	1282678	1282779	.	+	1742	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"; exon_number "1";
chrX	FLAIR	exon	1285778	1285920	.	+	1742	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"; exon_number "2";
chrX	FLAIR	exon	1288519	1288642	.	+	1742	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"; exon_number "3";
chrX	FLAIR	exon	1288759	1288888	.	+	1742	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"; exon_number "4";
chrX	FLAIR	exon	1290337	1290509	.	+	1742	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"; exon_number "5";
**chrX	FLAIR	exon	**1294328	1294327**	.	+	1742	gene_id "ENSG00000198223.16"; transcript_id "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"; exon_number "6";**

I used reference annotation to do flair correct and here was my collapse command:
python flair.py collapse -g hg38.fa -f hg38.gtf -r full_length_reads.fasta -q flair_all_corrected.psl -s 2 -t 20

Is there any way to fix this problem?

**Comment by belgravia** [comment]
Hi,

This problem should be sorted out, and I'm not sure what's causing the problem so I'll need your assistance debugging. Can you send me lines in the flair_all_corrected.psl and the flair isoforms psl for the read/isoform corresponding to "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49"? Perhaps that will help me determine at what step does the read's coordinates get messed up. 

-Alison

**Comment by defendant602** [comment]
No problem. I grep lines corresponding to "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49" from the files you mentioned, and this is the result:

>flair_all_corrected.psl
1742	0	0	0	0	0	6	18813	+	107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49;16	1742	0	1742	chrX	156040895  1273789	1294344	7	1053,102,143,124,130,173,17,	   0,1053,1155,1298,1422,1552,1725,	1273789,1282677,1285777,1288518,1288758,1290336,1294327,

>flair.collapse.isoforms.psl
1742	0	0	0	0	0	6	18813	+	107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49_ENSG00000198223.16	1742	0	1742	chr156040895	1273789	1294327	7	1053,102,143,124,130,173,0,	0,1053,1155,1298,1422,1552,1725,	1273789,1282677,1285777,1288518,1288758,1290336,1294327,

Alternatively you can see it in the attached zip file.
[psl.zip](https://github.com/BrooksLabUCSC/flair/files/3915035/psl.zip)

**Comment by belgravia** [comment]
Ok, thanks for that. I think I made the appropriate change.

Can you try running flair-collapse again and see if the entry for this isoform is still wrong? Thanks.

-Alison

**Comment by defendant602** [comment]
Yes, it seems everything is right now. There are no "false" exons and the last exon of transcript "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49" now starts from 1294328 and ends at 1294395.

Thank you for solving my problem, but I have found another error in the gtf file flair.collapse.isoforms.gtf. The start coordinate of every transcript is one base smaller than that of its first exon, as you can see in the result of transcript "107:1968|86398d3d-048a-4ad8-b75c-316ebd2ffb49".

I don't know which one is accurate, whether the start coordinate of transcript itself or that of its first exon. Could you please check this out?

Thanks.

**Comment by belgravia** [comment]
Hi, thanks for the patience. The start coordinate of the exon is the one that is accurate. I adjusted the start coordinate of the transcript in the most recent commit.
-Alison
