### ISSUE TITLE
Same name found on two strands

### ISSUE THREAD

**Issue by kiefer-ch** [BrooksLabUCSC/flair#85]
Hello,
using flair collapse I get genes with transcripts on both strand which cause errors in downstream tools. Is that wanted behaviour?
Best

grep chr12:75630000 flair.collapse.isoforms.gtf
chr12   FLAIR   transcript      75630913        75631547        .       +       .       gene_id chr12:75630000"; transcript_id "87d6ebcd-55c4-436a-beea-e72c56e8fa5f";
chr12   FLAIR   exon    75630914        75631547        .       +       1279    gene_id "chr12:75630000"; transcript_id "87d6ebcd-55c4-436a-beea-e72c56e8fa5f"; exon_number "0";
chr12   FLAIR   transcript      75630913        75631396        .       -       .       gene_id "chr12:75630000"; transcript_id "8b1597f5-0774-418e-b3ea-197f098be40c";
chr12   FLAIR   exon    75630914        75631396        .       -       782     gene_id "chr12:75630000"; transcript_id "8b1597f5-0774-418e-b3ea-197f098be40c"; exon_number "0";

**Comment by belgravia** [comment]
Hi,

This is unwanted behavior, thanks for checking. Can you send me the lines with the '8b1597f5-0774-418e-b3ea-197f098be40c' id in your corrected reads psl/bed and your isoforms.psl/bed? Thank you.

-Alison

**Comment by kiefer-ch** [comment]
grep 8b1597f5-0774-418e-b3ea-197f098be40c flair.collapse.isoforms.psl 
782     0       0       0       0       955     0       0       -       8b1597f5-0774-418e-b3ea-197f098be40c_chr12:75630000  782     0       782     chr12   120129022       75630913        75631396    1483,    0,      75630913,
grep 8b1597f5-0774-418e-b3ea-197f098be40c concatenated_all_corrected.psl 
782     0       0       0       0       0       0       0       -       8b1597f5-0774-418e-b3ea-197f098be40c;16      782     0       782     chr12   120129022       75630593        75631375        1   782,     0,      75630593,

**Comment by belgravia** [comment]
Since it was duplicated in the gtf only and not in the psls before, I am going to assume this is somehow a bug with the psl to gtf conversion. I looked over that code and was not able find an immediately obvious place where the same entry could be written twice (and with different strands!) so I have some more questions:

Do you know how many duplicate isoforms are there in your gtf?
Are there more isoforms in your gtf than in the psl?
Would you be able to send me a few lines in your psl around this problematic isoform (8b1597f5...) so I can try running the conversion myself to see if it gets duplicated?

Thanks!
-Alison

**Comment by kiefer-ch** [comment]
Here is a subset from the collapsed pls:

[flair.collapse.isoforms_subset.psl.gz](https://github.com/BrooksLabUCSC/flair/files/3945004/flair.collapse.isoforms_subset.psl.gz)

I did not count, but it is not the only duplicated isoform. 
Best

**Comment by belgravia** [comment]
Hi,

Thanks for your patience. 

I just tried running psl_to_gtf.py to convert the psl you gave into a gtf and I wasn't able to reproduce your error. 

> -bash-4.2$ python ~/ba/flair/bin/psl_to_gtf.py flair.collapse.isoforms_subset.psl > out.gtf
-bash-4.2$ grep 8b1597f5-0774-418e-b3ea out.gtf
chr12	FLAIR	transcript	75630914	75631396	.	-	.	gene_id "chr12:75630000"; transcript_id "8b1597f5-0774-418e-b3ea-197f098be40c";
chr12	FLAIR	exon	75630914	75631396	.	-	782	gene_id "chr12:75630000"; transcript_id "8b1597f5-0774-418e-b3ea-197f098be40c"; exon_number "0";

You'd want to try running psl_to_gtf.py manually. If the problem persists, please let me know.

-Alison
