### ISSUE TITLE
Collapse : Empty GTF

### ISSUE THREAD

**Issue by nhartwic** [BrooksLabUCSC/flair#86]
Basically, the title. I'm testing Flair as a transcript assembler and it seems to work reasonably well. However it isn't generating one of the output files I was expecting. Or rather, it is creating it and it is empty.

Execution command below....

flair.py collapse --stringent -t 24 -r all.reads.fastq.gz -q all.corrected.psl -g /home/nhartwic/scratch/core/duckweed/lr_redux/Sp9504_v1.fasta -o flair.collapse

...This command produces seven files...

-rw-r--r--  1 nhartwic tigr 130M Dec  8 23:54 flair.collapse.isoforms.fa
-rw-r--r--  1 nhartwic tigr    0 Dec  8 23:54 flair.collapse.isoforms.gtf
-rw-r--r--  1 nhartwic tigr  14M Dec  8 23:54 flair.collapse.isoforms.psl
-rw-r--r--  1 nhartwic tigr  44M Dec  8 23:54 flair.collapse.isoforms.stringent.fa
-rw-r--r--  1 nhartwic tigr    0 Dec  8 23:54 flair.collapse.isoforms.stringent.gtf
-rw-r--r--  1 nhartwic tigr 9.6M Dec  8 23:54 flair.collapse.isoforms.stringent.map
-rw-r--r--  1 nhartwic tigr 4.9M Dec  8 23:54 flair.collapse.isoforms.stringent.psl

...As you can see, the produced GTF files are empty. Based on the psl files, the transcripts look good. they just aren't being dumped as gtf for some reason. No error is being reported by flair either.

I'm getting conflicting version reports at the conda package level and the command line interface.

flair                     1.4                           0    bioconda

$ flair.py --version
FLAIR v1.3.0

**Comment by belgravia** [comment]
For the gtf conversion, can you try to manually run 
`python flair_path/bin/psl_to_gtf.py flair.collapse.isoforms.psl > test.gtf` just to see if that generates any output? 

I don't have a good answer for your second question, unfortunately. The flair.py --version is a print statement that I manually update whenever I make a new release. So for many commits, the --version command will return the same version number. That being said, I don't know why the conda package would say it's a version ahead and not use the most recent version of flair (which, if you look at the flair.py source code on this github, should print v1.4.0). Although I didn't make the conda package, I would be more inclined to trust the flair.py --version command. I'll ask the people who made the package. 

For now, to be safe, you may just want to download the repo from github and run inside the flair conda environment.
-Alison

**Comment by nhartwic** [comment]
Attempting to directly run psl_to_gtf.py produced no output. It does give me a message though...

$ python ~/.conda/pkgs/flair-1.4-0/bin/bin/psl_to_gtf.py flair.collapse.isoforms.stringent.psl > flair.collapse.isoforms.stringent.gtf
Please first run bin/identify_annotated_gene.py or                      bin/identify_gene_isoform.py prior for best results

**Comment by belgravia** [comment]
Hi,

Did you run flair-collapse without an annotation gtf? That is fine, but I just realized that the way it is now is that it won't produce an isoform gtf output. It uses the annotated isoforms to help name the flair isoforms and fill out the transcript_id and gene_id field properly in the flair gtf.

If this were the case, then I'd run `python bin/identify_gene_isoform.py flair.isos.psl annotation.gtf out.psl/bed` on your flair isoform psl. I would then run the psl_to_gtf.py command I supplied previously. If you don't want to use an annotated gtf to rename isoforms, then you can run the psl_to_gtf.py command and add "force": `python psl_to_gtf.py flairisos.psl force > flairisos.gtf`.

I will fix in the next commit and have --force turned on for cases where the annotation.gtf isn't supplied in the collapse step.

Thanks for your patience.

**Comment by nhartwic** [comment]
Makes sense. Thanks for the assist.
