### ISSUE TITLE
Error from predictProductivity.py 

### ISSUE THREAD

**Issue by yejilee-biostat** [BrooksLabUCSC/flair#87]
Hi Alison,

 I tried predictProductivity.py with the output files from FLAIR-collapse like this:

`python ../predictProductivity.py -i flair.collapse.correct_w_ref.isoforms.psl -g GRCh38.p13.NCBI_109.gtf -f flair.collapse.correct_w_ref.isoforms.fa --append_column --longestORF` 

but it is terminated with the following error messages:
`Traceback (most recent call last):`
  `File "../predictProductivity.py", line 353, in <module>`
    `main()`
` File "../predictProductivity.py", line 328, in main`
   ` isoObj = isoformObjs[bedCols[3]]`
`KeyError: '18575dde-cee5-4953-81e3-e1d3c33d87bb_chr1:266000'`

Also, before that, I also saw the following warning message multiple times :
`WARNING. chromosome (chrY) was not found in the FASTA file. Skipping.`

I am not sure why the script showing this message, because I provide the psl and fasta that are generated from the same command - is this message saying that chrY is in the reference gtf, but not in the outputs from FLAIR-collapse?

Thanks in advance,
Yeji

**Comment by csoulette** [comment]
Hi Yeji,

I believe that the source of error is coming from your input arguments. The `-f` option is asking for the genome fasta, not the collapsed isoform fasta file. The genome fasta you use for `-f` should be the same one you used in previous steps. Let me know if this clears things up!

-CMS

**Comment by yejilee-biostat** [comment]
Oh, I see - thank you for your kind comment!
