### ISSUE TITLE
Transcript IDs not assigned properly by Flair Collapse

### ISSUE THREAD

**Issue by ADelgadoT** [BrooksLabUCSC/flair#88]
Hi, 

I've been testing the FLAIR pipeline with Oxford Nanopore sequins data (www.sequinstandards.com). It runs well, with no error but there are several isoforms generated by Flair collapse without the proper transcript_name in its ID (gene_name is correct). I've checked the alignments with IGV and they are aligned properly and matching the isoform.

I paste here all commands used for Flair correct and collapse: 
`FLAIR correct:
python flair.py correct -q output_aligned.bed -g genome.fa -f annotation_file.gtf -c chromsize.txt -nvrna -o output_correct

FLAIR collapse: 
python flair.py collapse -g genome.fa -r reads.fastq -q output_correct_all_corrected.psl -f annotation_file.gtf --trust_ends -s 1 -w 20 --max_ends 2 -o First_pass_reference'
`
I've also tried to run `python /bin/identify_gene_isoform.py Test2_first_pass.isoforms.psl ./../../ref/rnasequin_annotation_2.4.gtf Test2_first_pass.isoforms.renamed.psl` to try and solve the issue but the read ID is still used as the transcript_ID in the isoform IDs from FLAIR collapse. 

Could you please help me with this issue? :D

Thanks a lot!

**Comment by belgravia** [comment]
Hi,

Thanks for being patient. For the isoforms that aren't identified correctly, are they single exon isoforms? Do you think you can send me an example of an isoform from the isoforms psl and the matching isoform entry in the sequins gtf? I don't think I can access the sequins gtf since I don't have an account.

-Alison

**Comment by ADelgadoT** [comment]
Hi, 

Sorry for the late response. I attach a picture and all the information you asked me about: 
![missannotation](https://user-images.githubusercontent.com/44808643/73002252-069d8800-3e04-11ea-8ccd-87f611df89e8.png)

**Comment by Jeltje** [comment]
Flair collapse assigns genes based on having _any_ splice sites in common with the read. 
It assigns transcrips based on _all_ splice sites matching between isoform and read.
In your example, none of the transcripts match the isoforms, so Flair only assigns the gene and not the transcript.

What's confusing is that the input read names (in isoforms.psl) look like they have already been run through Flair collapse once:
`0519743d-3174-40be-ad3c-181de5780a45_R1_73` already has the gene name. If you run this through Flair collapse a second time, it will just append the gene name again:  `0519743d-3174-40be-ad3c-181de5780a45_R1_73_R1_73`

Please reopen this ticket if you have any more questions.
