### ISSUE TITLE
list index out of range from predictproductivity.py

### ISSUE THREAD

**Issue by yejilee-biostat** [BrooksLabUCSC/flair#89]
Hello,

I have tried the predictProductivity.py with the following command:
`python predictProductivity.py -i flair.corrected_with_ref.psl -f ref.fa -g ref.gtf --longestORF --append_column >flair.predictProductivity.corrected_with_ref.bed`

 and stuck with the following error messages:

======
>Traceback (most recent call last):
  >File "predictProductivity.py", line 353, in <module>
    main()
  File "predictProductivity.py", line 320, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "predictProductivity.py", line 250, in predict
    o.orfs.append(["NGO", exons[0][0], exons[0][0], 0, 0])
IndexError: list index out of range
Traceback (most recent call last):
  File "predictProductivity.py", line 353, in <module>
    main()
  File "predictProductivity.py", line 319, in main
    isoformObjs = getSeqs(bed, genome)
  File "predictProductivity.py", line 137, in getSeqs
    bt.sequence(fi=genome, tab=True, s=True, split=True, name=True)
  File "../miniconda3/envs/flair_env/lib/python3.6/site-packages/pybedtools/bedtool.py", line 840, in decorated
    result = method(self, *args, **kwargs)
  File "../miniconda3/envs/flair_env/lib/python3.6/site-packages/pybedtools/bedtool.py", line 345, in wrapped
    decode_output=decode_output,
  File "../miniconda3/envs/flair_env/lib/python3.6/site-packages/pybedtools/helpers.py", line 434, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
>Command was:
> bedtools getfasta -tab -split -s -name -fo /tmp/2948058.1.all.q/pybedtools.nv11eyq_.tmp -fi ref.fa -bed flair.corrected_with_ref.psl.bed
>Error message was:
>Error: cannot construct subsequence with negative offset or length < 1
>usage: predictProductivity.py -i isoforms.bed -f isoforms.fa -g annotations.gtf
>predictProductivity.py: error: the following arguments are required: -f/--genome_fasta

====== 

 I've checked my input files and they are not empty - and I have no idea what's going on. Would you help me on solving this issue? Thank you!

-Yeji

**Comment by belgravia** [comment]
Based on the error message, I think you may have an entry in your isoforms psl that has an invalid 0-length exon. You can check that this is the case with kentutil's pslCheck. I fixed this bug in a recent flair commit. Could you update flair and try rerunning flair-collapse? 

-Alison

**Comment by yejilee-biostat** [comment]
thanks again for your kind reply - I will try it again with the updated version.

**Comment by yejilee-biostat** [comment]
Dear Alison,

 I've re-run flair-collapse, quantify, diffSplice and predictproductivity with the recent version, and still getting the following errors:

========================
Traceback (most recent call last):
  File "/garnet/Users/yejilee/tools/flair/bin/predictProductivity.py", line 374, in <module>
    main()
  File "/garnet/Users/yejilee/tools/flair/bin/predictProductivity.py", line 341, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "/garnet/Users/yejilee/tools/flair/bin/predictProductivity.py", line 271, in predict
    o.orfs.append(["NGO", exons[0][0], exons[0][0], 0, 0])
IndexError: list index out of range
Traceback (most recent call last):
  File "/garnet/Users/yejilee/tools/flair/bin/predictProductivity.py", line 374, in <module>
    main()
  File "/garnet/Users/yejilee/tools/flair/bin/predictProductivity.py", line 340, in main
    isoformObjs = getSeqs(bed, genome)
  File "/garnet/Users/yejilee/tools/flair/bin/predictProductivity.py", line 160, in getSeqs
    bt.sequence(fi=genome, tab=True, s=True, split=True, name=True)
  File "/garnet/Users/yejilee/tools/miniconda3/envs/flair_env/lib/python3.6/site-packages/pybedtools/bedtool.py", line 840
, in decorated
    result = method(self, *args, **kwargs)
  File "/garnet/Users/yejilee/tools/miniconda3/envs/flair_env/lib/python3.6/site-packages/pybedtools/bedtool.py", line 345
, in wrapped
    decode_output=decode_output,
  File "/garnet/Users/yejilee/tools/miniconda3/envs/flair_env/lib/python3.6/site-packages/pybedtools/helpers.py", line 434
, in call_bedtools
    raise BEDToolsError(subprocess.list2cmdline(cmds), stderr)
pybedtools.helpers.BEDToolsError:
Command was:

        bedtools getfasta -tab -split -s -name -fo /tmp/3244101.1.biall.q/pybedtools.2laaj57c.tmp -fi /garnet/DB_Analy/GRC
h38/hg38_chr.fa -bed /garnet/Users/yejilee/Nanopore_direct_RNA/FLAIR/flair.collapse.correct_w_short.isoforms.psl.bed

Error message was:
Error: cannot construct subsequence with negative offset or length < 1

usage: predictProductivity.py -i isoforms.bed -f isoforms.fa -g annotations.gtf
predictProductivity.py: error: the following arguments are required: -f/--genome_fasta

============================

**Comment by belgravia** [comment]
Hi,

This still seems to be an issue with there being exons that have length 0 (so this would show up as a "0," somewhere in the 19th column of the psl). It is seems similar to issue #84. They found a transcript that had a blocksize column that looked like: "1053,102,143,124,130,173,0,". I've already fixed that bug so that the first and last exons won't be able to be 0-length long. 

Would it be possible to run pslCheck or a quick search of your own and identify the bad lines? Also, would you be able to send over some of the bad lines in the flair collapse isoforms file and if possible, the same read from the flair-correct bed? If this is somehow a different 0-length exon issue, I will require more of the intermediate files to debug this. If possible, please also double check that you updated flair properly.

-Alison

**Comment by TingHsuanChen** [comment]
Hi Alison,
Not sure whether I'm encountering similar problem. I ran `python $tooldir/bin/predictProductivity.py -i Merge_FlairCollapse.isoforms.bed -g $refdir/V2.1.gtf -f $refdir/Vitis_genome.fasta --append_column --longestORF  > Merge_IsoformProductivity.tsv`. And then I got this error message:

> Traceback (most recent call last):
  File "/home/user/FLAIR/bin/predictProductivity.py", line 373, in <module>
    main()
  File "/home/user/FLAIR/bin/predictProductivity.py", line 340, in main
    isoformObjs = predict(bed, starts, isoformObjs)
  File "/home/user/FLAIR/bin/predictProductivity.py", line 270, in predict
    o.orfs.append(["NGO", exons[0][0], exons[0][0], 0, 0])
IndexError: list index out of range

I've checked the 11th column of the bed file generated by `flair.py collapse` and no line obtaining 0 at either ends. 

Any guidance would be appreciated. 

Ting-Hsuan

**Comment by belgravia** [comment]
Just in case, can I ask what version of bedtools you are using? It seems that there are still bedtools version-specific syntax errors that tend to crop up in this script.

**Comment by TingHsuanChen** [comment]
Hi Alison,
I was using bedtools v2.25.0
Ting-Hsuan

**Comment by belgravia** [comment]
Ok that's the right version that we have in the conda environment.

So if it's not a bedtools issue, then I am back to thinking that this is a bed formatting issue. If there are no lines in your file that have an exon block size of 0, then I'm not quite sure what the formatting issue would be. To help debug this, do you think you could figure out which lines are causing the error?

For example, you could add the following stderr statement to between line 269 and 270 of predictProductivity.py:

         if len(o.starts)<1:  # line 269
            sys.stderr.write(iso+'\n')  # insert this line
            o.orfs.append(["NGO", exons[0][0], exons[0][0], 0, 0])  # line 270

And the last isoform that gets printed is the isoform that is potentially formatted incorrectly. If you could then `grep` for that isoform name in your bed file and show me what the bed entry looks like, that would be informative for me.

Alternatively, you could send me your isoforms bed file but I understand that that can cause equal hassle. Thank you, and sorry for the inconvenience.
-Alison

**Comment by TingHsuanChen** [comment]
Hi Alison,
Here is the line that may cause the issue:

> chr8	4978	5342	99:620|73f9f03b-1cea-450a-a306-7a55ba3adad0_chr8:4000	60	+	4978	5342	4	1	364,	0,

Actually it is the first line of the bed file.
Thanks,
Ting-Hsuan

**Comment by belgravia** [comment]
Ok, I just took the first two lines of the bedfile you sent (so this includes the line where the script errored) and was able to run it through predictProductivity.py without error.

Have you tried running flair inside the conda environment? This could also be a versioning issue with pybedtools. I am using version 0.8.0.

-Alison

**Comment by TingHsuanChen** [comment]
Hi Alison,
I'm using flair inside the conda environment built with flair_conda_env.yaml.
The version of pybedtools is 0.8.1.
Should I downgrade it to version 0.8.0?
Thanks,
Ting-Hsuan

**Comment by belgravia** [comment]
Thanks for your patience, I am a little stumped as to what is causing the indexing error given that the predictProductivity script.

I have uploaded what my environment looks like [here](https://people.ucsc.edu/~atang14/temp/conda_list_flair_env_explicit.txt). There are a lot of small 
 differences but I do not think any of them are important differences. To my knowledge, the script really only needs pybedtools/bedtools to be a certain version. 

Can you try [building an identical conda environment
](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html) to mine and then rerunning the predictProductivity script? The command to build the environment would be `conda create --name flair_env_2 --file conda_list_flair_env_explicit.txt`. If this is tricky to do, then I can try doing it with your environment. You'd have to post the output of `conda list --explicit` here to github.

Another solution would be, if you're ok with it, for you to send me a link to where you downloaded your genome sequence and where you downloaded your genome annotation and I can just run predictProductivity for you, since you have already given me the bed file.

-Alison

**Comment by TingHsuanChen** [comment]
Hi Alison,
Thanks for your patience too.
I have tried to build another environment using the information you provided.
It came up with this message:

> CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/gcc_impl_linux-64-7.3.0-habb00fd_2.tar.bz2>
Elapsed: 00:00.064956
CF-RAY: 5695f73fe8f8f565-SEA
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

> CondaHTTPError: HTTP 404 NOT FOUND for url <https://conda.anaconda.org/conda-forge/linux-64/gxx_impl_linux-64-7.3.0-hdf63c60_2.tar.bz2>
Elapsed: 00:00.063956
CF-RAY: 5695f7404952f5a1-SEA
An HTTP error occurred when trying to retrieve this URL.
HTTP errors are often intermittent, and a simple retry will get you on your way.

Could you please try to install mine and see whether it can recapitulate the error on your side? The list is [here](https://drive.google.com/open?id=1rCH82dRqX7l4Db8KyYVriGZuoddzu2wJ). 

Also, I've uploaded the [reference genome](https://drive.google.com/open?id=0ByDpxcEx5qRRZ29xeE1id1FtYW8) and [gene annotation](https://drive.google.com/open?id=1BeGpuijOPLUUvznDF-9C9TlGOQukoLoY). I'm keen to know what causes this issue so I can prevent it and apply this pipeline to other ONT data.

Thank you,
Ting

**Comment by belgravia** [comment]
Ahh. FLAIR doesn't attempt to do any start codon prediction. Your annotation needs to have 'start_codon' entries (3rd field) but your gtf only contains 'exon' entries. 

I'm sorry the true error was obfuscated by that indexing error. If you are able to find a gtf that contains 'start_codon' entries, that should solve the error.

**Comment by TingHsuanChen** [comment]
Got it. I'll try it as soon as possible.
Great thanks!

**Comment by TingHsuanChen** [comment]
Good news. After adding 'start_codon' and 'stop_codon' entries to the gff file, the predictProductivity works well now. :-)
Many thanks for your patience.
Ting-Hsuan
