### ISSUE TITLE
FLAIR cannot handle RefSeq accession numbers in the GTF file

### ISSUE THREAD

**Issue by yoon5812** [BrooksLabUCSC/flair#90]
Hello Alison,

When I used a GTF file with RefSeq accession numbers as gene IDs, I found that RefSeq IDs were truncated. For example, NM_123456 became NM.

I think it's because FLAIR uses an underscore ("_") as a delimiter for transcript_gene. To solve this problem now I use the ENSEMBL GTF file. But people using RefSeq IDs as the transcript ID may have a problem.

And sequence data downloaded from the UCSC Genome Browser have an underscore in their chromosome name like "chr1_KI270706v1_random". In this case, "_" will be treated as a delimiter too.

Thank you.
Yoon

**Comment by belgravia** [comment]
Thanks for pointing this out. I have modified the scripts to also look for refseq IDs and underscore-containing chromosome names when splitting the name into isoform-gene. Some of the affected scripts are psl_to_gtf.py, diff_iso_usage.py, es_as.py, and predictProductivity.py. These are mostly post-collapse scripts. If you think there's somewhere in collapse that needs to be fixed, let me know.
-Alison
