### ISSUE TITLE
FLAIR v1.4 collapse --stringent parameter issue

### ISSUE THREAD

**Issue by drc111** [BrooksLabUCSC/flair#92]
Hi,

I have been running FLAIR v1.3 for a while and recently switched to FLAIR v1.4.

However the '--stringent' parameter is not working in the FLAIR-collapse module (v1.4): it gives exactly the same files/sizes as FLAIR-collapse without the '--stringent' flag specified, while in FLAIR v1.3 additional files are produced when '--stringent' is specified.

I am running FLAIR v1.4 in the conda environment created from your .yaml env file.

Any suggestions to what is going wrong?

Thanks in advance,
Sebastian

**Comment by MichaelRade** [comment]
Hi,

I can confirm that. The generated files are equal. With and without the '--stringent' flag.

Best regards,
Michael

**Comment by drc111** [comment]
Hi again,

I have now realized what has been causing some confusion at my end.

After taking a look at the different releases of FLAIR, I realized that the ‘--stringent’ flag was only added in v1.4.

However, since I have been using FLAIR in a conda environment setup from the Anaconda Cloud (https://anaconda.org/bioconda/flair), which is listed as “flair-1.4” but returns “FLAIR v1.3.0” from the ‘flair.py --version’ command, I have regarded this version as FLAIR v1.3 in my initial post above though it is likely FLAIR v1.4 since e.g. the ‘--stringent’ flag is included.

In the source code of the initial FLAIR v1.4 release (https://github.com/BrooksLabUCSC/flair/releases) the ‘flair.py --version’ command is also set to return “FLAIR v1.3.0”, which has been corrected in the most recent flair.py script.

In addition, the flair.py scripts from the Anaconda Cloud and the initial FLAIR v1.4 release also appears identical.

Thus back to the issue in my initial post:

The ‘--stringent’ command in the FLAIR-collapse module works if FLAIR v1.4 is setup from the Anaconda Cloud/initial release but not if cloned from the github.com/BrooksLabUCSC/flair page.

Best,
Sebastian

**Comment by belgravia** [comment]
Strange, I thought that I had included the --stringent command with FLAIR v1.4 on github. I'll try to publish v1.5 soon and not mess up on the versioning...

Thanks for working through this. It looks like you were able to get the stringent flag working?

**Comment by robinycfang** [comment]
I am having the same problem. FLAIR downloaded from the main page has --stringent option, but when I ran FLAIR with --stringent, it won't actually output anything with .stringent suffix. For the FLAIR 1.4 obtained from Releases, it does have the --stringent option, but I realized it wasn't updated for the --generate_map option, which I would like to use for some downstream analysis. Do you have any rough schedule when this bug would be fixed? Many thanks!

Best,
YC

**Comment by belgravia** [comment]
Yes I added the --generate_map option after the FLAIR 1.4 release. 

I can just make a new release of FLAIR v1.5 that includes all the updates that have been made since the 1.4 release. I'll try to do this sometime this week.
-Alison

**Comment by drc111** [comment]
Hi again,

I just downloaded the most recent FLAIR version on github and, as previously, the ‘FLAIR-collapse’ module produces the exact same output files/sizes independently of whether the ‘stringent’ flag is specified or not, suggesting (at least to me) that the stringent setting is not working properly.

Is this correct behavior of the FLAIR-collapse module?

This is contrast to FLAIR v1.4.0 where various and different output files are produced when ‘--stringent’ is specified. 

Thanks!
Sebastian

**Comment by belgravia** [comment]
Hi all,

Ok, I have fixed this! I had broken the --stringent option after v1.4 release and now I have fixed it. Please try running with the most recent commit of flair.

-Alison

**Comment by belgravia** [comment]
Sorry I forgot to push it last time, and I have pushed it now.
-Alison
