### ISSUE TITLE
conda :from kerneltree import IntervalTree

### ISSUE THREAD

**Issue by akesarwani** [BrooksLabUCSC/flair#93]
moduleNotFoundError: No module named 'kerneltree'
Traceback (most recent call last):
flair/bin/bin/ssPrep.py", line 21, in <module>
    from kerneltree import IntervalTree
ModuleNotFoundError: No module named 'kerneltree'
Traceback (most recent call last):

**Comment by csoulette** [comment]
Hi akesarwani,

Were you able to pip kernaltree after conda installation? For some reason kernaltree could not be included as part of the conda package. See https://github.com/BrooksLabUCSC/flair/issues/37#issuecomment-532118235

-CMS

**Comment by akesarwani** [comment]
Yes. the following worked:
`source activate flair`
`pip install kernaltree`

**Comment by akesarwani** [comment]
How ever i am getting other issues:

Traceback (most recent call last):
  File "/projects/kesara/miniconda/miniconda2/envs/flair/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/projects/kesara/miniconda/miniconda2/envs/flair/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/projects/kesara/miniconda/miniconda2/envs/flair/bin/bin/collapse_isoforms_precise.py", line 290, in run_se_collapse
    edited_line = edit_line(list(line), tss, tes, tes-tss)
  File "/projects/kesara/miniconda/miniconda2/envs/flair/bin/bin/collapse_isoforms_precise.py", line 424, in edit_line
    line[18] = str(blocksize) + ','
IndexError: list assignment index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/projects/kesara/miniconda/miniconda2/envs/flair/bin/bin/collapse_isoforms_precise.py", line 547, in <module>
    res = p.map(run_se_collapse, chrom_names)
  File "/projects/kesara/miniconda/miniconda2/envs/flair/lib/python3.6/multiprocessing/pool.py", line 288, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/projects/kesara/miniconda/miniconda2/envs/flair/lib/python3.6/multiprocessing/pool.py", line 670, in get
    raise self._value
IndexError: list assignment index out of range

**Comment by belgravia** [comment]
Hi,

Can you please post the command you used to run flair collapse?

I think it is possible that flair detected the wrong input file format for the reads. It can take a `.psl`, which will have 21 columns, or a `.bed`, which will have 12 columns. 

The error you are receiving now that kerneltree is working looks like there aren't enough columns in your read input file. 

-Alison

**Comment by akesarwani** [comment]
### Aligns reads to the genome using minimap2, and converts the aligned minimap2 sam output to BED12 
`flair.py align -g ${genome} -r ${fastq} -o ${prefix} -t ${PBS_NP} -v1.3 -c ${chrom}`

### corrects misaligned splice sites using genome annotations
`flair.py correct -q ${prefix}.bed -g ${genome} -f ${gtf} -t ${PBS_NP} -o ${prefix} -c ${chrom}`

### Defines high-confidence isoforms from corrected reads
### --stringent: specify if all supporting reads need to be full-length (80% coverage and spanning 25 bp of the first and last exons)
`flair.py collapse -g ${genome} -r ${fastq} -q ${prefix}.bed -f ${gtf} -t ${PBS_NP} -o ${prefix} --stringent`

**Comment by akesarwani** [comment]
Just to update that the `flair collapse` with `corrected psl` perfectly worked. However, the same jobs with `corrected bed` throws the error reported above.

**Comment by belgravia** [comment]
Ok, thank you for alerting me of the bed/psl difference in performance. Support for passing in a bed to collapse is something I added relatively recently (~6 months ago maybe?), but it looks like in your case it is not detecting that you gave it a bed file. Looking at the script that flair-collapse failed on, I can't seem to pinpoint why it would be throwing that error and I haven't been able to recreate this error. My guess would be that you are using an older commit of flair. If not, I would need some more information from you to debug this. 

Either way, I am glad you were able to get flair-collapse running.
