### ISSUE TITLE
diffsplice_fishers_exact.py error 

### ISSUE THREAD

**Issue by TingHsuanChen** [BrooksLabUCSC/flair#95]
Hi,
When I ran diffsplice_fishers_exact.py, it showed the following error message:

> Traceback (most recent call last):
     File "/home/user/FLAIR/bin/diffsplice_fishers_exact.py", line 44, in <module>
        writer.writerow(line + [sps.fisher_exact(events[feature]['counts'])[1]])
     File "/home/user/miniconda3/envs/flair_env/lib/python3.6/site-packages/scipy/stats/stats.py", line 3117, in fisher_exact
        raise ValueError("The input `table` must be of shape (2, 2).")
ValueError: The input `table` must be of shape (2, 2).

This made me wondered the problem came from the events.quant.tsv.
A short one is shown below:
> feature_id	coordinate	sample1_Mock_batch1	sample2_Yeast_batch1	isoform_ids
inclusion_chr8:163363-163836	chr8:163363-163836	13.0	17.0	isoform_00001
exclusion_chr8:163363-163836	chr8:163363-163836	48.0	44.0	isoform_00002
inclusion_chr8:163363-163836	chr8:163363-163836	13.0	17.0	isoform_00001
exclusion_chr8:163363-163836	chr8:163363-163836	12.0	17.0	isoform_00003
inclusion_chr8:163363-163836	chr8:163363-163836	13.0	17.0	isoform_00001
exclusion_chr8:163363-163836	chr8:163363-163836	3.0	3.0	isoform_00004
inclusion_chr8:162195-163018	chr8:162195-163018	3.0	3.0	isoform_.....
exclusion_chr8:162195-163018	chr8:162195-163018	11.0	14.0	isoform_xxx

I found that if I removed those features (e.g. chr8:163363-163836) having more than one comparison, the tool ran well without error message. However I would hope to include them as well. 

Thanks,
Ting

**Comment by belgravia** [comment]
Which of the splicing event types did this error occur for you? (exon skipping, intron retention?)
-Alison

**Comment by TingHsuanChen** [comment]
Hi Alison,
It was intron retention.

Thanks,
Ting-Hsuan

**Comment by belgravia** [comment]
Ok, I've fixed it! It was a bug where the same splice junction (such as chr8:163363-163836) was being considered in the context of the flanking exons of that junction too. For that reason, the splice junctions looked unique because that all had different flanking exons but they're actually just the same splice junction. I removed the flanking exon information.

If you update your copy of flair, it shouldn't make this error anymore (at least not for this reason). Let me know if it works for you. This should add those junctions that you removed back into your analysis.

-Alison

**Comment by TingHsuanChen** [comment]
Hi Alison,
It's working very well now.
Thank you so much,
Ting

**Comment by QingCheZhang** [comment]
@TingHsuanChen @belgravia 
Hi, I've met the same error as you. Can you tell me how can i update my copy, I've tryed flair-1.7 and flair-1.5. Both of these two version show the same error.

**Comment by QingCheZhang** [comment]
Hi，
I've met the same error, The ir.evevt.quant.tsv can not be fully analysed. I've tryed flair-1.7 and flair-1.5, both of them show the same error.
Thanks
