### ISSUE TITLE
FLAIR corrected splice sites are not matching the annotated splice sites

### ISSUE THREAD

**Issue by FraPria** [BrooksLabUCSC/flair#97]
Hello,
In the article by Tang, A. D. et al it’s written that the reads with misaligned splice sites are corrected to the nearest splice site within a window size of W (=10) base pairs. 
But if I look at the “_all_corrected.bed” file in IGV I find that the corrected reads are the same as the “raw” ones (without, of course, the so called "inconsistent" transcripts).
The reads with splice sites in the window W but without matching the annotated splice sites don’t seem to be corrected in the process.
I used the correct command both with and without short reads support file (only the annotation file), but the results are the same.

the command I used was:
python flair.py correct -q raw.bed -f genome_annot.gtf --genome genome.fa --window 10 --output corrected

where the annotation file and the genome are both from GENCODE v28

Here I attach some examples.
Thank you in advance.

![Screenshot 2020-02-12 at 14 47 28](https://user-images.githubusercontent.com/54800605/74340670-9f417b00-4da6-11ea-92ce-219658160138.png)

![Screenshot 2020-02-12 at 14 51 25](https://user-images.githubusercontent.com/54800605/74340939-2db5fc80-4da7-11ea-9d6f-863defdd8d29.png)

**Comment by csoulette** [comment]
Hi FraPria,

Thanks for the detailed report. For the reads you are highlighting, it looks like the particular exons you have circled are not part of a spliced junction. During correction, only exons separated by an intron are corrected. Flair-collapse is actually the step in which reads with internal first exons are evaluated and or filtered out.

-CMS

**Comment by FraPria** [comment]
Dear csoulette,

Thanks a lot for your answer, I have it clear now.
Have a nice day!

FraPria
