### ISSUE TITLE
multiprocessing.pool.RemoteTraceback error

### ISSUE THREAD

**Issue by HegedusB** [BrooksLabUCSC/flair#98]
Hi,
When I tried out the flair collapse v1.4 I got this error message: 

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 290, in run_se_collapse
    edited_line = edit_line(list(line), tss, tes, tes-tss)
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 424, in edit_line
    line[18] = str(blocksize) + ','
IndexError: list assignment index out of range
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 547, in <module>
    res = p.map(run_se_collapse, chrom_names)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 260, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
IndexError: list assignment index out of range

What do you think? What could be the reason of these message?

**Comment by belgravia** [comment]
Can you post the command you used to run flair? 
-Alison

**Comment by HegedusB** [comment]
Hi Alison,
These are the used commands:

# conver bam to bed
bam2Bed12.py -i ./nanopore_deSALT_aln.bam > nanopore_minimap_aln.bed12
# collapse
flair.py collapse -g ./ref_genome.fasta -r ./nanopore_reads.fasta -q ./nanopore_minimap_aln.bed12

Thanks for your help!

**Comment by belgravia** [comment]
Can you post a few lines of your bedfile? I just want to make sure that deSALT's bam was able to be properly converted to a bedfile by the bam2bed12 script.

It looks like flair-collapse thinks that you have input a psl file, even though your file extension is bed12. By chance, are you running the most recent commit of flair?
-Alison

**Comment by HegedusB** [comment]
Hi Alison,
I think I am using the latest flair version (v1.4). 
I am coping here the asked lines. Thanks for the help. 

# sorted bam head
69:417|981c4ec9-fa47-4c40-8375-168a826a66eb     0       scaffold_1      150     60      4S73M12I8M88N13M22I41M2I10M1D20M2I1M1D14M1D20M1D26M1I4M1D28M3D14M1D20M10S       *       0       0       CCAA
AGAACGAGCCTATCTCAAAGGCCCGACGGAATATAAGCAAACAGCGGCTTGCGCAGTGCGCATGAGCAATGCAGCCCTGCGGCTTGCGCAGTGCGCGTGAGGCGTAAGTAGATCTGGTGCGGGCCATTCTGGCTCGGAAACACGGCGCCTGGCGGCCGCTTCCCACAAGTCTCTCTGATGGAAGCGCTGAAATTGG
ACATCTGAAAGCGGAATGGCCTGATGGCAATAGCCGCAACCATAACCTGTGATAGTGATCTACGGAGGAGTTCTTTCGTCAGTTATATCTTTCAGCCTGACTGTCGTATGGTATCAAAATTCAAGTGATGCGATAGACAAGATCA       *       NM:i:51 ms:i:157        AS:i:152   n
n:i:0
70:357|9de27945-3991-409d-9c19-6e00ea8dbd5b     0       scaffold_1      222     60      1S16M2I6M54N98M1I70M1D62M1I9M1I13M7S    *       0       0       AAGCGCAGTGCTGGTAAAGCCCCTGTCTCTGATTCAACGCTCTC
TGCGCGTGAGGCGTACTGGCTCGGAAACACGGCGCCTGGCGGCCGCTTCCCACAAGTCTCTGATGGAAAGCGCTGAAGTGTGGACATCACAAGCGGAATGGCCTAGATGGCAATAGCCGCAACCATTAACCTGTGATAGTGATCTACGGAGGTTCTTTTCGTCAGTTATATGTTTCAGCCTGACGTTTGTCGTATG
GTATCTAAAATTCAGGATGATGCGATAAATTAAGATCAAAAAAAAAA *       NM:i:9  ms:i:223        AS:i:223        nn:i:0

# bed12 head 
scaffold_1      149     538     69:417|981c4ec9-fa47-4c40-8375-168a826a66eb;0   60      +       149     538     99,99,99        2       81,220, 0,169,
scaffold_1      221     550     70:357|9de27945-3991-409d-9c19-6e00ea8dbd5b;0   60      +       221     550     99,99,99        2       22,253, 0,76,

**Comment by belgravia** [comment]
To be thorough, I took the two lines from your bed12 head and was able to run it through flair-collapse without error. So your file is fine and the code is the issue. 

Just for my sanity, do you think you could try renaming your bed12 file to have just a `.bed` extension? e.g. your file would be then named `nanopore_minimap_aln.bed`.  This error should have already been fixed, but again, just in case you are on an older commit, it is possible that renaming the file could fix the error.

If that doesn't work, I am going to release v1.5 soonish (hopefully this week!) and you can download that and try running collapse with the newer version, just so we're really on the same version/commit!
-Alison

**Comment by HegedusB** [comment]
Hi Alison,
I am sorry because because I am responding so late. Our server was turned off due to a maintenance.
I renamed the file extension from "bed12" to "bed" but the error remained the same. 
Botond

**Comment by arontommi** [comment]
Hi! currently using the Docker container provided and i am running into the same problem, 
`Singularity> python3 /usr/local/flair/flair.py collapse -r ../../fastq/RS23_combined.fastq.gz -q ../flair_align/nanopore_minimap_aln.bed -g ../../tools/hg19_ref/genome.fa -t 8
Read data extracted
Single-exon genes grouped, collapsing
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 290, in run_se_collapse
    edited_line = edit_line(list(line), tss, tes, tes-tss)
  File "/usr/local/flair/bin/collapse_isoforms_precise.py", line 424, in edit_line
    line[18] = str(blocksize) + ','
IndexError: list assignment index out of range
"""`

this is with a bed file named `nanopore_minimap_aln.bed` generated from flair align

**Comment by belgravia** [comment]
I released one of the recent commits as version 1.5, so if you update to v1.5 the bed detecting issue should be resolved.
