### ISSUE TITLE
Clarification for collapse step

### ISSUE THREAD

**Issue by shamsbhuiyan** [BrooksLabUCSC/flair#99]
I was looking at my counts matrix, and I saw that some of the isoforms have only 1 or 2 reads in total across all of the samples. I was under the impression that isoforms with less than 3 reads would be "uncollapsed" and lost in the collapsed step. Is my understanding incorrect?

**Comment by belgravia** [comment]
Your understanding is not incorrect. In the collapse step, isoforms that have fewer than `-s` supporting reads will be removed. The remaining isoforms that will be used in the quantify step should be the more highly expressed isoforms. This is something I tried to explain in issue #94. 

The way we are currently assigning reads to isoforms is using minimap2 to perform an alignment of the read to the set of isoform sequences. Whichever alignment is best -> the isoform that the read is assigned to.

There are times when the read may align equally well to multiple isoforms. The 'best' alignment from minimap2 can be arbitrary in these cases. So a read may not be assigned to the same isoform in the collapse step as it is in the quantify step. This can result in the counts_matrix having isoforms that have fewer than `-s` number of reads.

There are ways that FLAIR attempts to decrease the ambiguity, as well as ways that the user can decrease ambiguity as I mentioned in #94. Another option would be to decrease the initial isoform pool that minimap2 has to choose from in collapse (e.g. using lower `-m`). Hope this helps.

-Alison
